### ISSUE TITLE
experimental: make Minify functions write to bytes buffer, not direct to io.Writer

### ISSUE THREAD

**Issue by bogem** [tdewolff/minify#103]
I've just read the code and noticed, what minifiers are writing directly to given `io.Writer`, but if given writer would be file, it will cause a lot of `syscall`s and will slow down the minify process. I rewrote code and make so, what minifiers are writing to `bytes.Buffer` and then are calling `io.Copy(w, buf)`. Here you can see benchmarks:
HTML (minifying amazon home page)
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkMinifyHTMLFromFileToFile-4     310047765     33907712      -89.06%

benchmark                               old allocs     new allocs     delta
BenchmarkMinifyHTMLFromFileToFile-4     41             57             +39.02%

benchmark                               old bytes     new bytes     delta
BenchmarkMinifyHTMLFromFileToFile-4     281955        2169332       +669.39%
```

CSS (minifying gumby)
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkMinifyCSSFromFileToFile-4     79784251      7325521       -90.82%

benchmark                              old allocs     new allocs     delta
BenchmarkMinifyCSSFromFileToFile-4     2207           2167           -1.81%

benchmark                              old bytes     new bytes     delta
BenchmarkMinifyCSSFromFileToFile-4     957533        1379221       +44.04%
```

JS (minifying jquery)
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkMinifyJSFromFileToFile-4     92260008      7364556       -92.02%

benchmark                             old allocs     new allocs     delta
BenchmarkMinifyJSFromFileToFile-4     16             27             +68.75%

benchmark                             old bytes     new bytes     delta
BenchmarkMinifyJSFromFileToFile-4     4916          397861        +7993.19%
```

As you can see, memory consumption noticeably increased, but I think, in this case performance  is higher in priority than memory consumption.
If you like this idea, let me know and I'll make a PR.

**Comment by tdewolff** [comment]
Yes this is true, but it is on purpose. The input is buffered (because it is a very specialized buffering tailored for the lexers). The output is however an io.Writer, the user can use any buffering or whatever they choose for the writer. It is trivial for users to add output buffering, plus if they don't want buffering (eg. direct result) that is also possible. The concept of `io.Writer` is that you can use any kind of writer without restrictions, I'd like to keep it that way.

That said the docs could make it more clear that performance is better with output buffering.

**Comment by tdewolff** [comment]
Oh it's pretty clear in the readme: https://github.com/tdewolff/minify#usage

**Comment by bogem** [comment]
Yes, it's better in your. I agree with you, what it should be user's choice to which writer should write minifier.

**Comment by bogem** [comment]
I will close this issue, because it's already written in usage and, as said, it's users' choice to which writer should be minified code written.
