### ISSUE TITLE
cmd: blank -o flag doesn't print to stdout

### ISSUE THREAD

**Issue by bogem** [tdewolff/minify#105]
In help it said, what if I use blank -o flag, minified data will be printed in `stdout`, but it doesn't work so:
![2016-10-16 9 41 27](https://cloud.githubusercontent.com/assets/13235519/19416023/35410178-9385-11e6-9a92-7355235c7a25.png)
It will print to `stdout` only, if I enter blank input.
It should be either documented or fixed, but I think it logically to fix this.

**Comment by tdewolff** [comment]
Yes, you're right. Depends on the defaults we want:

- one input file and no output file = stdout or overwrite?
- multiple input files and no output file = concatenate to stdout or overwrite themselves?
- multiple input files and one output file/directory = concatenate to file output or write files to directory output?

The first case should probably be stdout, as per the docs. This is safer, so people don't accidentally overwrite their original files.

The second case should probably concatenate to stdout then too, but then I'd like to drop the concat flag, as it is not necessary in this case.

The third case has a problem, how do we know that the users wants to output to a file or to a directory? If they pass `concat` we know it outputs to a file, but as per the second case it would be better to remove the `concat` flag. If we are to say that to specify an output directory the user has to append `/` at the end, it would solve this case. It would resolve the ambiguity of whether the output path is a file or a directory.

**Comment by bogem** [comment]
I think, it could be implemented so: if there is blank -o flag, then obviously output to stdout. And cmd should overwrite file, only if name of input file and output file are same. 
And in third case it could be did as you said: `specify an output directory the user has to append / at the end`. But obviously it should be documented.

**Comment by tdewolff** [comment]
The nice thing now though is that you can run `minify` in a directory and let it minify all files in that directory (and overwrite themselves), I find that very convenient, but it collides with what I wrote earlier about case two...

**Comment by bogem** [comment]
But in my workflow it's different.I have `src` (not minified, human readable source files) and `dist` (minified and concatenated files) directories and it wouldn't be nice if all my `src` will be minified.
IMHO flag `overwrite` is overwhelmed. If you want to overwrite your directory, user can execute `minify -o dir/ -r dir` and it will be obvious, what `minify` will overwrite files.

**Comment by bogem** [comment]
Also `os.FileInfo.IsDir' can detect if the path is directory or usual file

**Comment by tdewolff** [comment]
Yes exactly. If the path given is already a dir, it will assume directory output. Otherwise it is necessary to append the output by a slash.

I'm actually implementing this now :)

**Comment by tdewolff** [comment]
Fixed in 452cafca37a41058fa9c9a15d73b431c328b604f
