### ISSUE TITLE
Leading bang(!) syntax of 3rd party minifiers produces invalid js when re-minified

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/minify#107]
**Test case**

```js
var a='1';
var b='2';
var c='3'
!function(){
  console.log(a + b + c );
}();
```

Minifies to:

```js
var a='1';var b='2';var c='3'!function(){console.log(a+b+c);}();
```

Which results to (in Chrome debugger console):

```js
Uncaught SyntaxError: Unexpected token !
```

**Cause**

Some minifiers use the bang syntax to save some characters with closures (see http://stackoverflow.com/questions/5827290/javascript-function-leading-bang-syntax).

When I concatenate several scripts, some are already minified, some are not. I could join them with a `;` in between but there's still the case when this occurs is the same file like shown here.

Is it something feasible on your end or should I handle this case in userland?

**Comment by tdewolff** [comment]
Well, the JS minifier must never make valid JS code invalid, so this is a bug that should be fixed!

**Comment by tdewolff** [comment]
Easier than I thought ;-)

**Comment by mikegleasonjr** [comment]
So it minifies with a newline between the statements is that it? Not a semicolon?

**Comment by tdewolff** [comment]
Yes, it doesn't matter anyways. A semicolon and a newline are both 1 byte and they mean the same in JS (because of automatic semicolon insertion (ASI) at newlines). By preferring newlines over semicolons the minified source at least has _some_ newlines, which is slightly more readable than just one long line.
