### ISSUE TITLE
Multiple empty statements are not removed

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/minify#108]
```js
var a='1';
;
;
```

minifies to `var a=1;;;`

Not sure if you want to do it, feel free to close and 'wontfix'

**Comment by tdewolff** [comment]
Yes this is not ideal. The JS minifier is very simplistic at the moment, and the example is very uncommon. So I'll make this a wontfix. As soon as there comes a better JS minifier (if there ever comes one), this would automatically be solved.
