### ISSUE TITLE
"Syntax error: Unexpected string"

### ISSUE THREAD

**Issue by andreynering** [tdewolff/minify#109]
I'm getting this errors in few lines where a `;` was missing in the minified file. Cases like this:

```js
function(){}"foo"?"bar":"baz"
```

```js
a.b={}"foo"&&something()
```

```js
a.b=false"foobar".split(...)
```

I think probably there was a line break there, and a `;` should be inserted?

I tried to put these `;`s and the file worked, there was no other errors.

**Comment by tdewolff** [comment]
It should keep the line break in these instances, I'm on it!

**Comment by tdewolff** [comment]
This seems a problem with the original JSMin implementation as well

**Comment by andreynering** [comment]
Thank you, I confirm it works now.
