### ISSUE TITLE
JS minification causes syntax error in some circumstances (no newline)

### ISSUE THREAD

**Issue by Xiol** [tdewolff/minify#113]
Hi,

We've encountered a problem whereby we're minifying and combining two JS files, where the first file doesn't end with a new line, can cause syntax errors in the browser. Here's some example code that demonstrates this:

File 1:
```javascript
function some_stuff() {
    return false;
} // No newline here
```

File 2:
```javascript
$(document).ready(function() {
    alert("Hello");
});
```

Resulting script:

```javascript
function some_stuff(){return false;}$(document).ready(function(){alert("Hello");});
```

I don't think this is a problem is many scenarios, I think it's just because the second file does the `$(document)` stuff which can cause problems (I'm not a JS dev, so I have no idea what's acceptable syntax).

Thanks

**Comment by tdewolff** [comment]
The minifier assumes that the supplied JS is valid. In this case, the concatenated JS files are invalid, and so is the minified result. I suggest you insert a newline manually between the two sources so that it becomes valid. Let me know if it works.

**Comment by Xiol** [comment]
Yeah, the solution we used was to add newlines to the end of all the files, however it would be nice if this could be detected during minification to ensure the combined result is valid if the source files themselves are missing newlines.

**Comment by tdewolff** [comment]
Is this when using the command line interface? I think that would be a valid feature, as concatenation is a feature of the tool. It would be out-of-scope for the library though, as it expects valid input (for all minifiers).

**Comment by Xiol** [comment]
Sorry, I should have clarified - this is with the command line tool, yeah.
