### ISSUE TITLE
SVG minifier corrupts url(#...) by lowercasing it

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#117]
Here's gist with before/after minification: https://gist.github.com/RReverser/a4f31f7f4321cd17e5b653b31ed04ef7

The only difference is that `url(#SVGID_1_)` and `url(#SVGID_2_)` got lowercased, and IDs are case-sensitive (looks similar to #99), so references become invalid and image gets rendered incorrectly.

**Comment by tdewolff** [comment]
Thanks for the bug report, I will look into it shortly.

**Comment by tomByrer** [comment]
Aren't URLs supposed to be case insensitive?
https://url.spec.whatwg.org/#url-syntax

**Comment by tdewolff** [comment]
This happens for the `stroke` attribute as it doesn't expect a CSS-style URL reference.

@tomByrer I don't think it states that the fragment is case-insensitive. As far as I can see only the scheme is case-insensitive.

**Comment by RReverser** [comment]
@tdewolff It would happen for e.g. `fill` attribute too as it supports same syntax.

Just for the reference, found relevant SVGO issue https://github.com/svg/svgo/issues/372

**Comment by RReverser** [comment]
This should be the full list of properties that allow URLs / SVG fragment identifiers, in spec: https://www.w3.org/TR/SVG/linking.html#processingIRI

However, it's probably safer to always preserve casing.
