### ISSUE TITLE
minify should never overwrite the original

### ISSUE THREAD

**Issue by tatsujin1** [tdewolff/minify#118]
If running the minify tool on a single input file and specify no output, it will overwrite the original input file.

I think we can all agree that this is never a good thing to do.
Luckily I tested it on a small file. (no, of course I hade no backups! backups are for cowards!)

edit: this was version 2.0.0.

**Comment by omeid** [comment]
Use version control.

**Comment by tdewolff** [comment]
The new version of the CLI requires you to explicitly set the output filename equal to the input filename. If either is left blank, stdout or stdin is used. Please update to master, a new release is on the way though!
