### ISSUE TITLE
HTML inline SVG drops tag following enclosure

### ISSUE THREAD

**Issue by Nycroth** [tdewolff/minify#119]
When parsing an HTML file with SVG inline like the following:
```html
<a href="https://nycroth.com/">
    <svg>
        <path d="m6,2"/>
    </svg> Logo Text
</a>
<br>
```
After the `</svg>`, all data up to and including the next tag will be removed like so:
```html
<a href="https://nycroth.com/"><svg><path d="m6 2"/></svg><br>
```

Haven't had enough time to track it down myself. Figured I should post first to start the issue hunt. Confirmed issue with http://go.tacodewolff.nl/minify.

**Comment by tdewolff** [comment]
Thanks for the bug report, I will look at it shortly!

**Comment by Nycroth** [comment]
Write-up so far:
It seems the lexer assigns text following the <svg> as type Attribute (probably because it pulls the entire <svg>...</svg> section into a single Svg). For example the above gives the following tagging (pulled from buffer.go:Shift()):
```
Debug: StartTag (<a)
Debug: Text (
)
Debug: Svg (<svg>
        <path d="m6 2"/>
    </svg>)
Debug: Attribute ( logo)
Debug: Attribute ( text)
Debug: Attribute (
</a)
Debug: StartTagClose (>)
Debug: Text (
)
Debug: StartTag (<br)
Debug: Text (
)
Debug: Error ()
```
