### ISSUE TITLE
Allow disabling endtag stripping

### ISSUE THREAD

**Issue by adtac** [tdewolff/minify#120]
`minify` is removing my `</li>` tags, which shouldn't happen sometimes because these `li`s are wrapped around a `<a></a>`. Without the `</li>`, the whole thing breaks down.

**Comment by tdewolff** [comment]
Wrapping `li` with `a` is not allowed in HTML. This packages follows the spec closely, so sorry this is not possible.

**Comment by adtac** [comment]
At least allow an option to not remove end tags at all?

**Comment by adtac** [comment]
I've added this feature (keeping ALL end tags) and made a pull request here: https://github.com/tdewolff/minify/pull/121

**Comment by tdewolff** [comment]
This is now fixed with #121
