### ISSUE TITLE
svg tag usage

### ISSUE THREAD

**Issue by aydos** [tdewolff/minify#123]
Hi,
On my webpage there is a blank svg space, and I use there with d3.js plus my code. Minify deletes it. What is the best usage of minify on such case?
```<svg id="svg" width="100%" height="400"></svg>```

**Comment by tdewolff** [comment]
You could use `&nbsp;` as a placeholder. I might need to relax the removal of certain empty tags since they are usually filled by JS. Such tags are usually `div`, `span` or `svg`.

**Comment by aydos** [comment]
Yes... it works...
In my case it returns ```<svg id="svg" height="400"/>``` ie loosing width but I can handle with js I think. Thanks.

An alternative: you may check not empty id tag for js, not empty class tag for design in general, if you like. This will cover not all but most cases.

**Comment by tdewolff** [comment]
What do you mean the `width` tag is removed?

This last commit will keep empty SVG tags as a self-closing tag. This is probably wanted for 99% of the cases.

**Comment by aydos** [comment]
```width="100%"``` was removed. I fixed it within javascript. There is no problem for me now. Thanks.

To be clear, with latest minify I downloaded
```<svg id="svg" width="100%" height="400"> </svg>```
minified to
```<svg id="svg" height="400"/>```

**Comment by tdewolff** [comment]
That is correct behaviour since `100%` is the default value for the width: https://www.w3.org/TR/SVG/struct.html#SVGElement
