### ISSUE TITLE
Big number problem

### ISSUE THREAD

**Issue by awsom82** [tdewolff/minify#124]
Recently, i found thats in my HTML in-line CSS hack not working properly.
It become after minify replaces `left: -5000px;` to this one `left:-5e3px`.

full code tag before minification:
`<div style="position: absolute; left: -5000px;" aria-hidden="true">`

**Comment by tdewolff** [comment]
I've tried this in CodePen, but this doesn't seem to be a problem:

<p data-height="265" data-theme-id="0" data-slug-hash="GtqKj" data-default-tab="html,result" data-user="mobify" data-embed-version="2" data-pen-title="CSS Test — Button" class="codepen">See the Pen <a href="https://codepen.io/mobify/pen/GtqKj/">CSS Test — Button</a> by Mobify (<a href="http://codepen.io/mobify">@mobify</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

I believe the transformation is valid CSS, are you sure it is not something else that is broken?

**Comment by nurlansu** [comment]
Hey, I can actually confirm this issue. But, I don't think that's minify related problem. It's actually browser compatibility issue. I could test it on the last versions of Chrome, Safari and Firefox. And only Safari couldn't display it properly. The warning in console says: "The value is not supported for this property".
Attached some screenshots of @tdewolff pen :
This is how it looks in Chrome :
![chrome](https://cloud.githubusercontent.com/assets/14142638/23582472/1e13203a-012b-11e7-885d-ed0efb721bab.png)
And this is how it looks in Safari :
![safari](https://cloud.githubusercontent.com/assets/14142638/23582479/4bc53824-012b-11e7-9708-db24e7b98f18.png)

**Comment by awsom82** [comment]
Guys, sorry for late reply. Yeah, it's only seems to be a Safari v10.0.3 (current stable release) issue.

I test on Safari Technology Preview (Safari 10.2, WebKit 12604.1.6) and it works well,
![Safari TP R24 ](https://cloud.githubusercontent.com/assets/5804704/23582751/46e14444-0142-11e7-993c-5c36bfb9c51f.png)

**Comment by tdewolff** [comment]
`left` is supposed to have a `<length>`, `<percentage>` or `calc()` value. A `<length>` starts with a `<number>` (see https://drafts.csswg.org/css-values-3/#numbers) which may contain exponential terms.

I believe this is a bug of Safari and thus will not be fixed in this library.

**Comment by awsom82** [comment]
Few days ago Apple released new Safari 10.1.
And it works well.

So, @nurlansu, you may minify css now.
