### ISSUE TITLE
CSS variables declarations are wiped 

### ISSUE THREAD

**Issue by hs0ucy** [tdewolff/minify#130]
Hi,
I'm playing with [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) but **minify** erase the declaration pattern.

This:
```
:root {  
  --base-bg-color: #f1f1f1;
  --base-fg-color: #111111;
  --base-link-color: #0000ff;  
}
```
Became:
```
:root{}
```
Thanks for your help!

**Comment by tdewolff** [comment]
Please make sure you have updated github.com/tdewolff/parse

**Comment by hs0ucy** [comment]
@tdewolff It works! Thanks, have a nice weekend!
