### ISSUE TITLE
Why are you deleting conditional comments?

### ISSUE THREAD

**Issue by JoeArizona** [tdewolff/minify#133]
Hi, the minifier is now deleting conditional comments for IE. Conditional comments are **code**. Minifiers don't normally delete code. Why is this happening?

**Comment by mikegleasonjr** [comment]
see #96 

IE9 is the last browser supporting them and it has reached end of life (not officially supported anymore by Microsoft). Last IE browser supported by MS is IE11:
https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx

**Comment by tdewolff** [comment]
I agree with what @mikegleasonjr says. These minifiers are built to be spec compliant and are not intended to support old browser quirks. I guess you could circumvent this with a small piece of JS, but I'm sorry I won't reimplement this.

**Comment by tdewolff** [comment]
For anyone still looking for this: it has been implemented in the end due to popular demand. Enable the `KeepConditionalComments` option to keep conditional comments.
