### ISSUE TITLE
Allow to inline CSS stylesheets imported with @import rules

### ISSUE THREAD

**Issue by olegstepura** [tdewolff/minify#136]
Hi!

I'm using minify after `hugo` to create a static website. There is a bunch of CSS stylesheets to include in head (`bootstrap`, etc), and Google PageSpeed insights reports this has to be optimized. So I have an idea to create a single CSS file with a bunch of `@import` CSS rules pointing to all other CSS files nearby.  It's ok to run such file as is during development, but would be cool if minify would inline all those imported CSS files to the main CSS file.

Is this somehow possible to achieve with minify now or is it possible to be implemented?

Thanks!

**Comment by tdewolff** [comment]
These minifiers only minify all sources, it is out of the scope of this library to merge imports. The main problem is import resolution, i.e. finding the file that is referenced. Additionally I'd like to consider for example `background: url('background.jpg');` to be transformed into one with an embedded resources in the form of a data URI, depending on its size.

This is probably not going to happen in `minify`, but perhaps a helper library will merge and concatenate files akin to `webpack` for NodeJS.

**Comment by mikegleasonjr** [comment]
I know this issue is closed but I implemented this in one of my product. I will check if I can extract it and give it open source.
