### ISSUE TITLE
Issue with MinifyMimetype  text/html invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by goors** [tdewolff/minify#138]
Hi , this part of minify.html gives me error:

```
func (m *M) MinifyMimetype(mimetype []byte, w io.Writer, r io.Reader, params map[string]string) error {
	err := ErrNotExist
	if minifier, ok := m.literal[string(mimetype)]; ok { // string conversion is optimized away
		err = minifier.Minify(m, w, r, params)
	} else {
		for _, minifier := range m.pattern {
			if minifier.pattern.Match(mimetype) {
				err = minifier.Minify(m, w, r, params)
				break
			}
		}
	}
	return err
}
```
This `m.literal[string(mimetype)]` gives me `invalid memory address or nil pointer dereference` but when i log `string(mimetype)` i can see `text/html.` and i pass params as well to` charset=utf-8`.

I can not figure out from your code what this `m.literal[string(mimetype)]` part is doing.

**Comment by tdewolff** [comment]
Did you properly initiate `M` using https://github.com/tdewolff/minify/blob/master/minify.go#L68? Looks like `literal` has not been set.

**Comment by goors** [comment]
@tdewolff if i do `m := minify.New()` as you wrote in your docs, and `m` is "instance" of:

```
type M struct {
	literal map[string]Minifier
	pattern []patternMinifier

	URL *url.URL
}
```

not sure how to set literal.

**Comment by goors** [comment]
@tdewolff when i do `m := minify.New()` and then `log.println(m)` I got `&{map[] [] <nil>}` is this normal?

**Comment by goors** [comment]
@tdewolff yes that is normal. just tried to run https://github.com/tdewolff/minify#-custom-minifier and it works from command line. it  must be some issue with my code. closing, because i can see that this is not issue.
