### ISSUE TITLE
HTML parser strips out conditional comments

### ISSUE THREAD

**Issue by tiffanyAtDuke** [tdewolff/minify#139]
Checked in description here - https://github.com/tdewolff/minify#html:
"One of the minifications in HTML5 is: strip comments (except conditional comments)."

However, by testing in online tool and sample programs, it seems like the conditional comments are being stripped out as well. 

One example would be:
- Before Minification:
<img width="642" alt="screen shot 2017-05-05 at 1 16 09 pm" src="https://cloud.githubusercontent.com/assets/26337053/25762812/1c3308e4-3195-11e7-8993-8aaf80af84bb.png">

 - After Minification:
<img width="639" alt="screen shot 2017-05-05 at 1 16 13 pm" src="https://cloud.githubusercontent.com/assets/26337053/25762818/2407a48a-3195-11e7-91eb-3f211f0510e0.png">

**Comment by mikegleasonjr** [comment]
They have been removed, the documentation must be outdated. On my phone but look the closed issues, you will find one regarding this.

**Comment by tdewolff** [comment]
I've updated the readme to reflect that also conditional comments are removed. These constructs are a thing of the past, as even Microsoft doesn't support IE < 9 anymore

**Comment by mkadin** [comment]
Unfortunately, we're trying to use this library for the minification of emails, where conditional comments like these are very much still a thing.  The world of email clients is even more diverse than web clients - and they are far worse in terms of uniformity.

Are comments removed as a further minification?  Or was maintenance of the code related to comments difficult?

**Comment by RReverser** [comment]
@mkadin As far as I understand, that one is Outlook-specific and should be as well achievable with `mso-hide:all` CSS property?

**Comment by tdewolff** [comment]
I think pragmatism is more important than 100% spec compliance. We could possibly introduce an option to keep IE comments, as unfortunately old IE versions are still too common for end-users.

**Comment by mkadin** [comment]
@RReverser yeah - that's probably right in the case, but this is just one example of the craziness we have to deal with to support different email clients.  Our HTML is spattered with stuff like this to get spacing right and deal with other quirks.

```
<!--[if (gte mso 9)|(IE)]>
    <table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td>
<![endif]-->

...Some content goes here...

<!--[if (gte mso 9)|(IE)]>
            </td>
        </tr>
    </table>
<![endif]-->
```

+1 to @tdewolff for making this optional

**Comment by omeid** [comment]
Adding an option makes sense, but please keep it off by default.
