### ISSUE TITLE
CLI version number

### ISSUE THREAD

**Issue by client9** [tdewolff/minify#141]
Hello,

Really impressive work in this project.  thank you!

Unless I'm completely missing it, I could not see a way from the CLI to show the current version number.  Perhaps `--version` would be a nice addition.

Also.. equinox (interesting service BTW) is listing 2.1.1 while GH releases is 2.1.0

thanks!

n

**Comment by tdewolff** [comment]
The reason Equinox has a higher version is because the previous one didn't update properly. So `2.1.1` on Equinox is the same as `2.1.0` here on Github. I will see if I can fix this, because it is confusing.

As to the version number, what do you propose? Hard code the version? What about on the master branch, that is between the last version and the future new version...

**Comment by client9** [comment]
Hi @tdewolff 

The dumb, easy but more manual way is to  hard wire  the version number.  Release it.  Change the version to the next with "-dev" at the end, etc.   I think Hugo does something like this, but I'll have to lookl.

The other way is just setting the version number to "dev", and then passing in the version number of linker at release time.  Take a look at  https://blog.cloudflare.com/setting-go-variables-at-compile-time/

I'm not sure how you do releases, but happy to help here.

regards,

n

**Comment by client9** [comment]
hi @tdewolff  me again.. another question related to releases.  In February , the `--keep-end-tags` option was added, but yet, in the latest releases I don't see it or it doesn't work.  Not a problem, just trying understand how releases are done.

**Comment by tdewolff** [comment]
This is really really strange. All changes for `--keep-end-tags` are done on 25 and 26 February, however they are not in the release. I will make a new release on Equinox, but this will become 2.1.2, as each version has to be higher than the previous.

**Comment by tdewolff** [comment]
Well I had some troubles releasing a new version, so we're up to 2.1.5 now. I've updated the release description in this repository. The `--version` option will be included in a new version.

**Comment by client9** [comment]
thanks @tdewolff   must have been a merge problem or something, but the latest minify works great.
