### ISSUE TITLE
Minifying RGBA in CSS

### ISSUE THREAD

**Issue by 19kestier** [tdewolff/minify#143]
I like my things to be minified, but I don't link minify removing the background-color transparency of an element 
background-color: rgba(0,0,0,0.5); turns to background-color: #000
Which are not identical.

**Comment by tdewolff** [comment]
I've added a test, but minify works correctly in this case. It does not turn `rgba(0,0,0,0.5)` into hex as you state. What version did you use?

**Comment by 19kestier** [comment]
My bad, I was using https://github.com/hacdias/caddy-minify
It's README said that it used your library, so I thought maybe it was a bug in the library.
