### ISSUE TITLE
JS: nested templates bug

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#144]
JS minifier does not handle nested templates, test case:

```$(`#${a ? `apple ${orange} banana` : ''} .b`)```
must minify to
```$(`#${a?`apple ${orange} banana`:''} .b`)```

**Comment by RReverser** [comment]
This is already fixed in my PR and it has test cases.

**Comment by tdewolff** [comment]
PR is merged, so should be fixed.
