### ISSUE TITLE
Add & AddFunc producing different results

### ISSUE THREAD

**Issue by hacdias** [tdewolff/minify#145]
Hello!

I've got a question. Why are these two methods producing different results:

### Method 1

```go
mu := minify.New()
mu.AddFunc("text/css", css.Minify)
mu.AddFunc("text/html", html.Minify)
data, err = mu.Bytes(contentType, b.Bytes())
```

Output:

```
<!doctype html><style>.lr-border{border-left:1px solid rgba(86,61,124,.2);border-right:1px solid rgba(86,61,124,.2)}</style>
```

### Method 2

```go
mu := minify.New()
mu.Add("text/css", &css.Minifier{})
mu.Add("text/html", &html.Minifier{})
data, err = mu.Bytes(contentType, b.Bytes())
```

Output:

```
<!doctype html><style>.lr-border{border-left:1px solid transparent;border-right:1px solid transparent}</style>
```

I've been struggling with this. I'd prefer to use the second one so I can change the options, but I'm not getting the expected output with it.

**Edit:** Congrats!

![image](https://user-images.githubusercontent.com/5447088/28752477-85bedc04-7518-11e7-8d12-4677c08bbfa0.png)

**Comment by tdewolff** [comment]
Haha thanks! I just missed it the 1000... :-(

The reason why you get different output is because the zero initialisation of `css.Minifier` is not the default. Using `css.Minifier{ Decimals: -1 }` will give the expected results. I think I should add a global variable called `css.DefaultMinifier`.

**Comment by hacdias** [comment]
Thanks for the help. 😄 Yeah, probably a global with the default would be cool

**Comment by tdewolff** [comment]
I've added default minifiers: https://github.com/tdewolff/minify/commit/b6ab3cd0100936ee2de2074a0485b3be7922d7e2

**Comment by hacdias** [comment]
Thanks!
