### ISSUE TITLE
Does not support Accelerated Mobile Pages bastardized HTML5

### ISSUE THREAD

**Issue by raphaelcohn** [tdewolff/minify#147]
I love your tool; being able to download a well-written, statically-linked binary for the platforms I work with and just get stuff done has been amazing. It's been a breath of fresh air compared to npm, and keeps our development dependencies minimal. Combined with hugo, jq, and caddy, life's got a lot easier to script in the shell for us.

Sadly we've recently started to use AMP with it's bastardized HTML5, and, understandably, minify doesn't support them. It looks like changes to `table.go` might be necessary, but, given our limited working knowledge so far of AMP, I'd be reticent to make any recommendations.

Feel free to close with a "won't fix" if AMP isn't going to be something you'd want to support.

**Comment by tdewolff** [comment]
What exactly is the problem with `minify` that breaks AMP websites? I'm wondering if this can be fixed nonetheless or whether AMP doesn't follow the HTML5 spec. In the latter case this would be a "won't fix", for I intend to keep the library HTML5 spec compliant.

**Comment by raphaelcohn** [comment]
AMP introduces additional HTML elements, and embeds `application/ld+json` scripts in the head. minify seems to die part-way processing one of these scripts.

**Comment by tdewolff** [comment]
Do you have a example that makes minify die? It should be able to parse spec compliant JSON, unless `application/ld+json` is not spec compliant. You could try if it works if you don't attach the JSON minifier, see if that works. I'd still be interested in the reason why it is dieing though.

**Comment by raphaelcohn** [comment]
I did, and, I've currently lost it... I'll try to find one and put it in a gist.

**Comment by tdewolff** [comment]
Have you found the issue or fixed it somehow? I'd be interested to know!
