### ISSUE TITLE
Don't treat spellcheck as an html boolean attribute

### ISSUE THREAD

**Issue by escholtz** [tdewolff/minify#153]
It looks like the `spellcheck` attribute for input elements might be treated as a boolean attribute by minify. According to the [spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) it's an enumerated attribute, not boolean.

Here is a test case where the `="false"` is removed:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Title</title>
  </head>
  <body>
    <input type="text" spellcheck="false">
  </body>
</html>
```

Thanks for writing and sharing this great package!

**Comment by tdewolff** [comment]
Good catch, let me know if it is resolved now!

**Comment by escholtz** [comment]
Thanks! Resolved.
