### ISSUE TITLE
can  you  input  cmds from config file？

### ISSUE THREAD

**Issue by ghost** [tdewolff/minify#155]
thus，we  can  create a  config  file  in  the  root of project ，and  just  run  minify every  time  only，no  need to  input  from  console  again

**Comment by tdewolff** [comment]
I will think about it, but in the meantime it's quite easy to create a `.sh` (Linux) or `.bat` (Windows) file that executes the command with the same parameters every time.

**Comment by tdewolff** [comment]
I've aggregated this into #234
