### ISSUE TITLE
Binaries for the latest release

### ISSUE THREAD

**Issue by miltador** [tdewolff/minify#165]
Latest release which is `2.3.3`, at the moment of writing, doesn't have compiled binaries available for download. However previous releases have them in place.

**Comment by tdewolff** [comment]
That is because only the dependency scheme has changed, not the binary itself. The binary of 2.3.3 is equivalent to 2.3.1. None the less it would be better to release a new version to avoid confusion, I agree.

**Comment by tdewolff** [comment]
Fixed
