### ISSUE TITLE
NULL chars in HTML (intended) fails minification

### ISSUE THREAD

**Issue by kaushalmodi** [tdewolff/minify#166]
Hello,

I publish my coding notes to HTML using Hugo and then minify the HTML pages using your `minify` app.

Everything worked great, until a code block outputted a NULL character.. The HTML before minification shows up fine.. but trying to minify that breaks the site deployment because of this error:

```
minify 2.1.0-dev
ERROR: cannot minify public/notes/string-functions-nim-vs-python/index.html: unexpected null character
ERROR: Job failed: exit code 1
```

Can you allow minification to ignore NULL characters in HTML pages?

**Comment by tdewolff** [comment]
It was my understanding that NULL characters result in a parse error. Indeed they do, but usually the behavior should be to replace them by a 0xFFFD unicode replacement character. Since we don't really parse HTML in the sense that a browser does (we are just an intermediate stage that rewrites HTML), I think it should leave NULL characters in the source code.

Was this just a test or an actually used source? I wonder if there are any practical use cases with a NULL character.

**Comment by kaushalmodi** [comment]
> Was this just a test or an actually used source? 

I use Org (Emacs) to make notes about code snippets. The code snippets run within the document and the out gets auto-populated in a Results section below that code snippet.

The Nim code snippet [here][1] causes a NULL character to be output at the end of the first output line "1st char(0) to last, including \0(^0) : abc".

*In order to publish that page, I had to manually delete that NULL character. It would be a pain to do that every time as all the result blocks are auto-generated (which would auto-insert that NULL character).*

> I wonder if there are any practical use cases with a NULL character.

I also don't think there's a practical use.. but that character was auto-generated as I explained above.

[1]: https://scripter.co/notes/string-functions-nim-vs-python/#understanding-the-n-syntax

**Comment by tdewolff** [comment]
I pushed a commit that should fix this, I haven't tested it much myself. Please let me know if this works: fbe35477f08ee009b1af11bbf2094e4d318bc9c5 (update github.com/tdewolff/parse).

**Comment by kaushalmodi** [comment]
It now works! 👍 Thanks for fixing this quickly.

**Comment by kaushalmodi** [comment]
btw `minify --version` just outputs *minify version master*.. would be helpful if it printed the git hash used to build it.

**Comment by tdewolff** [comment]
The version string is automatically set if you use goreleaser, but otherwise I'm not sure if this can be set...it would be better to show the commit indeed!
