### ISSUE TITLE
ERROR: inferred mimetype text/xml of public/index.xml for concatenation unequal to previous mimetypes text/html

### ISSUE THREAD

**Issue by lpar** [tdewolff/minify#168]
Running `minify -r` on my Hugo site. The file in question is the Atom feed and starts with `<feed xmlns="http://www.w3.org/2005/Atom">`, and of course it's named `index.xml`, so it seems like this is a shortcoming in the code which infers MIME type.

**Comment by tdewolff** [comment]
Blank output means writing to stdout, which infers concatenation for multiple inputs. The real problem here is that the error is not accurated. It should check whether `--recursive` is provided and that `input` is not blank, since it makes no sense to run `minify` recursively on stdin.

**Comment by tdewolff** [comment]
Fixed in 5e54511d8a74a6b0b159323766512edfbf4a9090

**Comment by lpar** [comment]
Ah, that would explain why it worked on my Mac this morning, I got the command line right on my Mac. Yeah, in retrospect the error makes sense if you know what it's trying to do, it just shouldn't let you try to do that.
