### ISSUE TITLE
Parse error in CSS3 colours: HSLA

### ISSUE THREAD

**Issue by jinliming2** [tdewolff/minify#172]
HSLA colour needs 4 arguments, they are Hue, Saturation, Lightness and Alpha.
Saturation and Lightness need percentages.
I wrote `background: hsla(120, 0%, 100%, .5);` in my css file, and I got `background: hsla(120,0,100%,.5);` output. but this is wrong in Chrome, the second argument must be `0%`.

**Comment by tdewolff** [comment]
Let me get back to you in two weeks when I have better internet!

**Comment by tdewolff** [comment]
This was fixed https://github.com/tdewolff/minify/issues/84, are you sure you run the latest version? I cannot reproduce on master

**Comment by jinliming2** [comment]
I'm sure I upgraded to the latest version. And I still got the wrong output.
But I ran the test case `css/css_test.go`, it was all pass.
This is my css file:
```css
#common-m {
  background: hsla(0, 0%, 100%, .7);
}
```
I try to debug it, I found the code ran into this function:
https://github.com/tdewolff/minify/blob/master/css/css.go#L482-L499
The arguments are: `prop == 10`, `tt == 11`, `data == uint8[48, 37](0%)`
At line 486, got `n == 2`
At line 487, conditions set up, so `n--`, and `n == 1`
At line 492, `dim == uint8[37](%)`
At line 494, `data == uint8[48](0)`
At line 495, `tt == css.PercentageToken == 11`, but `len(data) == 1`, `data[0] == '0'`, `prop == 10, css.Color == 0x9305`, so the conditions are not set up.
At line 497, `tt == 11, css.DimensionToken == 12`, so the conditions are not set up.

At last, function return `tt(=11)` and `data(='0')`.

**Comment by jinliming2** [comment]
Test code:
```go
package main

import (
	"os"

	"github.com/tdewolff/minify"
	"github.com/tdewolff/minify/css"
)

func main() {
	m := minify.New()
	m.Add("text/css", &css.Minifier{
		Decimals: 2,
	})
	w := m.Writer("text/css", os.Stdout)
	w.Write([]byte(`#common-m {
  background: hsla(0, 0%, 100%, .7);
}`))
	w.Close()
}
```
Got this output:
```bash
#common-m{background:hsla(0,0,100%,.7)}
```

**Comment by tdewolff** [comment]
Thanks for the debug! The problem was that for `color` it was hardcoded that the `%` should not be dropped. The fix will keep `%` always (small minification regression that can be improved in the future) and also that only `<angle>` and `<length>` tokens will drop their dimension for zero values.
