### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by datajohnny** [tdewolff/minify#174]
Hi, does the library support whitelisting certain names to ignore minifying?

**Comment by tdewolff** [comment]
I think that's called blacklisting, but both blacklisting and whitelisting should be possible with the `--match` argument. You can pass a regex for which files to minify, and you could write a regex that matches if it is not part of a blacklist. Let me know if it works for you.

**Comment by datajohnny** [comment]
I meant ignoring certain minifications like for example a specific class name or tag name so that they still render with their full name, sorry for the confusion.

**Comment by tdewolff** [comment]
Do you mean with CSS or with HTML? I don't think class or tag names are minified themselves. Can you show me an example that doesn't work they way you expect?
