### ISSUE TITLE
`border-*: 0 none` is incorrectly transformed to `border-*: 0 0`

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#176]
```css
border-left: 0 none;
```

is transformed to

```css
border-left: 0 0;
```

which is invalid syntax and will cause entire `border-*` property to be ignored by the browser.

As far as I understand, it should transform to just `0` (or, if it's unsafe transformation, keep `0 none`).

**Comment by tdewolff** [comment]
I will need to do some refactoring first, in the CSS property value minification, for this and the other bug. I'll get back to it soon.

**Comment by RReverser** [comment]
Let me know if I can help, I didn't dig into CSS minifier as much as into JS one yet, but might try to.

**Comment by tdewolff** [comment]
Thanks for that! The refactor wasn't that big, I've implemented in the PR. It fixes both your issues and opens up the way for more rules in the future.

**Comment by tdewolff** [comment]
BTW, could you try the PR and let me know if there are any issues? Otherwise I'll go ahead and merge the PR.

**Comment by tdewolff** [comment]
Fixed by #177

**Comment by RReverser** [comment]
Sorry - haven't got time to try it out yet apart from test samples, will do a release next week.
