### ISSUE TITLE
JS: minify better; write a parser

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#18]
Write a JS parser to enable:
- Usage of ASI (automatic semicolon insertion) to reduce newlines and semicolons.
- Shorten variable names and function parameters when possible (ie. Closure Compiler simple mode; prohibit `eval` and `toString`), see https://ariya.io/2011/08/javascript-minifier-and-variable-renaming
- Correct for https://github.com/twbs/bootstrap/issues/3057

~~Still keep the current fast JSMin-inspired version?~~

~~It would be awesome if you'd consider donating through [Patreon](https://www.patreon.com/tdewolff) or [PayPal](https://www.paypal.me/tdewolff) so that I can free up time to implement a much improved JS minifier.~~ I don't think FOSS will ever earn me even a coffee haha!

**Comment by einthusan** [comment]
will be donating :)

**Comment by tdewolff** [comment]
@einthusan Thanks for considering! Very much appreciated ;-)

**Comment by phamdt** [comment]
how much do you need?

**Comment by tdewolff** [comment]
@phamdt It's a big undertaking that will cost a lot of time, given that I work freelance I'd say freelancer prices apply. However, I've created https://www.patreon.com/tdewolff and https://www.paypal.me/tdewolff, any amount is appreciated!

**Comment by tdewolff** [comment]
Usage of external minifiers is explained here: https://github.com/tdewolff/minify#external-minifiers if improved JS minification is required.

`minify` is still expected to improve its JS minifier at some point in the future.
