### ISSUE TITLE
Make possible to use gopkg.in/tdewolff/minify.v2

### ISSUE THREAD

**Issue by jeevatkm** [tdewolff/minify#189]
Could you please remove `package minify // import "github.com/tdewolff/minify"` from [minify.go](https://github.com/tdewolff/minify/blob/master/minify.go#L2)?

Error
```
$ go get -u gopkg.in/tdewolff/minify.v2
package gopkg.in/tdewolff/minify.v2: code in directory $GOPATH/src/gopkg.in/tdewolff/minify.v2 expects import "github.com/tdewolff/minify"
```

Library would be accessible via -
* `github.com/tdewolff/minify`
* `gopkg.in/tdewolff/minify.v2`

**Comment by tdewolff** [comment]
This package is not supposed to be used through `gopkg.in`, please use `github.com/tdewolff/minify`. It will use the latest version automatically. For what do you need to use `gopkg.in`?

**Comment by jeevatkm** [comment]
@tdewolff Sorry for late response. I'm the author of [aah framework](https://aahframework.org). I'm thinking to integrate your library for minify purpose for the framework users. I was hoping to get tagged version without using package management tools.

**Comment by tdewolff** [comment]
I think the advised approach is to vendor it, is this a possibility for you?

**Comment by jeevatkm** [comment]
Yes, I have plans for the next release. Thank you.

**Comment by abhishek-dbcloudops** [comment]
ggh
