### ISSUE TITLE
HTML minify is breaking SVG images

### ISSUE THREAD

**Issue by bfrancojr** [tdewolff/minify#19]
Minify is transforming sibling PATH tags in parent/child of each other. For example:

&lt;path id="x" d="M60.91,81.762 ..."&gt;&lt;/path&gt;
&lt;path id="y" d="M113.695,72.72 ..."&gt;&lt;/path&gt;

Become:

&lt;path id="x" d="M60.91,81.762 ..."&gt;
&lt;path id="y" d="M113.695,72.72 ..."&gt;

Which is wrong. PATH tags are block tags.

I've tried to patch the code by adding the PATH tag to the html/table.go blockTagMap var but no luck, the end result was the same.

Thanks!

**Comment by tdewolff** [comment]
It hasn't got to do with being a block tag, whether it is block relates to CSS and how it's displayed.

The problem is that SVG is an XML file format and not an HTML format. You can't use XML files to be minified by the HTML minifier, because there are a number of subtle differences. In the future I will build an XML minifier too.

However, can you send me a more complete example? I cannot reproduce.

**Comment by tdewolff** [comment]
Can you comment?

**Comment by bfrancojr** [comment]
Hi,

You can use the following HTML to see what is going on:

<html>
<link rel="stylesheet" type="text/css" href="http://statics.revision3.com/ui/r3/compressed/css/homepage-1429120872587.css" media="all"/>
<body>
<nav class="Navigation">
    <h1 class="logo">
        <a href="http://revision3.com/" rel="Revision3">
            <svg class="svg" viewBox="-20 0 626 33" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <g id="type" transform="translate(124, -14)" fill="#fff">
                    <path id="letterR"
                          d="M60.91,81.762 L38.749,50.918 C47.398,46.36 53.308,37.276 53.308,26.837 C53.308,11.839 41.11,-0.363 26.107,-0.363 C22.056,-0.361 -0.496,-0.366 -0.496,-0.366 L-0.496,81.762 L14.762,81.762 L14.762,54.036 L22.198,54.036 L42.118,81.762 L60.91,81.762 L60.91,81.762 Z M26.113,38.776 L14.762,38.776 L14.762,14.897 C19.086,14.901 24.032,14.899 26.113,14.896 C32.693,14.896 38.048,20.254 38.048,26.837 C38.048,33.419 32.693,38.776 26.113,38.776 L26.113,38.776 Z"/>
                    <path id="letterE"
                          d="M113.695,72.72 C108.177,79.296 99.137,82.934 90.333,82.934 C73.311,82.934 60.514,71.194 60.514,53.349 C60.514,37.5 71.314,23.646 88.22,23.646 C103.95,23.646 115.105,36.913 115.105,52.763 C115.105,54.288 114.986,55.814 114.752,57.106 L75.306,57.106 C76.128,65.09 82.586,70.607 90.686,70.607 C97.143,70.607 102.308,66.967 105.009,64.033 L113.695,72.72 L113.695,72.72 Z M99.49,45.953 C99.022,40.904 94.441,35.975 88.22,35.975 C81.88,35.975 76.715,40.788 76.011,45.953 L99.49,45.953 L99.49,45.953 Z"/>
                    <path id="letterV"
                          d="M147.175,59.571 L162.791,24.821 L178.638,24.821 L152.458,81.762 L141.893,81.762 L115.711,24.821 L131.56,24.821 L147.175,59.571"/>
                </g>
            </svg>
        </a>
    </h1>
</nav>
</body>
</html>

Minifying it will generate this:

<link rel=stylesheet href=http://statics.revision3.com/ui/r3/compressed/css/homepage-1429120872587.css media=all><nav class=Navigation><h1 class=logo><a href=//revision3.com/ rel=revision3><svg class=svg viewbox="-20 0 626 33" version=1.1 xmlns=//www.w3.org/2000/svg><g id=type transform="translate(124, -14)" fill=#fff>
                    <path id=letterR d="M60.91,81.762 L38.749,50.918 C47.398,46.36 53.308,37.276 53.308,26.837 C53.308,11.839 41.11,-0.363 26.107,-0.363 C22.056,-0.361 -0.496,-0.366 -0.496,-0.366 L-0.496,81.762 L14.762,81.762 L14.762,54.036 L22.198,54.036 L42.118,81.762 L60.91,81.762 L60.91,81.762 Z M26.113,38.776 L14.762,38.776 L14.762,14.897 C19.086,14.901 24.032,14.899 26.113,14.896 C32.693,14.896 38.048,20.254 38.048,26.837 C38.048,33.419 32.693,38.776 26.113,38.776 L26.113,38.776 Z">
                    <path id=letterE d="M113.695,72.72 C108.177,79.296 99.137,82.934 90.333,82.934 C73.311,82.934 60.514,71.194 60.514,53.349 C60.514,37.5 71.314,23.646 88.22,23.646 C103.95,23.646 115.105,36.913 115.105,52.763 C115.105,54.288 114.986,55.814 114.752,57.106 L75.306,57.106 C76.128,65.09 82.586,70.607 90.686,70.607 C97.143,70.607 102.308,66.967 105.009,64.033 L113.695,72.72 L113.695,72.72 Z M99.49,45.953 C99.022,40.904 94.441,35.975 88.22,35.975 C81.88,35.975 76.715,40.788 76.011,45.953 L99.49,45.953 L99.49,45.953 Z">
                    <path id=letterV d="M147.175,59.571 L162.791,24.821 L178.638,24.821 L152.458,81.762 L141.893,81.762 L115.711,24.821 L131.56,24.821 L147.175,59.571">
                </g></svg></a></h1></nav>

If you pay attention to path tag, there are not close tag for them.

Thanks!

**Comment by tdewolff** [comment]
Relevant specs page: http://dev.w3.org/SVG/proposals/svg-html/svg-html-proposal.html

**Comment by tdewolff** [comment]
The HTML minifier will now call an `image/svg+xml` minifier for the contents of the SVG tag. This minifier has not yet been implemented by me, but will be in the future.

**Comment by bfrancojr** [comment]
Thanks a lot!

On Sat, Apr 25, 2015 at 2:47 PM, Taco de Wolff <notifications@github.com>
wrote:

> The HTML minifier will now call an image/svg+xml minifier for the
> contents of the SVG tag. This minifier has not yet been implemented by me,
> but will be in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdewolff/minify/issues/19#issuecomment-96283875>.
>



-- 
Bene.

**Comment by tdewolff** [comment]
FYI, I've just pushed an early version of an XML minifier. It will probably work for SVG images!
