### ISSUE TITLE
Exponential numbers are part of CSS3

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#193]
We've noticed CSS minifier compressing properties like `left: -10000px;` to `left: -1e4px;`. While this is allowed in CSS3, some older browsers might not understand exponential syntax as it wasn't part of CSS2, and will skip such property altogether, causing incorrect output.

What would be the best way to disable this feature? I see there is `Decimals` option in the CSS minifier, but I wonder if it should be just set to maximum integer value or maybe it's worth providing separate option to disable exponential format or maybe it's worth disabling it altogether and just preserve original number string by default? (I assume it usually doesn't really save much, as in most cases you won't have many trailing zeroes in normal CSS, and even if you do, it's just ~1-2 bytes difference even in ungzipped version)

**Comment by tdewolff** [comment]
Sorry to answer this late, have been very busy.

The CSS minifier is based on the CSS3 specification, so providing CSS2 would not be appropriate. I do agree this is a minor minification technique that could be commented out for the purpose of supporting old browsers, but I wonder if there are other difference between CSS2 and CSS3 that will bother you. In the end I prefer not to support the full CSS2 spec alongside CSS3 though.

**Comment by RReverser** [comment]
In general it's not CSS3 support that bothers me, it's breakages that happen when minifying valid CSS2 to CSS3. I assume most people don't expect this to happen, and expect code that was valid on certain platforms, to be still valid on same platforms after minification.

Another example of this could be minifying ES5 to ES6 - while, with scope analysis, it's technically possible to minify some function expressions to ES6 arrow functions, it's not something that most would expect to happen by default.

Either way, given that Web specs are purely additive, I imagine it shouldn't be too hard to keep such "version upgrades" under some option flags rather than have them happen inevitably w/o any control.

**Comment by tdewolff** [comment]
I mean that the input must be CSS3 for the minifier to work correctly, as it assumes CSS3 input and gives you valid CSS3 output for that. It happens to parse CSS2 since it is indeed an additive upgrade towards CSS3.

What browser does not support scientific notation? https://developer.mozilla.org/en-US/docs/Web/CSS/number says all of them do (though not clear about Opera and Safari). I'm not sure I want to support old browsers or old spec versions, as that opens a large can of worms. There are many subtle differences between CSS2 and CSS3, so if this issue is giving problems I am fairly confident there are a couple of other issues too.

**Comment by tdewolff** [comment]
I'm going to close this, as `minify` will not support CSS2. Please re-open if you want to discuss it further.

**Comment by RReverser** [comment]
The main issue is definitely old versions of Safari (older iOS), but I suspect older versions of other browsers might be affected as well. It shouldn't cost too much to add an option to preserve original formatting of CSS where otherwise it would require upgrading to a newer browser, but if you feel strong about it, I guess I can add it and maintain in a separate fork. It just seemed reasonable to preserve them, especially in the light of minifiers supporting (as in "preserving") even IE-specific quirks.
