### ISSUE TITLE
not removing css comments

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/minify#208]
I am running `minify -v -r -o minified/ public` on

```
/*! minireset.css v0.0.3 | MIT License | github.com/jgthms/minireset.css */
html,
body,
...
```

while the CSS does get minified the comment is kept:

```
/*!minireset.css v0.0.3 | MIT License | github.com/jgthms/minireset.css*/html,body,p...
```

Bug?

**Comment by tdewolff** [comment]
This was implemented later on as a request by users. The `/*!   ...    */` pattern is widely used for licensing display and usually can't legally be removed. So it is a feature and not a bug ;-)

**Comment by tcurdt** [comment]
Urgh - OK. Thanks!

**Comment by tdewolff** [comment]
I guess this could be added as an option.

**Comment by tcurdt** [comment]
At the same time that would make it more obvious in terms of documentation. One could also just remove the `!` before the minification. Of course that'd be not quite as elegant.

**Comment by tdewolff** [comment]
@RReverser Do you have an opinion on this? We could add an option called `KeepBangComments` that will keep in comments that start with an exclamation mark. This is already default behaviour, but might be desirable to make optional? The cost is that we're adding another option to the minifier(s)...

I can also see the point of leaving it as it is. Licensing comments cannot usually be removed and it's better to keep the number of options down.

**Comment by RReverser** [comment]
@tdewolff Personally I think allowing to remove licensing comments might be a slippery slope since, as you said yourself, this is usually illegal change, and developers might not understand importance of it if given an option.

**Comment by tdewolff** [comment]
@RReverser Good point, I agree.

**Comment by tcurdt** [comment]
But could we update the docs?

> remove comments and unnecessary whitespace

IMO it should be mentioned there.

**Comment by tdewolff** [comment]
Done 84a56e44b8cc9db981a83f74a2db2e4d05bbf508
