### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by MichaelMonashev** [tdewolff/minify#213]
# github.com/tdewolff/minify/css
..\github.com\tdewolff\minify\css\css.go:423:14: undefined: css.Xx_Small
..\github.com\tdewolff\minify\css\css.go:423:35: undefined: css.X_Small
..\github.com\tdewolff\minify\css\css.go:423:55: undefined: css.Small
..\github.com\tdewolff\minify\css\css.go:423:73: undefined: css.Medium
..\github.com\tdewolff\minify\css\css.go:423:92: undefined: css.Large
..\github.com\tdewolff\minify\css\css.go:423:110: undefined: css.X_Large
..\github.com\tdewolff\minify\css\css.go:423:130: undefined: css.Xx_Large
..\github.com\tdewolff\minify\css\css.go:423:151: undefined: css.Smaller
..\github.com\tdewolff\minify\css\css.go:423:171: undefined: css.Larger
..\github.com\tdewolff\minify\css\css.go:423:230: undefined: css.Unset
..\github.com\tdewolff\minify\css\css.go:423:230: too many errors

**Comment by kaushalmodi** [comment]
I am getting the same errors when running `go build -v` from minify/cmd/minify. Why was this issue closed? How did you fix this?

Thanks.

**Comment by kaushalmodi** [comment]
OK, I fixed this error by manually updating tdewolff/buffer, tdewolff/parse and tdewolff/strconv in go.apps/src. Then `go build -v` ran fine.

For future, what's the canonical way to run `go build` so that it auto updates the dependencies too?

**Comment by MichaelMonashev** [comment]
I used different versions of github.com/tdewolff/minify and github.com/tdewolff/parse

**Comment by MichaelMonashev** [comment]
go get -u github.com/tdewolff/minify fix my problem.

**Comment by tdewolff** [comment]
@kaushalmodi You need to update `parse`. Either you keep both on `master` and update them, or you pick a version for each and use that. The command Michael posted should fix it.
