### ISSUE TITLE
BUG: Line Feeds generated

### ISSUE THREAD

**Issue by PLG** [tdewolff/minify#216]
With a HTML/CSS minify, whitespace gets generated after the ``{{.Values}}&nbsp;`` field (before the ``</th>`` tag. I detected a total of 4 Line Feeds being generated. Usually not a problem for HTML, but I use a ``white-space: pre;`` style, which make the Line Feeds throw off the layout.

    {{range .}}
	{{if eq .RadNr 1}}<thead>{{end}}
	<tr id="RadNr{{.RadNr}}">
	{{if le .RadNr 5}}
	<th>{{.AgensKod}}</th><th id="analysnamn">{{.AnalysNamn}}</th><th>{{.Values}}&nbsp;</th>	
	{{else}}
	<td>{{.AgensKod}}</td><td id="analysnamn">{{.AnalysNamn}}</td><td>{{.Values}}&nbsp;</td>
	{{end}}
	</tr>
	{{if eq .RadNr 5}}<tbody>{{end}}
    {{end}}

**Comment by tdewolff** [comment]
I don't think it generates new lines, instead it keeps some of the original new lines (and removes others). You could try using the `KeepWhitespace` option or by using a `pre` tag around it. Otherwise, explicitly replace spaces by `&nbsp;`.

**Comment by PLG** [comment]
There are no newlines between those two fields and I tried removing the newlines around it; it didn't help. I got a total of four newlines. It was clearly visible in hex code. ``&nbsp;\x0a\x0a\x0a\x0a</th>.`` Apparently, you missed it in my previous message. I use ``pre`` for white-space causing the newlines to mess up my table.

**Comment by tdewolff** [comment]
The example you posted has newlines in it, some of them are kept, some not. If you try:
```
{{range .}}{{if eq .RadNr 1}}<thead>{{end}}<tr id="RadNr{{.RadNr}}">{{if le .RadNr 5}}<th>{{.AgensKod}}</th><th id="analysnamn">{{.AnalysNamn}}</th><th>{{.Values}}&nbsp;</th>{{else}}<td>{{.AgensKod}}</td><td id="analysnamn">{{.AnalysNamn}}</td><td>{{.Values}}&nbsp;</td>{{end}}</tr>{{if eq .RadNr 5}}<tbody>{{end}}{{end}}
```
it is minified to
```
{{range .}}{{if eq .RadNr 1}}<thead>{{end}}<tr id=RadNr{{.RadNr}}>{{if le .RadNr 5}}<th>{{.AgensKod}}<th id=analysnamn>{{.AnalysNamn}}<th>{{.Values}}&nbsp;{{else}}<td>{{.AgensKod}}<td id=analysnamn>{{.AnalysNamn}}<td>{{.Values}}&nbsp;{{end}}{{if eq .RadNr 5}}<tbody>{{end}}{{end}}
```

The minifier does not insert newlines, so I'm not sure how this is affecting you, but try the stuff I mentioned.

**Comment by PLG** [comment]
your EDIT... Glad you see it! =)))

**Comment by tdewolff** [comment]
Alright, the problem is that the HTML specification disallows text between `th` and `td` tags, but clearly you have text (namely `{{end}}`) in between them. HTML templates are not valid HTML and cannot be parsed by this minifier (though often they are minified fine, this is coincidence). I'm sorry but this will not likely be fixed. There should come a separate HTML template minifier instead. I advice you not to use the minifier on templates, unless you avoid this problem...

**Comment by PLG** [comment]
Thank you for looking into the problem! I have disabled minifier for now, since I can only minify the templates and not the result (due to the fact that the text is preformated <pre/>).
