### ISSUE TITLE
HTML5: whitespace when using <div> inside <a>

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#224]
Casus:
```
<a>
	<div>text</div>
	<div>text</div>
</a>
```

Normally, whitespace between `<div>` elements are removed, but what if the parent is a flow-element? Should we cascade-down that fact and keep whitespace between nested elements?

https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element

**Comment by yudyananda** [comment]
I totaly agree with you that we should not rely on the white space between elements, This is a lesson for me to not rely on the white space but sometimes it lead to some problem on styling (CSS)

for example   [when we have with width in percent](https://discourse.gohugo.io/t/hugo-minify-strips-out-p-tags/13813/14?u=yudy_ananda) we have to anticipate the appereance before the minification which is barely hard to find out the result 

I personaly dont have any issue with the whitespace removing, but it would be great if we have an option to remove or not the whitespace on minifiy

Thank you for checking my issue in Hugo Forum 👍 

Regards

Yudy

**Comment by tdewolff** [comment]
@yudyananda There is actually an option `KeepWhitespace` that will keep one space to preserve spacing. I don't think Hugo supports setting these options yet, but you can look into that as well! Thanks for the added information.

I think the way whitespace removal works right now will stay as it is (as I'm pretty confident it works well), but I wanted to check this specific case more thoroughly. From HTML4 it was forbidden to put <div> in <a>, but HTML5 seems to allow it. I need to delve into the specs and see if some assumptions that were made might be off...

**Comment by tdewolff** [comment]
Testing this in Chrome, the following results in no visible spaces: `abc<i> <div> efg </div> </i>hij` and is thus effectively the same as `abc<i><div>efg</div></i>hij`. Therefore I don't think this is a legitimate issue, and falls under the case where CSS changes the `display` property, which we can't anticipate for in HTML and should thus be fixed by the `KeepWhitespace` option.
