### ISSUE TITLE
cache busting

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/minify#225]
Given the name "minify" I fear it might be out of scope, still I wish there was an option to support cache busting of resources. https://www.keycdn.com/support/what-is-cache-busting/

**Comment by tdewolff** [comment]
This is indeed out of scope. This package will only transform text and has nothing to do with caches or filenames. I suggest bringing this up with whatever other package that uses this minifier, as the caller will be naming the file or determining the URL to enable cache busting.
