### ISSUE TITLE
Equivalent of htmlmin:ignore

### ISSUE THREAD

**Issue by jiridj** [tdewolff/minify#228]
Hi, 

For my static site with Hugo I was using [html-minifier](https://github.com/kangax/html-minifier). Now that minification is built into Hugo with this library, I want to switch. It will make my build process a lot simpler. There is one particular feature that I use that I couldn't find an equivalent of in this library. 

I rely on whitespace not being stripped in a particular div of my html files. Those divs are styled with a monospace font to create the impression of a fixed-width character terminal. You can see an example here: [Sick and tired of terminal screenshots](https://jiridj.be/posts/macos-terminal-in-css/). The terminal now renders without all additional whitespaces so it looks off. 

With html-minifier I could specify two comment tags `<!-- htmlmin:ignore -->` and any content between the tags would be left alone. Is there an equivalent, or alternative method with minify that will yield me the same result?

Thanks!

**Comment by jiridj** [comment]
I forgot to use the obvious solution: &nbsp; Must have been a lack of coffee! (－‸ლ)

Did a string replace on my output, replacing spaces by non-breaking spaces. Works like a charm.

**Comment by tdewolff** [comment]
Sorry to respond this late, but you need to put your terminal in `<pre>` tags in this case. That'll keep all whitespaces.
