### ISSUE TITLE
minify --svg-decimals=3 adds artifacts to a certain .svg file

### ISSUE THREAD

**Issue by shlomif** [tdewolff/minify#230]
When running the latest minify against this svg - https://github.com/shlomif/vim-begin/blob/master/vim-begin/vim-begin-logo/Vim-begin-logo.svg - I am getting this - https://vim.begin-site.org/images/vim-begin.min.svg with an artefact added - as displayed by all of FF, chromium-browser and gwenview. Please look into fixing it and thanks for a great program.

**Comment by tdewolff** [comment]
Thanks for the bug report! Should be fixed now.

**Comment by shlomif** [comment]
On Thu, 25 Oct 2018 17:33:43 -0700
Taco de Wolff <notifications@github.com> wrote:

> Thanks for the bug report! Should be fixed now.
> 

Thanks! Let me try.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

He has a high degree of idealism, a high degree of stubbornness, and an even
higher degree of inability to distiniguish between the two.
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
On Thu, 25 Oct 2018 17:33:43 -0700
Taco de Wolff <notifications@github.com> wrote:

> Thanks for the bug report! Should be fixed now.
> 

Seems to work nicely now - thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Parody of "The Fountainhead" - http://shlom.in/towtf

Judaism: God knows you will do shit, does nothing to prevent it, but makes you
take the blame for it anyways.
    — http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
