### ISSUE TITLE
2.3.6 seems incomplete

### ISSUE THREAD

**Issue by bep** [tdewolff/minify#231]
I tried to pull in the latest Minify into Hugo, but it failed, assume there are some dependencies out of synch

https://github.com/gohugoio/hugo/commit/286d0b7dc3aa6e118eb7d5f19900377ae55ab41c

```bash
exec: go test ./... -tags extended
# github.com/tdewolff/minify/css
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:14: undefined: css.Xx_Small
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:35: undefined: css.X_Small
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:55: undefined: css.Small
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:73: undefined: css.Medium
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:92: undefined: css.Large
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:110: undefined: css.X_Large
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:130: undefined: css.Xx_Large
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:151: undefined: css.Smaller
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:171: undefined: css.Larger
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:230: undefined: css.Unset
../../gopath/pkg/mod/github.com/tdewolff/minify@v2.3.6+incompatible/css/css.go:424:230: too many errors
```

Not sure if it's related, but it would probably also be cool if you could add a `go.mod` file to this project. Go Modules actually works really great.

**Comment by tdewolff** [comment]
Yes, I'm working on the Go modules support, thanks for raising this as a priority. In the meanwhile please update the `parse` library and you should be fine.

**Comment by bep** [comment]
For other people using Go Modules. I needed a "replace" statement to get it to pick the correct parse package:

https://github.com/gohugoio/hugo/commit/aa281b5135db2e84b9e21b5f38a6cb63cf3ab158

**Comment by tdewolff** [comment]
I just gave it a go but there doesn't seem to be a good solution that:
- keeps the major version at v2
- does not change the import paths (ie. keep at `github.com/tdewolff/minify`)

So I'm quite unsure how to proceed from here, would you have an idea?

**Comment by bep** [comment]
>So I'm quite unsure how to proceed from here, would you have an idea?

No, the v2 area is a little but murky to me. On one hand it is one thing I really like and need with Go Modules, but on the other hand -- I can see how it creates some gray hairs for existing modules that has gone passed the v1 mark.

**Comment by tdewolff** [comment]
This should be fixed now when you use the `github.com/tdewolff/minify/v2 import path!
