### ISSUE TITLE
minify --svg-decimals 3 messes up https://commons.wikimedia.org/wiki/File:Fedora_logo_and_wordmark.svg

### ISSUE THREAD

**Issue by shlomif** [tdewolff/minify#233]
After running `minify --svg-decimals 3 -o dest-prod/images/fedora-logo.min.svg dest-prod/images/fedora-logo.svg` with https://commons.wikimedia.org/wiki/File:Fedora_logo_and_wordmark.svg as the input I am getting [this](https://fc-solve.shlomifish.org/images/fedora-logo.min.svg) which looks mutilated in FF, gwenview and inkscape.

**Comment by tdewolff** [comment]
This commit should've fixed it: https://github.com/tdewolff/minify/commit/c86dd764169e70ab04e3b0d5fd5e478657a6c83d

What version of `minify` are you running (I thought you were on the latest?), latest `minify` seems to give a good result for me!

**Comment by shlomif** [comment]
On Thu, 08 Nov 2018 11:44:51 -0800
Taco de Wolff <notifications@github.com> wrote:

> This commit should've fixed it:
> https://github.com/tdewolff/minify/commit/c86dd764169e70ab04e3b0d5fd5e478657a6c83d
> 

Thanks, I shall try.

> What version of `minify` are you running (I thought you were on the latest?),
> latest `minify` seems to give a good result for me!
> 

```
shlomif[fcs]:$trunk/fc-solve/site/wml$ which minify
/home/shlomif/apps/golang/bin/minify
shlomif[fcs]:$trunk/fc-solve/site/wml$ minify --version
minify version master
shlomif[fcs]:$trunk/fc-solve/site/wml$ ls -l `which minify`
-rwxr-xr-x 1 shlomif shlomif 7365263 Nov  8
17:59 /home/shlomif/apps/golang/bin/minify
shlomif[fcs]:$trunk/fc-solve/site/wml$                     

```

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://ccmixter.org/files/destinazione_altrove/49997 - “Paint The Sky”

Do not meddle in the affairs of Dragons, for you are crunchy and taste good
with ketchup.                                       — Unknown source.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi,

On Thu, 08 Nov 2018 11:44:51 -0800
Taco de Wolff <notifications@github.com> wrote:

> This commit should've fixed it:
> https://github.com/tdewolff/minify/commit/c86dd764169e70ab04e3b0d5fd5e478657a6c83d
> 
> What version of `minify` are you running (I thought you were on the latest?),
> latest `minify` seems to give a good result for me!
> 

tried again:

shlomif[fcs]:$trunk/fc-solve/site/wml$ go get -u
github.com/tdewolff/minify/cmd/minify
shlomif[fcs]:$trunk/fc-solve/site/wml$ ls
-l `which minify` -rwxr-xr-x 1 shlomif shlomif 7365263 Nov  9
10:26 /home/shlomif/apps/golang/bin/minify
shlomif[fcs]:$trunk/fc-solve/site/wml$ date Fri  9 Nov 10:26:13 IST 2018
shlomif[fcs]:$trunk/fc-solve/site/wml$ minify --version
minify version master
shlomif[fcs]:$trunk/fc-solve/site/wml$ minify --svg-decimals 3 -o
dest-prod/images/fedora-logo.min.svg dest-prod/images/fedora-logo.svg
shlomif[fcs]:$trunk/fc-solve/site/wml$ gwenview dest/images/fedora-logo.min.svg
shlomif[fcs]:$trunk/fc-solve/site/wml$ 

The bug still happens! Is there a caching problem?
https://www.martinfowler.com/bliki/TwoHardThings.html .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Faith: Becky… you have a lot of potential. You’re more than a pretty face.
Becky: Heh, I knew that I have potential, but do you really think I have
a pretty face?
    — http://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Note that the input image can be found here - https://fc-solve.shlomifish.org/images/fedora-logo.svg - I am on Mageia Linux x86-64 v7 and also tried it with the executable after `go build` in the git clone - and got the same problem.

**Comment by tdewolff** [comment]
Are you sure `go get -u` is getting the latest version? With Go modules this doesn't seem to be the case...

Either use git to get the latest, or try the binary here: https://github.com/tdewolff/minify/releases/tag/v2.3.6 Let me know if it persists!

**Comment by shlomif** [comment]
@tdewolff : with this the problem still happens:

```
shlomif[fcs]:$trunk/fc-solve/site/wml$ git clone https://github.com/tdewolff/minify
Cloning into 'minify'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 4929 (delta 68), reused 83 (delta 38), pack-reused 4791
Receiving objects: 100% (4929/4929), 3.16 MiB | 2.72 MiB/s, done.
Resolving deltas: 100% (2942/2942), done.
shlomif[fcs]:$trunk/fc-solve/site/wml$ cd minify/cmd/minify 
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ go build
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ ls
main.go  minify_bash_tab_completion  util.go       watch.go
minify   README.md                   util_test.go
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ go mod edit
go mod edit: no flags specified (see 'go help mod edit').
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ ./minify --svg-decimals 3 -o f.svg ../../../src/images/fedora-logo.svg
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ gwenview f.svg 
shlomif[fcs]:$trunk/fc-solve/site/wml/minify/cmd/minify$ 
```

**Comment by tdewolff** [comment]
@shlomif Ah my fault, I can reproduce and I get the same problem. Let me work on a fix.

**Comment by shlomif** [comment]
@tdewolff : thanks for the update and for working on it.

**Comment by shlomif** [comment]
Thanks! The problem appears to be fixed now.
