### ISSUE TITLE
Minifier outputs invalid Hex codes for rgba and transparent values

### ISSUE THREAD

**Issue by bep** [tdewolff/minify#238]
This a re-opening of #5506

>This issue came up in the Hugo Forum a few days ago and today I also came across this behavior myself:

>It seems that for any rgba value e.g. rgba(000, 000, 000, 0.7); and also if a color value is set to transparent @tdewolff 's minifier outputs invalid hexadecimal numbers that fail W3C validation.

>ref: https://discourse.gohugo.io/t/bug-minify-outputs-invalid-hex-codes-for-rgba-and-transparent-values/15609

>I am opening this issue because this is something that looks like a proper bug but please note that currently my time is very limited and I cannot investigate further myself.

To add my own words:

The default minifier should produce **correct result**.

**Comment by tdewolff** [comment]
The results are correct, as per https://www.w3.org/TR/css-color-4/#hex-notation, it just seems that https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Browser_compatibility has not yet implemented it. I might have been a little early in adopting this new syntax.

**Comment by tdewolff** [comment]
I suggest you turn on the `KeepCSS2` flag for now, I need to decide whether we keep the new color module in or leave it out.

**Comment by bep** [comment]
>The results are correct

From a minifier's standpoint, the results are not correct. I would expect a minifier, in its default settings, to work on the conservative side.

>I suggest you turn on the KeepCSS2 

I will, but please consider my comment above.
