### ISSUE TITLE
Bing webmaster verification fails with minified HTML output

### ISSUE THREAD

**Issue by Jos512** [tdewolff/minify#242]
I know that the minified HTML that this library makes is *technically* correct. Unfortunately, Bing isn't as strict with what is still valid HTML.

For site verification purposes, Bing [expects](https://www.bing.com/webmaster/help/how-to-verify-ownership-of-your-site-afcfefc6) something like:

~~~html
<head>
    <meta name="msvalidate.01" content="randomstring" />
</head>
~~~

Minify makes it into:

~~~html
<head><meta name=msvalidate.01 content=randomstring></head>
~~~

Which is unfortunately not something that Bing picks up.

(I use minify with Hugo, if that's relevant.)

**Comment by tdewolff** [comment]
I will investigate if it is possible to add a new flag to keep quotes around attribute values, and see if that solves the issue.

**Comment by tdewolff** [comment]
This is similar to #236, I'll track progress there.
