### ISSUE TITLE
minify --svg-decimals 3 yields an unusable .svg for https://openclipart.org/detail/307527/a-mushroom

### ISSUE THREAD

**Issue by shlomif** [tdewolff/minify#245]
Hi!

If I run `minify --svg-decimals 3 -o dest/post-incs/t2/humour/images/1538381903--mushroom.min.svg dest/post-incs/t2/humour/images/1538381903--mushroom.svg` with https://www.shlomifish.org/humour/images/1538381903--mushroom.svg (taken from https://openclipart.org/detail/307527/a-mushroom under PD - sha256 is 39e6675a1c717e642c2d98364a75ff7235f3734c9fa364e340c222f267f9dd17 ), I get an empty and unusable .svg - https://www.shlomifish.org/humour/images/1538381903--mushroom.min.svg . I'm using the latest minify on mageia v7 x64.

**Comment by tdewolff** [comment]
Thanks for the bug report, I will look into it. As I have very limited time lately it might take a little longer of me to get back to this, sorry for that!

**Comment by shlomif** [comment]
@tdewolff : thanks for the update. No problem,

**Comment by tdewolff** [comment]
Looks like this was also fixed by f40d33a2269564183b02bb7a31365f0ceb2a49a0 and seems to correctly minify the SVG now. If this is still an issue you can reopen ;-)

**Comment by shlomif** [comment]
@tdewolff : thanks! Seems fine now in ff and chromi. KDE's gwenview handles the minified image wrong, but it is likely their bug.
