### ISSUE TITLE
JS minification of switch/case could be improved

### ISSUE THREAD

**Issue by JRaspass** [tdewolff/minify#248]
```js
switch (foo) {
    case 'bar':
        bar();
        break;
    case 'baz':
        baz();
        break;
}
```
is currently minified to:
```js
switch(foo){case 'bar':bar();break;case 'baz':baz();break;}
```
A simple improvement is to drop the whitespace between `case` and literal string. Two additional wins are to drop the redundant trailing `break` and omit the trailing semi-colon because of the surrounding block but that's probably more of a #18 thing.

**Comment by JRaspass** [comment]
Had a quick poke at the code, I now understand why #18 is such a big project :-P

I can't just match on `js.Case` because JavaScript isn't currently parsed, just lexed.

**Comment by tdewolff** [comment]
True, but the combination of `case` and `string literal` might be added for whitespace suppression. I'm a little afraid it might break another construct though. Ideally I'd like to completely revamp the JS minifier and, among other things, do proper semi-colon and newline removal. I don't think I'll do this anytime soon though...

**Comment by JRaspass** [comment]
That's fair, and thanks for the quick reply @tdewolff, I'll see what else I can change/break ;-)

This really is a superb project, and bloody fast!

**Comment by tdewolff** [comment]
Thanks @JRaspass very much appreciated! The whole JS minifier will have to be revamped, but if you are interested, there is still much left to do for SVGs. Also CSS could enjoy more minification although it is a little more subtle.

**Comment by tdewolff** [comment]
I will close this in favor of keeping discussion in #18
