### ISSUE TITLE
css: runtime error: index out of range

### ISSUE THREAD

**Issue by aofei** [tdewolff/minify#252]
Somehow, this line has panic:

https://github.com/tdewolff/minify/blob/2524af8f5589b64967cb0dd441af44b9b3bc02a8/css/css.go#L667

It's certain that this is not caused by misuse. More detailed content is still being collected. I opened this issue first for people who have encountered the same panic to share more information here.

**Comment by aofei** [comment]
> It's certain that this is not caused by misuse.

This is because the same code does not have any problems in the `v2.3.8`. It seems that this problem was introduced in the `v2.4.0`.

**Comment by tdewolff** [comment]
This is a bug in the code that will be fixed soon. Thanks for the issue!

**Comment by aofei** [comment]
Hi @tdewolff, I'd like to know when you plan to release the next version? Maybe a `PATCH` version, like `v2.4.1`. I'm not pushing you, I just need to check it. Of course, if you don't have any plan, I can use the `master` version for the time being. :-)

**Comment by tdewolff** [comment]
Done! It's `v2.5.0`
