### ISSUE TITLE
Add to brew?

### ISSUE THREAD

**Issue by karkraeg** [tdewolff/minify#253]
The current way of installing on macOS is a bit cumbersome, would be great if minify could be added to [brew](http://brew.sh).

**Comment by tdewolff** [comment]
I am unfamiliar with brew, but shouldn't `brew tap tdewolff/minify` work?

**Comment by karbecker** [comment]
I think it’s missing a formula then…

```
brew tap tdewolff/minify                                                                 
Updating Homebrew...
==> Tapping tdewolff/minify
Cloning into '/usr/local/Homebrew/Library/Taps/tdewolff/homebrew-minify'...
remote: Repository not found.
fatal: repository 'https://github.com/tdewolff/homebrew-minify/' not found
Error: Failure while executing; `git clone https://github.com/tdewolff/homebrew-minify /usr/local/Homebrew/Library/Taps/tdewolff/homebrew-minify --depth=1` exited with 128.
```

I’ll see if I find time to look into this, am interested how this works! Thanks for your awesome minifier 😊

**Comment by tdewolff** [comment]
Thanks!

Looks like I need to create `homebrew-minify`, or something more general for all my projects. I'll get into this some time soon ;-)

**Comment by tdewolff** [comment]
I've added a homebrew tap at https://github.com/tdewolff/homebrew-tap, you should be able to install `minify` using:

```
brew install tdewolff/tap/minify
```

It works for me, can you check if it works for you too? If not please re-open the issue.
