### ISSUE TITLE
HTML inline css class whitespace not removed

### ISSUE THREAD

**Issue by kundkingan** [tdewolff/minify#254]
I have an issue with minify my HTML.

The issue is with css classes in HTML elements.

For example this code here

```
<table class="row
                        regular
                          
                        
                        m-full-width">
```

Will be transformed to.
```
<table class="row
                        regular
                          
                        
                        m-full-width">
```

Is there any fix for this issue?

**Comment by tdewolff** [comment]
You are right, this is not being minified. I will work on a fix, thanks for bringing it up!
