### ISSUE TITLE
Braces (closing brace) in style tags creating issues in minification.

### ISSUE THREAD

**Issue by sunnykarira** [tdewolff/minify#255]
The code hangs when we try to minify the HTML having right brace in style tag.

**To replicate the issue**

```
<!DOCTYPE html>
<html>
<body>
<div style="text-align: justify;"><span style="font-size:18px;"><span style="color:#555555;"><em>Nous avons eu récemment le plaisir de vous présenter notre nouvelle <strong>Cuvée Brut  Millésimé 2008</strong>, modèle d&#39;légance et de savoureuse fraicheur qui sublime une très grande année champenoise ; ainsi que notre assortiment inédit <q style="quotes:&#39;«&#39; &#39;»&#39;;
}"> cuvée de lumière </q> qui réunit les somptueux millésimes 2006 et 2008.</em></span></span></div>
 </body></html>
```

This is a valid HTML but while trying to minify the code hangs and the parser continuously try to parse right brace at the end.

The library tries to create a `NewError` on every parse which results in a lot of memory consumption.
Below is the stack trace.

```
goroutine 35 [runnable]:
github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse.NewError(...)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/error.go:22
github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse.NewErrorLexer(...)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/error.go:33
github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/css.(*Parser).parseDeclarationList(0xc000104280, 0xc000000000)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/css/parse.go:208 +0x1a1
github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/css.(*Parser).Next(0xc000104280, 0x156b38b, 0x1, 0x1, 0x1)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/parse/css/parse.go:132 +0xa5
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css.(*cssMinifier).minifyGrammar(0xc0000bd8c8, 0x13499f8, 0xc000104280)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css/css.go:73 +0x4a
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css.(*Minifier).Minify(0x156ba20, 0xc00009ed20, 0x1399c60, 0xc00000e0c0, 0x1399c40, 0xc00000e560, 0xc00009ec60, 0x0, 0x0)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css/css.go:64 +0x100
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css.Minify(0xc00009ed20, 0x1399c60, 0xc00000e0c0, 0x1399c40, 0xc00000e560, 0xc00009ec60, 0xc0000d2138, 0xc0000bda48)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/css/css.go:50 +0x70
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify.MinifierFunc.Minify(0x13499e8, 0xc00009ed20, 0x1399c60, 0xc00000e0c0, 0x1399c40, 0xc00000e560, 0xc00009ec60, 0xc00000e560, 0xc0000bda78)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/minify.go:29 +0x65
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify.(*M).MinifyMimetype(0xc00009ed20, 0x156b4c8, 0x8, 0x8, 0x1399c60, 0xc00000e0c0, 0x1399c40, 0xc00000e560, 0xc00009ec60, 0x40, ...)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/minify.go:139 +0x28a
github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/html.(*Minifier).Minify(0xc0000bdf23, 0xc00009ed20, 0x1399b00, 0xc00009e7b0, 0x139a180, 0xc00000e040, 0x0, 0x0, 0x0)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/vendor/github.com/tdewolff/minify/html/html.go:393 +0x1a83
github.com/DTSL/email-sending/benchmark.BenchmarkMinfiy(0xc0000aa000)
	/Users/sunnykarira/Documents/go/src/github.com/DTSL/email-sending/benchmark/benhcmark_minify_test.go:39 +0x21d
testing.(*B).runN(0xc0000aa000, 0x1)
	/usr/local/go/src/testing/benchmark.go:176 +0xb3
testing.(*B).run1.func1(0xc0000aa000)
	/usr/local/go/src/testing/benchmark.go:249 +0x5a
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:242 +0x7d

rax    0x104
rbx    0x34100
rcx    0x7ffeefbff5f8
rdx    0x34100
rdi    0x15a47c8
rsi    0x3410100034200
rbp    0x7ffeefbff690
rsp    0x7ffeefbff5f8
r8     0x0
r9     0x60
r10    0x0
r11    0x202
r12    0x15a47c8
r13    0x7ffeefbff618
r14    0x1
r15    0x7fff9f616380
rip    0x7fff66c60a16
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
exit status 2
```
Could you please help on this?
Thanks

**Comment by tdewolff** [comment]
Thanks for the bug report. Looks like the minimal reproducible example is: `<q style="}">`. Please try the new fix and see if that solves it for you.

**Comment by pierrre** [comment]
Hi !
Thank you for the quick fix.
We (I work with @sunnykarira ) will test it tomorrow.

One issue is that we can't update to the latest version, because we can't yet use the Go modules.
We're still using the dep tool (several problems prevent us to change currently).

**Comment by pierrre** [comment]
After some thoughts, we will migrate to Go modules, but it will take some time.

FYI, I was reading the Go modules documentation:
> The module path must end with /v3. Copy or move the code into the v3 subdirectory. Update import statements within the module to also use /v3
> This provides greater backwards compatibility. In particular, Go versions older than 1.9.7 and 1.10.3 are also able to properly consume and build a v2+ module created using this approach.

Using a sub-directory is a nice approach to let people use the latest versions. (instead of requiring the usage of modules)

**Comment by tdewolff** [comment]
I've been very unsatisfied in the way they handled introducing Go modules. Requiring the `v2` directory for old Go versions only, was a big breaking change. This Go package has no version one anymore, so it made little sense to move everything to a `v2` directory. I've decided to support the new Go modules at some point, and I think changing the project organization now will only break it for other people. I will keep the structure as it is.

Perhaps adding something like a symlink or git submodule on `/v2` that points to the root of the project will solve this? Anyways, I was also assuming people would be upgrading to Go 1.10.3 and 1.9.7. Do you guys have the ability to upgrade to any of these Go versions? No need to start using Go modules yet that way.

**Comment by pierrre** [comment]
> I've been very unsatisfied in the way they handled introducing Go modules.

Yes me too

> Perhaps adding something like a symlink or git submodule on `/v2` that points to the root of the project will solve this? Anyways, I was also assuming people would be upgrading to Go 1.10.3 and 1.9.7. Do you guys have the ability to upgrade to any of these Go versions? No need to start using Go modules yet that way.

I don't know, for some reasons we can't use the recent tags of minify.
We are using `dep` with vendoring.
Maybe it's the cause of the issue.

Anyway, for now we have disabled CSS minification temporarily, and are working to migrate all our projects to modules.
Thank you for your help ! :+1:

**Comment by tdewolff** [comment]
No worries, I don't know much about `dep` so can't help much here, but if you find a way to improve the compatibility of `minify` with `dep` or older Go versions please let me know!

**Comment by sunnykarira** [comment]
Hi tdewolff,
Thanks for the fix.

**Comment by pierrre** [comment]
Hi !
Is it planned to release a new tagged version ?

**Comment by tdewolff** [comment]
Put out a new release, name v2.5.1!
