### ISSUE TITLE
Height and width attributes removed when <rect> is converted to <path>

### ISSUE THREAD

**Issue by tomanistor** [tdewolff/minify#256]
Hi,

I'm having some trouble with an SVG pattern. When minified, `<line>` and `<rect>` elements are converted to paths, but the in the conversion, the `height` and `width` attributes attached to the `<rect>` element is lost.

It looks like with `width="100%" height="100%"` this creates a path that is 100x100 pixels and no longer takes up 100% of the container's space.

I tried replacing the attributes with a CSS class instead and had more success that way because the `<rect>` didn't get converted to a path and so it took up 100% of the space as intended. However, this method had a different problem. If the window was expanded after page load, the `<rect>` element remained the same size rather than expanding also.

Codepen example: https://codepen.io/timehammer/pen/LowJvM

**Comment by tdewolff** [comment]
Well spotted, should be fixed now!

**Comment by tomanistor** [comment]
Thank you @tdewolff, I appreciate the quick fix! Hope to see it in the next version of Hugo 🤞
