### ISSUE TITLE
CLI: add --sync flag to copy files that are not minified

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#257]
https://simpleit.rocks/web/html/compacting-html-code/ says:

> To minify all the HTML pages in a directory and its sub-directories, official docs recommends the usage of $ minify -r -o out/ --match=\.html src to minimize all the files inside the src directory. But in my experience, it also removes non HTML files, so I recommend to traverse all the directories looking for HTML files with the find command.

**Comment by marcanuy** [comment]
> I've reviewed this and found out that I had misunderstood the command usage. What was happening is that I was always using the `--output` parameter and expected to see all files of the processed directory, those minified and non-minified, in the output directory.
> 
> So when I applied the `--match` parameter I only saw the minified files in the resulting directory then I thought there could be a problem with that feature and chose `find` to be sure which files were being modified. 🤦🏻‍♂️
> 
> 

x-post: https://simpleit.rocks/web/html/compacting-html-code/#comment-4508550713

**Comment by tdewolff** [comment]
I see. The minifier will only process files that match the given pattern, thus no other files are touched. Setting a different output directory will copy only those files there. I'm not sure whether `minify` should just copy the other files or not. On the one hand the CLI does not minify those other files, so why copy them? On the other hand, I suppose a broader audience would be interested in a more general directory-minification tool that copies the files to a new directory (as is a typical usecase when transferring files to a `dist` or `public` directory). What do you think? Should there be another option to copy over unmatched files?

**Comment by marcanuy** [comment]
For me it looked more natural to copy all files present in the directory, that's the behaviour I expected to see originally, but I understand it would be slightly out of the scope of the minifier.

As the `--output` parameter is used for single files but also for directories, adding another one just for a special case of the directories scenario like `--output-all` seems it won't be so clear.

I think it is better to keep the number of parameters low, and not having another one like `--output-all` for this case which can be easily done with another command, just adding something similar to this to docs would be enough:

   -o, --output string                    Output file or directory **with minified files only** (must have trailing slash), leave blank to use stdout

Hope it helps!

**Comment by tdewolff** [comment]
I think the library would benefit from a `--sync` flag, that minifies all files that match and copies the rest. It adds another flag but it is a common scenario. On the otherhand, I would not expect a CLI tool that minifies files to be touching other file types as well without explicitly telling it to do so (e.g. with `--sync`). I'll work on the implementation!
