### ISSUE TITLE
Just question about the minify tool

### ISSUE THREAD

**Issue by variadico** [tdewolff/minify#26]
This isn't an issue, more of a question. The minify tool looks cool, but what do you think about making it more like `go build`?

For example, let's say I have a folder like this.
```
$ tree .
css
├── foo.css
├── bar.css
├── fizz.css
└── buzz.css
```

What if I could use the `minify` tool to "build" or "compile"—but really to minify—the files in that folder. So you could say something like `minify .` and then all of your CSS files would be minified.
```
$ minify .
$ tree
css
├── foo.css
├── foo.min.css
├── bar.css
├── bar.min.css
├── fizz.css
├── fizz.min.css
├── buzz.css
└── buzz.min.css
```

Then, each time you call `minify .`, the `.min.css` files get overwritten with the latest version of the non-minified version.

Does that sound like something interesting? Or not at all? I could help with a pull request if you'd like. Otherwise, cool, just wondering. :)

**Comment by tdewolff** [comment]
Sounds like a good request. I suggest to keep the current functionality and add a flag like '-d' for directory which defines the directory to minify. It would then minify files by file extension and add '.min' before the extension. Perhaps add an '-r' for recursive to recursively minify everything.

You can make a pull request if you like!

**Comment by variadico** [comment]
So, question: Why did you use `minify.AddFuncRegexp` here?

https://github.com/tdewolff/minify/blob/master/cmd/minify/main.go#L89-L90

Would it be reasonable to use this instead?

```
m.AddFunc("application/json", json.Minify)
m.AddFunc("text/xml", xml.Minify)
```

**Comment by tdewolff** [comment]
Because any mime-type that ends with `/json` or `+json` is valid JSON, same goes for XML. See for example the top entries in this table: http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by variadico** [comment]
Oooh, okay. Gottcha.
