### ISSUE TITLE
Case where minifying go templates fails

### ISSUE THREAD

**Issue by zaddok** [tdewolff/minify#261]
In the last two lines of this example:

```
;['dragenter', 'dragover'].forEach(eventName => {
{{range .DocumentTypes}}
  e = document.getElementById('drop_{{.GetKey}}');
  e.addEventListener(eventName, function(){setFileType('{{.GetKey}}')}, false)
  {{end}}
})
```

the `{{end}}` becomes `{{end}}}`

I wonder if there is a temporary workaround for this?

**Comment by tdewolff** [comment]
I don't think so, templates are not supported by these minifiers as this is actually quite complicated. I would recommend minifying the resulting JS code instead (and since the minifiers are fast this should be no problem). This issue will be tracked in https://github.com/tdewolff/minify/issues/35
