### ISSUE TITLE
css font-family names bug

### ISSUE THREAD

**Issue by monopolly** [tdewolff/minify#265]
Hi,

there is a font name (import from google)
'Caveat', cursive

so its minify to 
caveat, cursive

I think its wrong because I can't use it after.

**Comment by monopolly** [comment]
yeah, also you cut a brace for @import
need @import('https://fonts.googleapis.com/cssfamily=Roboto:300);

and we have
@import 'https://fonts.googleapis.com/cssfamily=Roboto:300;

**Comment by tdewolff** [comment]
`@import('url')` is invalid syntax, both `@import 'url'` and `@import url('url')` are equal, see https://developer.mozilla.org/en-US/docs/Web/CSS/@import

For the `font-family`, I've just tested this in Chrome where I import a font and access it through a lower-case name without quotes, and it works. See https://drafts.csswg.org/css-fonts-3/#font-family-casing

```
<!doctype>
<html>
    <head>
        <title>Mansalva</title>
<style>
/* latin */
@font-face {
  font-family: 'Mansalva';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Mansalva Regular'), local('Mansalva-Regular'), url(https://fonts.gstatic.com/s/mansalva/v1/aWB4m0aacbtDfvq5NKliKY8.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
</style>
    </head>
    <body>
        <p style="font-family:mansalva;">Test</p>
    </body>
</html>
```

Please be a little more specific of the problems you have (what browser, software, environment) and what error / bug you see. As per the official CSS specifications, the minification is perfectly valid.
