### ISSUE TITLE
go html templates code get lowercase after minify

### ISSUE THREAD

**Issue by cydside** [tdewolff/minify#268]
Here the html template:
`
					<select class="form-select" id="employeegend" name="emp_gend" value="{{.ItemSel.EmployeeGend}}">  
						<option {{ if eq .ItemSel.EmployeeGend "M" }}selected{{ end }} value="M">Maschio</option>
`
in the option html statement the expression .ItemSel.EmployeeGend become itemsel.employeegend and that produce a fault at execution time. It seems that --html-keep-default-attrvals can help but I can't put it in production without a more investigated use.
Hope this can help.

**Comment by tdewolff** [comment]
The HTML minifier can only minify HTML and not the Go template syntax. I recommend you execute the template and then do the minification and not the other way around.

There are plans to support the Go template syntax (and other templating syntaxes) in the future, but this is more complicated than it sounds.
