### ISSUE TITLE
"type" attribute lowercasing not always desirable

### ISSUE THREAD

**Issue by kabukky** [tdewolff/minify#270]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes the "type" attribute is only specified for `<button>, <input>, <command>, <embed>, <object>, <script>, <source>, <style>, <menu>`.

However, [AMP](https://developers.google.com/analytics/devguides/collection/amp-analytics) are using the "type" attribute on `<amp-analytics>` as well.

We've run into issues where the "type" attribute value is case sensitive, specifically with the [Adobe Analytics](https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/accelerated-mobile-pages.html#section_3556B68304A4492991F439885727E9FF) implementation: When using Minify, "adobeanalytics_nativeConfig" gets lowercased to "adobeanalytics_nativeconfig" which breaks the implementation.

Could you enable "type" attribute lowercasing only for specific HTML tags, e. g. the ones in the HTML spec?

**Comment by tdewolff** [comment]
See d843c1073df21c584da37018ad96abe47a1e7913, 3f3065622cd02aa1d6673eeb6a43af2403f2d53b, 261d800d41d9536b6efbcd3ce7757ca44d1e637f for the fix. This will fix a wider range of potential bugs by ensuring that only HTML5 element attributes are minified specially, following the Living HTML specification: https://html.spec.whatwg.org/
