### ISSUE TITLE
Issue while updating the minfiy library in my personal project

### ISSUE THREAD

**Issue by RO-29** [tdewolff/minify#273]
`go get -u all`

```
../../go/pkg/mod/github.com/tdewolff/minify/v2@v2.5.2/html/table.go:60:2: undefined: html.Keygen
```

Maybe it requires a new release?

**Comment by RO-29** [comment]
`html.Keygen` exists in v2.5.2
https://github.com/tdewolff/minify/blob/v2.5.2/html/table.go#L60


but not in the master
https://github.com/tdewolff/minify/blob/master/html/table.go

**Comment by pierrre** [comment]
https://github.com/tdewolff/parse/commit/24e08b0f6a5bb95e493f5a0589077b1f6fe9da4b is breaking the backward compatibility

**Comment by tdewolff** [comment]
Ooops, was a little too eager to push the changes. Should be fixed in tdewolff/parse@09ec6e8c0f2b637843268b292bad2ad856685bc4, let me know if this works for you.

**Comment by tdewolff** [comment]
Use the latest version of `minify` for it to work. Give me another day to fix this `master` branch.

**Comment by pierrre** [comment]
For now I've used the `replace` instruction in `go.mod` with an older version.
So I can't accidentally upgrade to the version that breaks the backward compatibility.
