### ISSUE TITLE
CSS: background shorthand mangles background-size width set to auto

### ISSUE THREAD

**Issue by picasticks** [tdewolff/minify#281]
Hi! Here's the issue that I'm seeing:

It's with the [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) shorthand property, specifically when a [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) is specified after the  `/` separator. It only seems to happen when the background size width is set to the "auto" keyword (this is the syntax for specifying a height and then the browser scales the image width according to the image's proportions).

Example:
`background: url(foo.png) no-repeat 50% 11px/auto 78px;`

Minifies to:
`background:url(foo.png)no-repeat 50% 11px 78px;`

Which is invalid syntax and causes the property to be discarded by Firefox.

Expected result would be:
`background:url(foo.png)no-repeat 50% 11px/auto 78px;`

`background-size: auto 78px;` minifies correctly.

I looked at css.go and can't totally decipher a fix, sorry.

Also, if you put `/78px auto` then there is no issue and it's not mangled, the result is unchanged. However that value you can minify to `/78px` because height defaults to auto when only width is specified. It might be that's what the code is trying to do and there is an [i+2] or [i+3] off somewhere. Thanks for any attention to this issue!

**Comment by tdewolff** [comment]
Thanks for the report, seems like I had this already fixed in `develop`. Let me push out a new release soon!

**Comment by tdewolff** [comment]
Released v2.7.0

**Comment by picasticks** [comment]
Awesome, thanks!
