### ISSUE TITLE
HTML minification is working probably, discussing template minification

### ISSUE THREAD

**Issue by Techassi** [tdewolff/minify#287]
Hi there,

I implemeted the minifier with the template function replacement. I am seeing some unexpected behaviour:

Un-minified:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8" />
    <base href="http://127.0.0.1/" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <meta name="description" content="" />

    <meta property="og:description" content="" />
    <meta property="og:title" content="Home" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://127.0.0.1/" />
    <meta property="og:image" content="" />

    <title>Home</title>

    <link rel="stylesheet" href="/css/app.min.css" />
</head>

<body data-barba="wrapper">
    <script src="/js/app.min.js" defer></script>
</body>

</html>
```

becomes this after minification:

```html
<!DOCTYPE html>

<html lang="en" dir="ltr">


<head>

   
<meta charset="utf-8" />

   
<base href="http://127.0.0.1/" />

   
<meta name="viewport" content="initial-scale=1.0, width=device-width" />

   
<meta name="description" content="" />


   
<meta property="og:description" content="" />

   
<meta property="og:title" content="Home" />

   
<meta property="og:type" content="website" />

   
<meta property="og:url" content="http://127.0.0.1/" />

   
<meta property="og:image" content="" />


   
<title>Home</title>


   
<link rel="stylesheet" href="/css/app.min.css" />

</head>


<body data-barba="wrapper">

<script src="/js/app.min.js" defer></script>

</body>


</html>
```

The file size goes up by 3 bytes.

Is this intended behaviour, is there something wrong with the minifier or did I implement this in a false way?

Thank you for your feedback, cheers!

**Comment by tdewolff** [comment]
Are you minifying a Go template for HTML by a HTML minifier? Or do you minify the output of the template (which is HTML) by a HTML minifier? If it is the first case, the HTML minifier does not work well on Go templates (mainly because a Go template for HTML is itself not valid HTML). Can you clarify your usage?

**Comment by Techassi** [comment]
I'm using this function:

```golang
func CompileTemplates(pattern string, funcMap template.FuncMap) (*template.Template, error) {
	filenames, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}
	if len(filenames) == 0 {
		return nil, fmt.Errorf("template: pattern matches no files: %#q", pattern)
	}

	m := minify.New()
	m.Add("text/html", &html.Minifier{
		KeepDefaultAttrVals: false,
		KeepWhitespace:      false,
		KeepDocumentTags:    false,
	})

	var tmpl *template.Template
	for _, filename := range filenames {
		name := filepath.Base(filename)
		if tmpl == nil {
			tmpl = template.New(name)
		} else {
			tmpl = tmpl.New(name)
		}

		b, err := ioutil.ReadFile(filename)
		if err != nil {
			return nil, err
		}

		mb, err := m.Bytes("text/html", b)
		if err != nil {
			return nil, err
		}
		_ = mb
		tmpl.Funcs(funcMap)
		tmpl, err = tmpl.Parse(string(b))
		if err != nil {
			fmt.Println(err)
		}
	}
	return tmpl, nil
}
```

It is based on your function in the README at https://github.com/tdewolff/minify#templates
So I think I am minifying a template, which as you state is not standard HTML. Is there either a way to accomodate the special golang template mustache syntax or to minify the generated HTML on the fly?

**Comment by tdewolff** [comment]
You will have to apply the minification _after_ executing the template. The output of the executed template should be HTML.

There is a possibility that template/mustache syntax can be minified too and I want to investigate this. Can you post the template source for the example you gave?

**Comment by Techassi** [comment]
> You will have to apply the minification after executing the template. The output of the executed template should be HTML.

How can I accomplish this. Can you give me an example on how to do this?

> There is a possibility that template/mustache syntax can be minified too and I want to investigate this. Can you post the template source for the example you gave?

Actually the above example was plain HTML, without any mustach systanx to elimiate this as the problem. 

It would be great to further optimizie your minifier to support the mustache syntach, as it allows the template to be minified beforehand and not on every request!

**Comment by tdewolff** [comment]
I'm not following, you're saying the `b, err := ioutil.ReadFile(filename)` line reads in a HTML file _without_ mustache brackets? Why would you parse that as a template (`tmpl, err = tmpl.Parse(string(b))`) if it is not a template?

If I input the un-minified file you posted into https://go.tacodewolff.nl/minify, it says: `Size: | 696B → 521B`. Are you sure you correctly call the HTML minifier and not some other minifier?

> How can I accomplish this. Can you give me an example on how to do this?

At some point you'll call `Execute` or `ExecuteTemplate` that outputs to a `io.Writer`. Connect the minifier to the `io.Writer`.

**Comment by Techassi** [comment]
Okay I think we are talking past each other.
1. I implemented the `template.ParseFiles` replacement, see here https://github.com/tdewolff/minify/issues/287#issuecomment-577777039 and here in your README: https://github.com/tdewolff/minify#templates
2. I tried to parse my templates with the minifier (and mustach syntax) and I was getting a whole lot of template errors. To elimiate the mustach syntax as the problem I used a plain HTML file, which got parsed as a template (which shouldn't be a problem) and then minified, which resulted in https://github.com/tdewolff/minify/issues/287#issue-552246729
3. I am 100% sure that I call the "right" minifier, because there is only one minifier imported, which is yours. See again https://github.com/tdewolff/minify/issues/287#issuecomment-577777039 for the minifier implementation.

> At some point you'll call Execute or ExecuteTemplate that outputs to a io.Writer. Connect the minifier to the io.Writer.

Okay. Seems like an not so elegant solution. I would be way better for performance reasons to minify the templates before the actual templating, so that we don't have to minify the parsed template on every HTTP request we make.

**Comment by tdewolff** [comment]
Alright let's see. It is weird that https://go.tacodewolff.nl/minify minifies your source correctly, but as soon as you use the library it doesn't. You don't seem to use the `mb` variable in https://github.com/tdewolff/minify/issues/287#issuecomment-577777039, is this accidental? Otherwise, print the contents of `b` and `mb` _directly_ before and after minification, surely something is off!

> I am 100% sure that I call the "right" minifier, because there is only one minifier imported, which is yours.

It looked like you minified using XML/SVG minifiers that are also in the package, but the code you posted should minify HTML correctly.

> Okay. Seems like an not so elegant solution. I would be way better for performance reasons to minify the templates before the actual templating, so that we don't have to minify the parsed template on every HTTP request we make.

It is not elegant but it is more correct. A HTML Go template is not HTML, and the minifier only works (at the moment) for HTML.

**Comment by Techassi** [comment]
I will look into it. Thank you for your help!

I will keep you updated!

**Comment by tdewolff** [comment]
Probably you're right, but I wasn't 100% sure about all the edge-cases. I'll work on template support soon!

About the one-liner, the minifier prefers to minify a sequence of whitespace containing a newline into a newline. This is the same size of a space but prevents extremely long lines in most cases. Could you give me the output you're getting?

**Comment by Techassi** [comment]
Sorry for my late response...

The output is pretty lame. Just some multiline HTML, but way less the the origial file / template. Going from 100 to 6 / 7 lines. I just thought about minifying into a one-liner to save even more bandwidth or what were your intentions to keep some of the newlines?

**Comment by tdewolff** [comment]
Some spaces need to be retained to keep the same semantics. These spaces can also be newlines, the size is the same. Replacing newlines by spaces does NOT make the file smaller/save more bandwidth! The amount of lines Ina file says nothing about the size of the file! Less lines do not mean that bandwidth is being saved.

**Comment by Techassi** [comment]
Okay! Didn't know that.

We should close this issue or do you want to keep it open to further discuss the templating syntax?

**Comment by tdewolff** [comment]
No worries ;-)

Yes, I think I'll leave it open for a bit and see what I can do to improve template support.

**Comment by Spotlight64** [comment]
Hello! I also have the same issue. The minify worked on HTML tags, styles and scripts.
```
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport"content="width=device-width, initial-scale=1.0"><link rel="stylesheet"href="/static/assets/css/index.css"><title>Document</title><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script><script src="/static/assets/js/index.js"></script><style>.green{color:green;}</style></head><body><h1 class="red"id="bold">YES</h1><p class="green">I am green.</p><div class="custom-container"></div><script>$("h1").on("click",function(){console.log("NO");});$(".custom-container").append("WOW!");</script></body></html>
```

PageHandler
```
package views

import (
	"html/template"
	"io/ioutil"
	"net/http"
	"path/filepath"

	"github.com/tdewolff/minify"
	"github.com/tdewolff/minify/js"
)

// PageHandler !
func PageHandler(w http.ResponseWriter, r *http.Request) {
	// uadmin.RenderMultiHTML(w, r, []string{"templates/index.html", "templates/sub.html"}, nil)
	tmpl := template.Must(compileTemplates("templates/index.html"))
	tmpl.Execute(w, nil)
}

func compileTemplates(filenames ...string) (*template.Template, error) {
	m := minify.New()
	m.AddFunc("application/javascript", js.Minify)

	var tmpl *template.Template
	for _, filename := range filenames {
		name := filepath.Base(filename)
		if tmpl == nil {
			tmpl = template.New(name)
		} else {
			tmpl = tmpl.New(name)
		}

		b, err := ioutil.ReadFile(filename)
		if err != nil {
			return nil, err
		}

		mb, err := m.Bytes("application/javascript", b)
		if err != nil {
			return nil, err
		}
		tmpl.Parse(string(mb))
	}
	return tmpl, nil
}
```

Now when I do something like {{define "content"}}Hello{{end}} {{template"content"}} in a separate HTML files, it did not work.

**sub.html**
```
{{define "title"}}
<title>Document</title>
{{end}}

{{define "content"}}
<h1 class="red" id="bold">YES</h1>
<p class="green">I am green.</p>
<div class="custom-container">
  
</div>
{{end}}
```

**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="/static/assets/css/index.css">

	{{template "title"}}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="/static/assets/js/index.js"></script>

	<style>
		.green {
			color: green;
		}
	</style>
</head>
<body>
	{{template "content"}}
	<script>
		$("h1").on("click", function(){
			console.log("NO");
		});
		$(".custom-container").append("WOW!");
	</script>
</body>
</html>
```

Inside the PageHandler function
```
tmpl := template.Must(compileTemplates("templates/index.html", "templates/sub.html"))
tmpl.Execute(w, nil)
```

**Result:** White screen on the webpage

**Comment by tdewolff** [comment]
Let's keep discussing this in the main issue at #35!
