### ISSUE TITLE
“Shortest HTML document” in README is not

### ISSUE THREAD

**Issue by chris-morgan** [tdewolff/minify#289]
#266 reduced `<html lang=en>` to `<html lang>`, but the `lang` attribute is not in fact required; it’s [merely encouraged](https://html.spec.whatwg.org/#the-html-element):

> Authors are encouraged to specify a lang attribute on the root html element, giving the document's language.

That that particular HTML validator produces a *warning* in the absence of `<html lang>` is neither here nor there: it’s a completely conformant document. And semantically, `<html lang>` is almost certainly equivalent to omitting the attribute. (“[Setting the attribute to the empty string indicates that the primary language is unknown.](https://html.spec.whatwg.org/#the-lang-and-xml:lang-attributes)” This probably means “guess, just as you would have done anyway”.)

That takes it down to `<!doctype html><title>x</title>`.

*In some situations*, the title is also optional. Specifically, [the `head` element’s content model is](https://html.spec.whatwg.org/#the-head-element):

> If the document is an `iframe srcdoc` document or if title information is available from a higher-level protocol: Zero or more elements […]

So in an `iframe srcdoc` or in an HTML email, `<!doctype html>` is valid.

Therefore, I declare that the shortest valid HTML document is `<!doctype html>`*.

(* Conditions apply.)

**Comment by tdewolff** [comment]
Great work! You're right in that the `lang` attribute is optional, I will amend that in the docs. For your second point, I would argue that we refer to an independent HTML page, i.e. not in an iframe or email, so that the title attribute is necessary. This could be clarified in the docs. Thanks for researching!
