### ISSUE TITLE
GZip Support

### ISSUE THREAD

**Issue by schmitch** [tdewolff/minify#29]
it would be great that you also have GZip Support for Assets, we then wouldn't need any of Grunt, Gulp for our static projects.

**Comment by tdewolff** [comment]
You can use the standard library for this, just pass the stream through a gzip compressor and it's gzipped!

**Comment by schmitch** [comment]
Yeah Thank's I've found out, however I didn't found out how to minify directly with a Http ResponseWriter, so that I could write some kind of middleware

**Comment by tdewolff** [comment]
You can use the same trick I suppose

**Comment by schmitch** [comment]
nah, minify wants a reader..

**Comment by tdewolff** [comment]
Use `io.Pipe` ideally (with a go routine), otherwise you can use an `buffer.Bytes` but that is bad for memory usage.

**Comment by schmitch** [comment]
I'm relativly new to go, could you show me an example?

**Comment by tdewolff** [comment]
```
func newGzipEncoder(r io.ReadCloser) (io.ReadCloser, error) {
	pr, pw := io.Pipe()
	encoder := gzip.NewWriter(pw)

	go func() {
		if _, err := io.Copy(encoder, r); err != nil {
			log.Println("newGzipEncoder:", err)
			r.Close()
			encoder.Close()
			pw.CloseWithError(err)
		} else {
			r.Close()
			encoder.Close()
			pw.Close()
		}
	}()
	return pr, nil
}
```

In this example I used gzip, but the concept is the same. `io.Pipe` gives a reader and a writer that act on each other simultaneously, so writing and reading happens at the same time and otherwise are blocking (thus you need a go routine).

**Comment by schmitch** [comment]
Btw. I also found a bug around some CSS3 things, should I post it in a new Issue?

And Thanks :) +1

**Comment by schmitch** [comment]
The current:
```
background: none repeat scroll 0 0...
```

Will be minified to:
```
background:0 repeat scroll 0 0....
```

Which is incorrect... It should be background: none and not zero since that will have different results.

**Comment by tdewolff** [comment]
Thanks, good find! It should be a new issue, I'll do that

**Comment by schmitch** [comment]
@tdewolff I still don't get your example, I mean httpResponseWriter has no reader, it will just write to the user. so pipe won't work?!

**Comment by tdewolff** [comment]
Hmm yes I always get confused with reader and writer transformations. Lets see; you want to turn a writer into a writer that minifies and then writes to the original writer.

``` go
pr, pw := io.Pipe()
go func() {
    if err := minify.Minify(m, "mime type", w, pr); err != nil {
        panic(err)
    }
}()
return pw
```

with `m` the minifier object, `w` the passed writer, `pw` the new writer and a certain mime type. This way any write to `pw` will instantly cause a read on `pr`, which lets the minifier proceed minifying and writing to `w`. I didn't test the code but something like this should work!
