### ISSUE TITLE
[v2.6.1] Removal of svg output elements causes missing elements

### ISSUE THREAD

**Issue by pocc** [tdewolff/minify#291]
## Problem 

minify removes subgraph clusters, edgePaths, edgeLabels, and nodes. 

## Details

You can visually see the difference in the SVG on the main page of tshark.dev for different deploys:

Working: https://tshark.dev
Failing: https://5e5631ba1523330008ceb7be--pedantic-lumiere-bf6286.netlify.com/
SVG HTML ID: `mermaid-tshark-dev`

You can get the full SVG for both with `document.getElementById('mermaid-tshark-dev').outerHTML` in your browser's dev console.

`document.querySelector('#mermaid-tshark-dev > g > g').children.length` and `document.querySelector('#mermaid-tshark-dev > g > g > g').children.length` both return 4 for the working version and 1 for the failing version (there are at least 6 HTMLElements that are missing).

### Failing instance info

Hugo Version: 0.65.3 (3 days ago)
Minify version (per go.mod): v2.6.1

## Errata

This relates to breakage with SVGs generated by MermaidJS like #260.

**Comment by tdewolff** [comment]
Thanks for the report! Seems that SVG has an element called `foreignObject` which is parsed as something other than SVG. I've added code to skip minification of the contents of those tags, fixing this bug. Let me know if this works for you!

**Comment by pocc** [comment]
Thanks for the fix! Which tagged version will feature this commit (and when can we expect that release)?

**Comment by tdewolff** [comment]
Released v2.7.3!
