### ISSUE TITLE
Semantic UI wrongly minified (for div.ui.form > div.fields > div.two.wide.fields)

### ISSUE THREAD

**Issue by kokizzu** [tdewolff/minify#292]
Not sure which property, but these are the result when using minifier:

![image](https://user-images.githubusercontent.com/1061610/76832850-c1726100-685c-11ea-875f-269a86114666.png)

Original:

![image](https://user-images.githubusercontent.com/1061610/76832864-c800d880-685c-11ea-9d42-9db9d28dda44.png)

Minimal HTML:
```
<div class="award_grid ui form">
	<div class="ui hidden divider"></div>
	<h3 class="ui header">Award and Reason</h3>
	<div class="ui two fields">
		<div class="one wide field">
			<select class="ui search dropdown" id="ddl_award" onchange="get_Award_text()">
				<option value="0">-</option>
				<option value="ee">EE</option>
				<option value="em">EM</option>
				<option value="ei">EI</option>
			</select>
		</div>
		<div class="fourteen wide field" id="ddl_award_text">Extraordinary Impact: Measured by the Scope, length and depth of Impact of any Initiatives or Projects</div>
	</div>
	<div class="field">
		<textarea id="award_reason"></textarea>
	</div>
</div>
```

Semantic UI link: https://semantic-ui.com/collections/form.html

all things broken (not just .fields) when there's `xxx/wide` class (where `xxx` is the number: one, two, three, four, twelve, etc)

current workaround, i exclude `semantic.css` to be minified (then combined to one file), and using `semantic.min.css` directly.

**Comment by tdewolff** [comment]
Problem seems to be in the CSS minifier which minifies `flex:0 1 auto` to `flex:0 1` incorrectly. It should be `flex:initial` in this case. Thank you for reporting!
