### ISSUE TITLE
Place !;(MISSING) after each % 

### ISSUE THREAD

**Issue by sandermirov** [tdewolff/minify#293]
After minify (css/js/html) 
if the text contains a percent sign place !;(MISSING)
Before:
`let foo = 10,
bar = foo % 2;
alert(bar);
console.log(foo);`
After:
`let foo=10,bar=foo%!;(MISSING)alert(bar);console.log(foo);`
Same on CSS and HTML

**Comment by tdewolff** [comment]
I don't understand, this has been solved? Do you want to place `!;(MISSING)` after each `%` or is it a bug that you were reporting?

**Comment by sandermirov** [comment]
It was my fault. I shouldn't have to use Fprintf after minify data
