### ISSUE TITLE
CSS border property incorrectly transformed

### ISSUE THREAD

**Issue by DejanPelzel** [tdewolff/minify#294]
Hi,

We have found a case where a border properly is incorrectly transformed into an invalid value, for example:
**border: medium none !important;**
is transformed into:
**border: medium 0!important;**

The browser then ignores this citing invalid property.

**Comment by tdewolff** [comment]
Are you using the latest version of `minify`? Testing in https://go.tacodewolff.nl/minify gives me `border:none!important` which should be correct.

**Comment by tdewolff** [comment]
Assuming you were using an old version of minify, please re-open if still happens with the current version.
