### ISSUE TITLE
Higher-level API?

### ISSUE THREAD

**Issue by matthewmueller** [tdewolff/minify#295]
Hey @tdewolff, thanks for putting this together!

I was wondering if you've thought about a higher-level API? I often reach for this library for testing, to remove whitespace and whatnot. 

That leads me adding this to my code:

```go
func minifyHTML(code string) (string, error) {
	m := minify.New()
	m.AddFunc("text/html", html.Minify)
	var out bytes.Buffer
	err := m.Minify("text/html", &out, bytes.NewBufferString(code))
	if err != nil {
		return "", err
	}
	return out.String(), nil
}
```

When what I'd love is something like this:

```go
html, err = minify.HTML(html)
css, err = minify.CSS(css)
js, err = minify.JS(js)
```

With good defaults picked by you.

Thanks!

**Comment by tdewolff** [comment]
Agreed, I'm not sure if people prefer `[]byte`, `string` or `io.Reader` as input, what would be more common you guess?

**Comment by tdewolff** [comment]
The problem was that you can't add that as it will create import cycles. Not sure how that could be fixed in a nice way...

**Comment by matthewmueller** [comment]
Might make sense as a separate package, something like: `github.com/tdewolff/min`. Then you could have something like the function I have above as sugar on top.

I guess io.Reader would be the most useful. It's pretty easy to get back to read in strings or bytes that way with:

```go
html = min.HTML(bytes.NewBufferString(html))
```

**Comment by tdewolff** [comment]
Hmm but you need to convert the returned `io.Writer` back to a string ;-). I implemented the string case for now, might be most intuitive for beginners. Any user that wants even a bit of control will quickly switch to the "main" API I suppose.
