### ISSUE TITLE
CSS import url on multiple lines is broken

### ISSUE THREAD

**Issue by hkdobrev** [tdewolff/minify#296]
```html
<style type="text/css">
  @import url(
    https://fonts.googleapis.com/css?family=Lato:400,700
  );
</style>
```
gets converted to

```html
<style type="text/css">
  @import "
    https://fonts.googleapis.com/css?family=Lato:400,700
  "</style>
```
which doesn't work.

Expected output:
```html
<style type="text/css">
  @import "https://fonts.googleapis.com/css?family=Lato:400,700"</style>
```

The source is produced by another automatic tool and only when trying to minify it the quotes around the URL are put incorrectly breaking any subsequent CSS in the style tag.

**Comment by tdewolff** [comment]
Thanks! Should be fixed now, let me know if that works for you

**Comment by hkdobrev** [comment]
Yes, I can confirm it works now! Thanks @tdewolff!
