### ISSUE TITLE
[Feature Request] Add support for {%  %} template tags

### ISSUE THREAD

**Issue by AlexSSD7** [tdewolff/minify#297]
Noticed that {{ }} template tags work seamlessly, but {% %} tags do not. These tags are used in many web frameworks like Django - the most popular one. I think this would be very cool to have {% %} tags minified.

### What is expected?
Properly minify HTML files with {% %} tags.

### What is wrong?
There is a bunch of random newlines in the minified file.

**Comment by tdewolff** [comment]
Neither should really work using this minifier as they aren't really supported. Usually it works out of the box but this is not guaranteed. I'm working on improving support for tags, thanks I'll keep you updated!

**Comment by tdewolff** [comment]
Closing this in favor of keeping discussion in #287
