### ISSUE TITLE
Ignore certain html parts

### ISSUE THREAD

**Issue by quoid** [tdewolff/minify#299]
I was wondering if it was possible to ignore certain html markup with a special comment/tag, like [`<!-- htmlmin:ignore -->`](https://github.com/kangax/html-minifier).

For example, let's say I want to preserve a *non-conditional* comment or a bit of multi-line html markup; is it possible to skip certain lines of a file.

I took a look at issue #228, but it looks like the solution that was found there is no applicable for this use case.

Thank you

**Comment by tdewolff** [comment]
Thanks for the feature request. Could you show me some use cases? In general I think comments should be removed unless it might be license information? Maybe you want to keep whitespace if you're misusing whitespace for element positioning (which is a bad idea)? Not sure what else?

**Comment by quoid** [comment]
The use case that motivated me to search or the feature I describe above was that I like to include build times as a comment in the `<head>` of my [hugo](https://gohugo.io) websites like this:

`<!--Hugo Build Date: Tue May 12 21:35:29 EDT 2020-->`

However, I wasn't initiating a feature request, I was unsure at the time of posting the issue if it was possible or not (but [subsequently found out it was not possible](https://discourse.gohugo.io/t/omit-certain-html-when-minifying/25041)). 

I don't know that my use case is compelling enough for a feature request - I agree with the points in your replay that *most* comments should be removed and markup hacks with comments aren't generally a great idea.

**Comment by tdewolff** [comment]
I'm unsure whether this warrants a new feature as it could be argued that build date information is irrelevant for HTML content (you could add it in the meta data or HTTP headers for example so other applications can use that information).

I'm not against this feature perse, but I think we'd need a strong case where it proves to be necessary and cannot be fixed otherwise. Thanks for bringing this to a discussion though!

**Comment by quoid** [comment]
> I'm unsure whether this warrants a new feature 

I tend to agree with your judgment call, here. If a more compelling use case comes up I will chime in, but otherwise, feel free to close the issue if you'd like.

Thanks again for the replies.
