### ISSUE TITLE
strings with whitespace unquoted

### ISSUE THREAD

**Issue by gj52** [tdewolff/minify#301]
A CSS validator ( http://jigsaw.w3.org/css-validator/ ) gives me a warning about font-family:
**INPUT**
body {
  font-family: "avenir next", georgia, serif;
 }
**MINIFIED**
body{font-family:avenir next,georgia,serif}

should be
body{font-family:"avenir next",georgia,serif}

**Comment by tdewolff** [comment]
Thanks for the report. I've rechecked the specification (https://drafts.csswg.org/css-fonts-3/#family-name-value) and it states that besides being quoted, it can be a a series of identifiers. The warning from the validator is:

> Family names containing whitespace should be quoted. If quoting is omitted, any whitespace characters before and after the name are ignored and any sequence of whitespace characters inside the name is converted to a single space.

Which is correct. The minifier will only remove quotes if there is no leading or training whitespace, and if all words are separated by only single spaces (see the tests). I think the minifier works according to the specification and that this warning can be safely ignored.
