### ISSUE TITLE
Error on go get - Go v1.14.3

### ISSUE THREAD

**Issue by dnnspaul** [tdewolff/minify#308]
Hi!

I don't know if I'm just stupid or if there' been a mistake. If the former, I would like to apologize in advance.

If you are familiar with Docker: with the following Dockerfile I can reproduce the problem:

```
FROM golang:1.14.3
RUN go get -v github.com/tdewolff/minify/v2
```

![image](https://user-images.githubusercontent.com/4589085/83980830-16cc8480-a919-11ea-8fe4-25ed755ce0a3.png)

It seems like the files won't be installed into the v2 directory. The command
```
go get -v github.com/tdewolff/minify
```
runs without any errors, but because the library itself imports the v2 it causes errors on building minify then.

**Comment by tdewolff** [comment]
You are not stupid! It looks to me that you are running Go with `GO111MODULE=off` which is then unable to recognize the `v2` in the import strings. Please verify what value that environment variable has and set it to `on` if you can. For example, run the following command: `GO111MODULE=on go get -v github.com/tdewolff/minify/v2` and see how that works for you. If for some reason you are unable to use Go modules, you should probably use the last version that didn't use Go modules and `go get` that specific git commit hash. Let me know if this works for you.

**Comment by dnnspaul** [comment]
Hey @tdewolff,
I really thought I tried that out, but it seems like it solved the problem now. Big thanks for the fast response!

For documentation, the Dockerfile is now:
```
FROM golang:1.14.3-alpine
RUN GO111MODULE=on go get -v github.com/tdewolff/minify/v2
```
