### ISSUE TITLE
Proposal - Option to keep HTML comments

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#310]
Using the Hugo static site generator, it would be helpful to have an option to keep HTML comments. Why?

Current process:

1. Build Hugo site.
2. Grep the HTML for a particular comment emitted by Hugo under certain conditions (bad things).
3. If the comment isn't present, build again with minification.

If we could keep the comments during minification, we would only have to build the site once, and we really don't care about the extra bytes that might be present due to other comments. 

Hugo build times are insignificant, so there's not much hardship in the current process. It just seems inefficient.

Thank you for your consideration.

**Comment by jmooring** [comment]
To be specific, the only comment we need to keep is `<!-- raw HTML omitted -->`. So if there were a way to specify a comment string to ignore, that would also be acceptable.

**Comment by tdewolff** [comment]
Hey Joe, thanks for the suggestion!

In general I try to keep the number of options down, so as to not fall for the same trap as other minifiers which have dozens of options. I think a minifier is something that should be applied to the production version of a website and isn't really needed/suited for debugging. I have the feeling that emitting HTML comments as part of the debug process is something specific to Hugo, so I'm unsure how this would help other users. For those reasons I'm leaning against this proposal.

However, if this is a widespread request amongst users and the HTML comments have a certain format to make filtering easier (like the JS license comment: `/*! license */`), we could either always keep those comments or alternatively add the option anyways. I'll close this for now, but I'm open for comments. Thanks for the interest!

**Comment by jmooring** [comment]
Understood. Thanks for the review.

**Comment by bep** [comment]
I agree with @tdewolff -- and the particular problem in Hugo, I think, needs some different medicine on the Hugo side. What, I 'm not totally sure, but different.

**Comment by cascading-jox** [comment]
> However, if this is a widespread request amongst users and the HTML comments have a certain format to make filtering easier (like the JS license comment: `/*! license */`), we could either always keep those comments or alternatively add the option anyways. I'll close this for now, but I'm open for comments. Thanks for the interest!

Has this been implemented? I have a use case where I have a html comment with a license text that I would like to keep after minification.

**Comment by tdewolff** [comment]
Yes, it's available at https://github.com/tdewolff/minify/blob/master/html/html.go#L49 !

**Comment by cascading-jox** [comment]
Thank you for the swift reply @tdewolff! Does this option save all comments during minification? I only need to save one comment and I was imagining I could do something like `<!-- !License text  -->`.

**Comment by tdewolff** [comment]
You could use SSI tags, such as `<!--# License text -->`, I haven't really found a common way to keep comments in HTML much like the shebang comments in JS, but if you have suggestions I'm open to that!

**Comment by cascading-jox** [comment]
Thank you for the help but  though. I will dig a bit more into this to see if it could be hugo messing something up.

**Comment by tdewolff** [comment]
True, Hugo is using an old version of minify, but actually today they updated it! I suppose a new version of Hugo is due any day now, and as soon as you updated it should be working.

**Comment by cascading-jox** [comment]
Alright, thanks a lot @tdewolff!
