### ISSUE TITLE
HTML: Not work probably included template literal

### ISSUE THREAD

**Issue by OmidHekayati** [tdewolff/minify#318]
I know that template literals are not pure HTML feature but it is very good feature to write page or widget templates that render in the client browser. But this minify package like #35 issue doesn't respect syntax even enable all HTML minifer options!   
convert this to next:
```html
            <datalist id="countries">
                ${Regions.map(r => `
                <option value="${r.nativeName}">${r.englishName}</option>
                `)}
            </datalist>
```

```html
<datalist id=countries>
${Regions.map(r => `
<option value=${r.nativeName}>${r.englishName}</option></datalist>
```

**Comment by tdewolff** [comment]
Hi Omid, thanks for raising the issue! Yes, HTML templates are not at all an HTML feature and are thus not implemented. I'm working on a solution for this. I think it would be best to concentrate discussing this feature in #35, so let's continue there.
