### ISSUE TITLE
Minified CSS icons

### ISSUE THREAD

**Issue by prologic** [tdewolff/minify#322]
Before:

<img width="368" alt="Screen Shot 2020-08-20 at 17 02 07" src="https://user-images.githubusercontent.com/1290234/90727607-e9338c80-e306-11ea-9e25-35836dbf97dc.png">

After:

<img width="364" alt="Screen Shot 2020-08-20 at 17 02 12" src="https://user-images.githubusercontent.com/1290234/90727627-ed5faa00-e306-11ea-94d6-d3d7ec59b2ab.png">

I'm not an expert in CSS to understand what you're tool is doing to my CSS here :/

**Comment by prologic** [comment]
For original source CSS see https://github.com/prologic/twtxt/tree/master/internal/static/css

**Comment by tdewolff** [comment]
Which version are you using of `minify`? Could you try with the latest v2.8.0?

I've ran the following test and it works fine for me:

```
minify -o icss.min.css icss.css
minify -o icons.min.css icons.css
```

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test</title>
    <link rel=stylesheet href="icss.min.css">
    <link rel=stylesheet href="icons.min.css">
</head>
<body>
    <i class="icss-text-bold"></i> test
</body>
</html>
```

Please let me know if you have something so I can reproduce the bug. Thanks!

**Comment by prologic** [comment]
I was running the latest from `master` and I ran the following:

```#!console
minify -o twtxt.min.css *.css
```

**Comment by prologic** [comment]
Or in other words I was _trying_ to combine and minify _all_ the CSS into a single file.

**Comment by tdewolff** [comment]
I've done the same thing (combine and minify all CSS to the same file) and I still get icons that are working well, I'm unable to reproduce the bug. Could you send the HTML file that is giving this problem so I can check? Can you make sure this is a CSS problem by confirming that the bug exists only after minifying the CSS (and not the HTML or other sources)? I was hoping you could give me an HTML + CSS file that shows the bug so that I can reproduce it.

**Comment by prologic** [comment]
The branch is [here](https://github.com/prologic/twtxt/tree/minify_css_js_assets)

```#!console
git clone github.com/prologic/twtxt
cd twtxt
git checkout minify_css_js_assets
make deps
make
```

Hopefully this helps! Yes I can confirm the weirdness in the icons  is only present _after_ minification/combination.

**Comment by prologic** [comment]
Can I do anything more to help figure this one out?

**Comment by tdewolff** [comment]
The problem is in the order of minification of files. You need to have `icss.css` before `icons.css`, which is in the right order originally due to the order of loading the CSS files, but in the minification this is not the case. Actually, in the current branch I executed the following commands which worked well:

```
$ cd internal/static/css
$ rm twtxt.min.css 
$ minify -o twtxt.min.css -v *
INFO: infer mimetype from file extensions
INFO: minify to output file twtxt.min.css
INFO: (5.818545ms,  50 kB,  38 kB,  75.5%, 8.6 MB/s) - (01-pico.css + 02-theme-switcher.css + 03-icss.css + 04-icons.css + 99-twtxt.css) to twtxt.min.css
INFO: 6.279787ms total
```

As you can see, the order is correct now. The order by the way is determined by your bash script (which expands `*` before calling `minify`) and not by `minify`. It might be best to verbosely specify the order to avoid this problem.

**Comment by prologic** [comment]
This is what I _thought_ too! So what I did was use an old UNIX trick and rename all the `*.css` with a numerical NN-` prefix. Hmmm Let me have another stab at this, perhaps it was my fault all along 🧐

**Comment by prologic** [comment]
Yup it works! I did something wrong before and/or I was half asleep 🥱

https://github.com/jointwt/twtxt/commit/3f98ae669dd94fc1a25a6f6e788aa6d54c2e6dc6 fixes this for me.

**Comment by prologic** [comment]
Oh oops I feel so dumb. I forgot to add originally that I was seeing this issue __only__ on IE11

See attached.

<img width="624" alt="Screen Shot 2020-08-25 at 09 17 19" src="https://user-images.githubusercontent.com/1290234/91105639-e690b880-e6b3-11ea-85fc-dd4b4e23c7df.png">

**Comment by tdewolff** [comment]
Did you properly refresh the browser cache? I think in IE that is a Shift+click on the refresh symbol.

**Comment by prologic** [comment]
Oh and one more thing I have noticed one icon in particular that lost its "eyes" -- It was suppose to be a smiley face :D

<img width="136" alt="Screen Shot 2020-08-26 at 7 48 56 AM" src="https://user-images.githubusercontent.com/1290234/91231516-bce99700-e770-11ea-99d7-ab31e2fe64a6.png">

**Comment by prologic** [comment]
> Did you properly refresh the browser cache? I think in IE that is a Shift+click on the refresh symbol.

Yes, even Deleted its cache :D Although I will check with a real user that uses a real Windows PC with IE11 since I was only able to test on a VM.

**Comment by prologic** [comment]
Please check/test https://twtxt.net (which you can find the source at https://github.com/jointwt/twtxt)

**Comment by tdewolff** [comment]
The eyes of the smiley is a bug, working on a solution. The IE11 problem is something I can't test on my Linux easily, I'm pretty sure this must be an artifact of the order of the CSS files, but if it persists I'll need to install a virtual machine.

**Comment by prologic** [comment]
Thank you! Look forward to the fix, Can we cut a new release too?

**Comment by tdewolff** [comment]
I'll push out a new release very soon, what happened with the IE11 problem?

**Comment by prologic** [comment]
I just pused jointwt/twtxt@dc008b2dcdde577a824ac922a11dd4b1f17e9ab8 with a new version of the tool by just updating ot master locally. I will still need a new release so the CI/CD pipeline works :) I'll check IE11 to see how it affected the icons there and report back!

**Comment by prologic** [comment]
Seems the icons don'y really work very well in IE11 (_still_) even with the updated tooling.

<img width="624" alt="Screen Shot 2020-09-01 at 22 20 59" src="https://user-images.githubusercontent.com/1290234/91850820-885e6980-eca1-11ea-868f-ba2f3a6ad048.png">

**Comment by tdewolff** [comment]
Ok I'll take a look with a virtual machine

**Comment by tdewolff** [comment]
I see the issue aswell in IE11, it looks like it uses `#0000` instead of `transparent` to display the `background-color`. This doesn't happen on the latest version of `minify` and might be related with the fact that `make deps` is downloading minify v1 instead of v2, you need to use `github.com/tdewolff/minify/v2/...` to prevent that. Does using v2 or `master` fix this?

**Comment by prologic** [comment]
Let me try and report back!

**Comment by prologic** [comment]
Hmmm I didn't realise you had a v2 of this tool, I tried to update to it with:

```#!console
go get -u github.com/tdewolff/minify/v2/cmd/...
```

But re-generating the bundles produces no differences. Am I missing something?

**Comment by prologic** [comment]
Actually I _feel rather stupid here or Go still doesn't support `go get package/cmd/...`  __specific__ version? How do you do this!? 😳

**Comment by prologic** [comment]
I just tried to build from a Git checkout and install the tool:

```#!console
prologic@Jamess-iMac
Wed Sep 02 17:14:27
~/Contributions/minify
 (master) 0
$ git id
da67d20
prologic@Jamess-iMac
Wed Sep 02 17:14:28
~/Contributions/minify
 (master) 0
$ go install ./cmd/minify/...
```

And in my project:

```#!console
prologic@Jamess-iMac
Wed Sep 02 17:15:22
~/Projects/jointwt/twtxt
 (master) 0
$ command -v minify
/Users/prologic/go/bin/minify
prologic@Jamess-iMac
Wed Sep 02 17:15:24
~/Projects/jointwt/twtxt
 (master) 0
$ minify --version
minify built from source
prologic@Jamess-iMac
Wed Sep 02 17:15:28
~/Projects/jointwt/twtxt
 (master) 0
$ make generate
prologic@Jamess-iMac
Wed Sep 02 17:15:30
~/Projects/jointwt/twtxt
 (master) 0
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Makefile

no changes added to commit (use "git add" and/or "git commit -a")
```

Still produces no difference in the generate bundled files. So the IE11 bug remains 🤔

**Comment by tdewolff** [comment]
Just to make sure, can you download the binary from GitHub of v2.9.3 and use that binary. `minify --version` should then give you `minify v2.9.3`. Using that binary, can you go to `internal/static/css` in either `master` or `minify_css_js_assets` and execute `minify -o twtxt.min.css --verbose --bundle 01-pico.css 02-icss.css 03-icons.css 99-twtxt.css`. This must give you a different `twtxt.min.css` where there should be no `background-color:#0000`.

**Comment by prologic** [comment]
Looks like I already have this updated to the tool and minified/combined css bundle:

```#!console
(⎈ |netdata-production:infra)
prologic@Jamess-iMac
Tue Sep 15 02:40:59
~/Projects/jointwt/twtxt/internal/static/css
 (master) 0
$ /Users/prologic/Downloads/minify -o twtxt.min.css --verbose --bundle 01-pico.css 02-icss.css 03-icons.css 99-twtxt.css
infer mimetype from file extensions
minify to output file twtxt.min.css
(1.378439ms,  56 kB,  42 kB,  75.7%,  41 MB/s) - (01-pico.css + 02-icss.css + 03-icons.css + 99-twtxt.css) to twtxt.min.css
finished in 1.586742ms
(⎈ |netdata-production:infra)
prologic@Jamess-iMac
Tue Sep 15 02:41:11
~/Projects/jointwt/twtxt/internal/static/css
 (master) 0
$ git st .
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(⎈ |netdata-production:infra)
prologic@Jamess-iMac
Tue Sep 15 02:41:14
~/Projects/jointwt/twtxt/internal/static/css
 (master) 0
$ sift 'background-color:#0000'
```

Does this match your expectations?

**Comment by tdewolff** [comment]
Sounds good to me! Does it work well in your browsers?

**Comment by prologic** [comment]
> Sounds good to me! Does it work well in your browsers?

Yeah no it still looks terrible in IE11 :/ I'm really not sure why :) Did you manage to get an IE11 VM? I got it off MS's developer site [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) maybe you can see what's going on?

**Comment by tdewolff** [comment]
I did manage to get IE11 in my VM and it worked well. Can you please look at the CSS code for the element that is bad (Inspect Element in IE11)?

**Comment by prologic** [comment]
<img width="580" alt="Screen Shot 2020-09-17 at 15 00 15" src="https://user-images.githubusercontent.com/1290234/93422170-8548b780-f8f6-11ea-9f0e-937cf74bb5a4.png">

What am I looking for again? 😀

**Comment by prologic** [comment]
Vs Chrome (_which is correct_):

<img width="752" alt="Screen Shot 2020-09-17 at 15 02 41" src="https://user-images.githubusercontent.com/1290234/93422330-e3759a80-f8f6-11ea-9b43-e572e592c12c.png">
<img width="1268" alt="Screen Shot 2020-09-17 at 15 02 48" src="https://user-images.githubusercontent.com/1290234/93422338-e83a4e80-f8f6-11ea-9218-8e47ed24245a.png">
