### ISSUE TITLE
E-notation on values of 1000 or multiples thereof

### ISSUE THREAD

**Issue by LittleRedRavingHood** [tdewolff/minify#323]
Minify appears to be altering values of 1000 to be represented in e notation (1e3). This can be easily demonstrated with the following command:

`echo ".test{width:1000px;max-width:1200px;margin:100px}.element1000em{width:1000rem;}.element-1000px{width:1000em;}" |minify --type css`

The output is as follows:

`.test{width:1e3px;max-width:1200px;margin:100px}.element1000em{width:1e3rem}.element-1000px{width:1e3em}`

The issue also applies to multiples of 1000, as in:

`.test{width:1e3px;max-width:1200px;margin:100px}.element1000em{width:1e4rem}.element-1000px{width:2e3em}`

**Comment by tdewolff** [comment]
I don't see what the issue is, this is working as expected. `1e3` are three characters while `1000` are four, so it is minifying as it should. What am I missing?

**Comment by LittleRedRavingHood** [comment]
> I don't see what the issue is, this is working as expected. `1e3` are three characters while `1000` are four, so it is minifying as it should. What am I missing?

The issue is that e notation is not W3C compliant.
![image](https://user-images.githubusercontent.com/70355835/91648102-cba0b880-eaa6-11ea-880d-0177161cfaae.png)

**Comment by tdewolff** [comment]
That is funny, because it is specifically allowed in https://drafts.csswg.org/css-syntax-3/#number-token-diagram. In CSS2 it seems to be prohibited to use scientific notation of numbers (https://www.w3.org/TR/CSS2/syndata.html#value-def-number), but this is weird as you are using a CSS3 validator. Furthermore, it seems that a couple of major browsers allow the scientific notation. Maybe I'm missing something in the spec?

**Comment by LittleRedRavingHood** [comment]
I agree with you, and realistically, it doesn't appear to impact the outcome on the major browser platforms (as you stated). My only concern is that sites exhibiting this anomaly could be marked down when being assessed for SEO or search engine ranking. Not really a big deal but it could impact some people.

Personally, I just have a workaround using sed inline, as that's how I've architected my current solution. Might not be so easy for other situations. I would certainly not mark this as a high priority, but thought it was worth mentioning.

Thank you for your great work by the way, it's much appreciated.

**Comment by tdewolff** [comment]
Thanks for the kind words, and thanks for bringing this to my attention! I'll take a deeper look when I have a bit more time.

**Comment by tdewolff** [comment]
You can actually use decimal notation instead of exponential notation using the `KeepCSS2` flag. This is by default disabled but I think I'd like to enable it by default. The CSS3 scientific notation is still a candidate recommendation and not an official specification.
