### ISSUE TITLE
The CLI minifier segfaults on anything create by Deno bundle

### ISSUE THREAD

**Issue by dschissler** [tdewolff/minify#324]
`Linux host 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Using `v2.9.0` amd64 release binary from github.

First generate a bundle with `deno bundle input.ts output.js`.  The bundle works in the browser but minify cannot process it.  Even something as simple as a hello world console log.  It begins to output javascript to stdout and then it segfaults.

Steps to ultimate life failure:

1) Create a `console.log('Hello world')` named `input.ts`.
2) Run `deno bundle input.ts output.js`
3) Run `minify output.js`

**Comment by tdewolff** [comment]
Could you post the contents of `output.js` please? That will help me track down the problem. By the way, calling `minify output.js` will output to stdout, if you want to overwrite the file you have to say so explicitly: `minify -o output.js output.js`

**Comment by dschissler** [comment]
Ok, I was just about to post the contents now.  This one is just incredibly easy to reproduce.  A rare bug indeed ;).

**Comment by tdewolff** [comment]
Thanks for the bug report! I'll release a new version (very) soon!

**Comment by tdewolff** [comment]
Released in v2.9.1, thanks!
