### ISSUE TITLE
v2.9.1 breaks some JS

### ISSUE THREAD

**Issue by JRaspass** [tdewolff/minify#325]
Take the following function to compute the length in chars of a string in JavaScript taken from https://mths.be/punycode

```javascript
function strlen(str) {
    let i = 0, len = 0;

    while (i < str.length) {
        const value = str.charCodeAt(i++);

        if (value >= 0xD800 && value <= 0xDBFF && i < str.length) {
            // It's a high surrogate, and there is a next character.
            const extra = str.charCodeAt(i++);

            // Low surrogate.
            if ((extra & 0xFC00) == 0xDC00) {
                len++;
            } else {
                // It's an unmatched surrogate; only append this code unit, in case the
                // next code unit is the high surrogate of a surrogate pair.
                len++;
                i--;
            }
        } else {
            len++;
        }
    }

    return len;
}
```

Under v2.9.0 this minified to:
```javascript
function strlen(b){let a=0,c=0;while(a<b.length){const d=b.charCodeAt(a++);if(d>=55296&&d<=56319&&a<b.length){const d=b.charCodeAt(a++);(d&64512)==56320?c++:(c++,a--)}else c++}return c}
```

Under v2.9.1 it now minifies to:
```javascript
function strlen(b){for(let a=0,c=0;a<b.length;){const d=b.charCodeAt(a++);if(d>=55296&&d<=56319&&a<b.length){const d=b.charCodeAt(a++);(d&64512)==56320?c++:(c++,a--)}else c++}return c}
```

And when invoked you get the following error about `c` not being defined:
```
Uncaught ReferenceError: c is not defined
```

Notice how the scope of `c` has gone from function scope to for loop scope, I suspect 436c1b1 is to blame? Making the let's be vars would probably fix it.

**Comment by JRaspass** [comment]
Side note, `extra` which became the second `d` could be inlined, as it only has one use. I believe it's only written like that for clarity I would expect a minifier to inline it.

**Comment by tdewolff** [comment]
That was a sloppy bug, thanks for the report. With respect to inline singly-used variables, it's on the TODO list together with removing unused variables. Good idea!

**Comment by tdewolff** [comment]
See v2.9.2 for the fix and let me know if that works for you.

**Comment by JRaspass** [comment]
v2.9.2 seems to work perfectly, thanks!
