### ISSUE TITLE
CSS: translating linear-gradient to 'transparent'

### ISSUE THREAD

**Issue by artemkonev** [tdewolff/minify#327]
Hi,

I've ran into the following issue that I think is maybe a bug. When minifying this CSS property with v.2.9.4:

``linear-gradient(to top,white,rgba(255,255,255,0))``

I get the following:

``linear-gradient(to top,white,transparent)``

The specification (https://www.w3.org/TR/css-color-4/#transparent-color) says the following:

    The keyword transparent specifies a transparent black. It is a type of <named-color>.
    For easy reference in other specifications, opaque black is defined as the color rgb(0 0 0 / 100%); transparent black is the same color, but fully transparent—i.e. rgb(0 0 0 / 0%).

Also, an earlier specification (https://www.w3.org/TR/css-color-3/#transparent-def) defines it as follows:

    transparent
    Fully transparent. This keyword can be considered a shorthand for transparent black, rgba(0,0,0,0), which is its computed value.

The resulting (undesired) effect looks like this (grey bars):

<img width="393" alt="Screenshot 2020-09-07 at 15 22 57" src="https://user-images.githubusercontent.com/41629299/92412710-d3b2c500-f144-11ea-830d-4055525c3535.png">

**Comment by tdewolff** [comment]
You are right, thanks for reporting the issue and the detailed report! Will push out a new version soon.
