### ISSUE TITLE
Commit 6242e8846252b4f6bb53739970b85ea969b244f8 breaks Semantic UI CSS

### ISSUE THREAD

**Issue by vizvayu** [tdewolff/minify#329]
The commit 6242e8846252b4f6bb53739970b85ea969b244f8 brakes the Semantic UI CSS file (both the regular and the pre-minified version).

I can use the latest version of minify and if I revert that particular commit, the CSS works just fine.

You can check it by downloading Semantic UI from https://github.com/Semantic-Org/Semantic-UI-CSS/archive/master.zip

I'm honestly not sure if this is a problem with minify or with semantic UI, but I do know that when using any of the CSS files from the Semantic repository everything works fine.

Thanks and let me know if there's any other test I can do to help you figure this out.

**Comment by tdewolff** [comment]
Thanks for the bug report, can you tell me which browser and OS you're using? In what way does it brake, what error or glitch do you see?

**Comment by vizvayu** [comment]
I'm using Opera (Chromium) under Windows 8. It doesn't throw any errors; but the whole layout of the page appears broken. Almost like if the Semantic CSS file was missing. I tested it clearing the cache and in incognito mode as well, and it consistently shows the same result when applying minify to the Semantic CSS file. If I revert that particular commit, everything works perfectly fine again. I was initially using minify 2.7.6 and never had any problems, but yesterday updated it to the latest version and noticed this issue.

**Comment by tdewolff** [comment]
Thanks for that, took a look and it wasn't encoding `\t`, `\r` and `\n` characters. I will push out a new release soon with this fix.

**Comment by vizvayu** [comment]
Awesome! Thank you very much!
