### ISSUE TITLE
title="" shouldn't be removed

### ISSUE THREAD

**Issue by coliff** [tdewolff/minify#331]
I noticed that (using Hugo 75) the input:
`<input title="" required>`
is minified to:
`<input required>`
This has the unexpected side effect of removing the empty title which is actually useful as it prevents the browsers default 'Please fill in this field.' tooltip from displaying when hovering over an input with the `required` attribute. It would be good if  `title=""` wasn't removed.

**Comment by tdewolff** [comment]
Thanks for the issue! According to https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute it is stated:

> If this attribute is omitted from an element, then it implies that the title attribute of the nearest ancestor HTML element with a title attribute set is also relevant to this element. Setting the attribute overrides this, explicitly stating that the advisory information of any ancestors is not relevant to this element. Setting the attribute to the empty string indicates that the element has no advisory information.

In other words, you're right. Setting an empty `title` is relevant and this is a bug, I'll work on a fix soon!

**Comment by tdewolff** [comment]
Should be fixed, I'll push out a new version soon!
