### ISSUE TITLE
Unintended consequence of minifying 'none' to '0 0' in box-shadow property

### ISSUE THREAD

**Issue by ogham** [tdewolff/minify#332]
I saw in the README that minify will re-write CSS `none` to `0` for the `border` properties, but this has unexpected side-effects with the `box-shadow` property when using CSS transitions.

In my CSS, I had the equivalent of this:

```css
.box {
    box-shadow: none;
}
```

minify v2.9.4 re-wrote the `none` to `0 0`:

```css
.box{box-shadow:0 0}
```

Unfortunately, this doesn't do _exactly_ the same thing! The first one sets the shadow size to 0 and the colour to `transparent`, but the second one sets _only_ the size, leaving the colour:

> treating `none` as a zero-item list and appending blank shadows (`transparent 0 0 0 0`)
> ...
> If the `color` is absent, it defaults to `currentColor`.
> — https://drafts.csswg.org/css-backgrounds/#the-box-shadow

Which means that even though the two pieces of CSS have the same effect on a _static_ page, animating through the properties with a CSS transition means that you can see the shadow fade through the colour during the transition. This took me by surprise too.

I put together [a JSFiddle](https://jsfiddle.net/syo5k64j/1/) demonstrating the effect. In both the browsers I tested it on (Safari and Firefox), you see blue during the transition when hovering over the second box, but not the first.

I'm able to work around this by using `transparent 0 0` instead of `none`. Thanks for making minify!

**Comment by tdewolff** [comment]
Thank you so much for the detailed report, should be fixed now! A new version will be pushed out soon.
