### ISSUE TITLE
Bug in minification of inline arrow functions returning maps

### ISSUE THREAD

**Issue by JRaspass** [tdewolff/minify#333]
I have the following snippet of code for making a value => label map from a select element:
```javascript
console.log([...document.querySelector('select').options].reduce(
    (acc, cur) => ({ ...acc, [cur.value]: cur.label }), {}));
```

Minify removes the parens and produces this:
```javascript
console.log([...document.querySelector('select').options].reduce((b,a)=>{...b,[a.value]:a.label},{}))
```

The lack of parens around the returned map cause the braces to be interpreted as a block and the parser to complain about the spread operator now being outside of an array or map:
```
Uncaught SyntaxError: expected expression, got '...'
```

**Comment by JRaspass** [comment]
Looks like it can be golfed to this:

```javascript
console.log((() => ({ foo: "bar" }))());
```

Expected
```
Object { foo: "bar" }
```

Got
```
undefined
```

**Comment by tdewolff** [comment]
Thanks for the report, will work on a fix soon!

**Comment by TropicalPenguin** [comment]
Probably related, I'm also seeing:

`(a, b) => { return { start: a, end: b }; };`

improperly being minified to:

`(a,b)=>{start:a,end:b}`

Without thorough investigation, I haphazardly tried removing the -1 from https://github.com/tdewolff/minify/blob/1bd30d887a9f05f203ffecf8d6c9d087a17b42e8/js/js.go#L604 ... which fixed the immediate problem... but probably breaks something else.

**Comment by tdewolff** [comment]
Thanks guys, pushed a fix and will release a new version very soon!
