### ISSUE TITLE
Feature Request: Preserve Line breaks for CSS minification

### ISSUE THREAD

**Issue by coliff** [tdewolff/minify#337]
I think it'd be useful to have an option to preserve line breaks for minifying CSS. This helps when diffing between CSS files.

**Comment by tdewolff** [comment]
Hi @coliff thanks for the request. While it might be useful in your case, I don't think this is in the scope of these minifiers. They are purely meant to be minifiers and not beautifiers nor code arrangers.

What I do in cases like yours is either run it through a beautifier online, or by running a search and replace and replacing `;`, `{`, and `}` by `;<NL>`, `{<NL>`, and `}<NL>` respectively, where `<NL>` is a newline character. I hope this helps!

**Comment by coliff** [comment]
No problem - thanks for the reply and suggestion on the search/replace.  👍
