### ISSUE TITLE
CSS Invalid Property Value 

### ISSUE THREAD

**Issue by kokizzu** [tdewolff/minify#34]
Got a CSS `Invalid Proprty Value` error on Chrome after minifying:

Minify result `    z-index: 1e3;`
original value `1000`.

**Comment by tdewolff** [comment]
Good find. This is because `z-index` requires an integer not a length. So do `counter-increment`, `counter-reset`, `orphans` and `windows`. See http://www.w3.org/TR/css-2010/#properties for an old CSS version.

I can only fix this after 2 weeks.
