### ISSUE TITLE
JS: directive "use strict" not reconized by nodejs if after variable declaration

### ISSUE THREAD

**Issue by csystem-it** [tdewolff/minify#343]
Old version of nodejs (haven't yet tested with newer ones) doesn't seem to recognize the "use strict" directive if put after variable declaration.

Right now the javascript minifier when does the variable hoisting, move all the declaration to the top of the scope, before the "use strict"; we should instead put them after.

Right now as a workaround i've commented all call to the function `hoistVars()` declared in vars.go.

**Comment by tdewolff** [comment]
Thanks for the bug report, this should be fixed now. Please let me know if you still run into trouble.
