### ISSUE TITLE
In the for Variable declaration is advanced, resulting in null assignment

### ISSUE THREAD

**Issue by LiuJun0** [tdewolff/minify#346]
source code
```
function getWHIgnoreDisplay() {
    for (var _len = arguments.length, args = Array(_len), _key2 = 0; _key2 < _len; _key2++) {
        args[_key2] = arguments[_key2];
    }
    var val = void 0;
    var elem = args[0];
    if (elem.offsetWidth !== 0) {
        val = 1;
    } else {
        val = 0;
    }
    return val;
}
console.log(getWHIgnoreDisplay(document.body, 'width', 1));
```

After compression:  `Cannot read Variable'elem ' of undefined`

```
function getWHIgnoreDisplay(){for(var _len=arguments.length,args=Array(_len),_key2=0,val=void 0,elem=args[0];_key2<_len;_key2++)args[_key2]=arguments[_key2];return elem.offsetWidth!==0?val=1:val=0,val}console.log(getWHIgnoreDisplay(document.body,'width',1))
```
elem Variable assignments should not be advanced
![image](https://user-images.githubusercontent.com/21070935/96560591-1691bc00-12f1-11eb-8d2f-32debfd1fd75.png)

**Comment by tdewolff** [comment]
Thanks for the report. The problem is that we set `elem` before we assign content to `args` in the for loop. In general we cannot merge var statements with their definitions into the for initializer. I will work on a fix.
