### ISSUE TITLE
Feature idea: Remove unused css classes.

### ISSUE THREAD

**Issue by Alexander-Zierhut** [tdewolff/minify#349]
The following is a feature request and is optional. The minifier is already amazing!

Could it be possible to remove classes from css files that are never used in a given directory? This might save insane amounts of space when using frameworks like Bootstrap. Same with unused javascript functions. 

The first error I could think about is that classes might be set using javascript or javascript function calls generated using Preprocessors like PHP. I could imagine a config file, which would define classes and functions, that would not be removed. Similar to flags passed to a compiler to make it less aggressive.

**Comment by tdewolff** [comment]
That's an excellent idea! This would really improve the compression rate of the minifiers. The only problem is that we have no idea of knowing which classes or functions are used. This is a big problem but it could be solved by building a web minifier that basically compiles a website entirely instead of its files separately. This would be a huge project haha.

**Comment by Alexander-Zierhut** [comment]
> This would be a huge project haha. 

Yeah, that's true 😅 Still wanted to mention it. Maybe sometime in the future!

> The only problem is that we have no idea of knowing which classes or functions are used. This is a big problem but it could be solved by building a web minifier that basically compiles a website entirely instead of its files separately

Exactly! This also includes the problems about generated code I described. Maybe someday. I imagine it to be easier for css then js though.

Thank you again for your work and insanely fast response times!

**Comment by tdewolff** [comment]
I will close this issue for now, but it will definitely be on the roadmap if I decide to put more time in this project. PRs always welcome as usual ;-)

**Comment by Alexander-Zierhut** [comment]
Sounds great!
