### ISSUE TITLE
Minifcation used javascript shorthand in CSS

### ISSUE THREAD

**Issue by dvente** [tdewolff/minify#350]
The minifyer will use exponential notation when minifying css. I have done my best to research but I couldn't find whether that is allowed in CSS. However, it is considered an error by the W3C CSS validator. I'll post a MWE below, but unless it says somewhere it's allowed this should probably be patched. I don't know whether there are any other JS conventions that accidentally make it into the CSS, but it might be possible. 

## MWE
```bash
$ echo "body { margin-right: 100000px;}" > test.css
$ minify test.css --type css
body{margin-right:1e5px}
```

**Comment by tdewolff** [comment]
Hi, please use the `KeepCSS2` flag. Exponential numbers are allowed in (one of the documents of) CSS3, but their support is not so widespread yet. Let me know if that helps!

**Comment by dvente** [comment]
Thank you for the quick response! I wasn't aware that scientific notation was allowed in CSS3. It only came up because the w3 CSS validator flagged it as invalid, however it doesn't state clearly which version of CSS it is checking against, so perhaps that is where the error originated. In any case I will close the issue since this is valid behaviour, sorry for the mistake!
