### ISSUE TITLE
Disable minify for some parts?

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/minify#351]
Are there markers to disabled minify for some sections?
It's removing too much in a very special case - and there are no suitable options to disable the optimization.

**Comment by tdewolff** [comment]
Unfortunately there is no option to disable for some part. Can you please let me know in what situation you'd like to disable the minification? Is there a bug that should be fixed?

**Comment by tcurdt** [comment]
There is a neat css selector trick that requires `<input placeholder=" "`. Of course minify removes that whitespace. But it seems like `<input placeholder="&nbsp;"` works, too. I hope that holds true for all browsers.
But it triggered a general wondering.

**Comment by tdewolff** [comment]
Looks like this is a bug. We should not be trimming whitespace in attribute values for `placeholder` and `value` in case of an `<input type="text">` tag. I wonder for what other tags and attributes we can't trim their whitespaces. When I have that clear I'll push out a fix, thanks for the issue!

**Comment by tdewolff** [comment]
Looks like we were trimming all attribute values, if changed this to be a whitelist of attributes that allow this. Should be fixed now, please let me know if that works for you.
