### ISSUE TITLE
Bug: translate="no" is minified incorrectly

### ISSUE THREAD

**Issue by coliff** [tdewolff/minify#352]
Hi. I think I found a bug. With Hugo 0.78.2 and minify HTML option enabled (default minification settings), it minifies the following:

```html
<h1 translate="no">Navigation</h1>
```

to:

```html
<h1 translate>Navigation</h1>
```

which doesn't work as expected. Translate="no" is a HTML5 attribute and is used on the new Safari to tell the browser not to auto-translate a particular div/span etc. - useful for product/brand names etc.
REF: https://html.spec.whatwg.org/multipage/dom.html#the-translate-attribute

I hope this could be fixed so that it'd be minified to:

```html
<h1 translate=no>Navigation</h1>
```

**Comment by tdewolff** [comment]
Thanks! This should be fixed, please let me know if you still run into trouble.
