### ISSUE TITLE
SSI tags support

### ISSUE THREAD

**Issue by muspelheim** [tdewolff/minify#353]
Hello, seems like this library doesn't support SSI tags. There is no option to skip the comments inside the codebase.

common SSI tag looks like:
```
<!--# SSI Tag -->
<!--# var VARIABLE_NAME="xxx" -->
<!--# echo DOCUMENT_NAME-->
<!--# GET var/val="ATTRIBUTE_NAME" "INDEX_LIST" -->
```

More examples here: https://www.webnms.com/cagent/help/http/c_http_ssi.html

It would be great if this library will support this feature.

**Comment by tdewolff** [comment]
Done, thanks for the suggestion!
