### ISSUE TITLE
JS: Arrow function with a single destructured parameter results in invalid code

### ISSUE THREAD

**Issue by sjohannes** [tdewolff/minify#358]
Input: `({x,y,z})=>x+y+z`
Output: `{x:a,y:b,z:c}=>a+b+c`

Input: `([x,y,z])=>x+y+z`
Output: `[a,b,c]=>a+b+c`

Both outputs are invalid JS (tested with minify 2.9.10).

**Comment by tdewolff** [comment]
Thanks for the bug report, let me know if that fixes it! ;-)
