### ISSUE TITLE
JS: Object destructuring assignment without var/let/const results in invalid code

### ISSUE THREAD

**Issue by sjohannes** [tdewolff/minify#359]
The following is correctly minified:

Input: `const {x, y, z} = {x: 1, y: 2, z: 3}`
Output: `const{x,y,z}={x:1,y:2,z:3}` (correct)

If we don't want the `const` declaration, the whole assignment needs to be parenthesized ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assignment_without_declaration)). Here minify outputs invalid code:

Input: `({x, y, z} = {x: 1, y: 2, z: 3})`
Output: `({x,y,z})={x:1,y:2,z:3}` (incorrect)

Tested with minify 2.9.10.

**Comment by tdewolff** [comment]
Thanks again for the report! Please let me know if this fixes it for you and whether you find any new bugs.

**Comment by sjohannes** [comment]
Thank you; both this and #358 are resolved in the latest revision.

I've been playing around with similar constructs and haven't found any other issues. Happy to report that these also work perfectly:

| Code                    | minify 2.9.10                 | minify latest               |
|-------------------------|-------------------------------|-----------------------------|
| `({x} = {x: 1}); y = 2` | `({x})={x:1},y=2` (incorrect) | `({x}={x:1},y=2)` (correct) |
| `y = 2; ({x} = {x: 1})` | `y=2,{x}={x:1}` (correct)     | `y=2,{x}={x:1}` (correct)   |
