### ISSUE TITLE
cmd seems could not  build

### ISSUE THREAD

**Issue by terryh** [tdewolff/minify#36]
# github.com/tdewolff/minify/svg
../svg/table.go:19: undefined: svg.Fill
../svg/table.go:20: undefined: svg.Stroke
../svg/table.go:21: undefined: svg.Stop_Color
../svg/table.go:22: undefined: svg.Flood_Color
../svg/table.go:23: undefined: svg.Lighting_Color
FAIL	github.com/tdewolff/minify/html [build failed]

**Comment by Knorkebrot** [comment]
Maybe it's time to use some kind of CI, like [Travis][tr] or [Drone][dr], they're both free for open source. Unfortunately Drone seems to lack a current version of Go, so I guess Travis would be the better choice here.

[tr]: http://docs.travis-ci.com/user/languages/go/
[dr]: http://docs.drone.io/quickstart.html

**Comment by denji** [comment]
Travis is the better he can test simultaneously on Linux and OSX machines.

**Comment by tdewolff-rug** [comment]
I will look into Travis, but in the meantime I'll use a separate branch for new development

**Comment by tdewolff** [comment]
I will look into Travis, but in the meantime I'll use a separate branch for new development
