### ISSUE TITLE
New problem, getting WARNING: --recursive not specified

### ISSUE THREAD

**Issue by spekary** [tdewolff/minify#361]
My scripts just started breaking with this error:

WARNING: --recursive not specified, omitting directory ../../../deploy/server/assets/goradd/js/

The command line is:
minify -o ../../../deploy/server/assets/goradd/js/ ../../../deploy/server/assets/goradd/js

I essentially am minifying into the same directory. But, when I remove the output path, I get the same error. Seems like it is having some trouble with the .. in the path.

This is running on Mac OS.

I recently upgraded minify.

**Comment by tdewolff** [comment]
Please specify `--recursive` (or `-r`) to fix the warning. The minifier needs to be called explicitly with recursiveness when minifying directories (similar to how `cp` works). Let me know if that fixes it for you!

**Comment by spekary** [comment]
But I don't want it to be recursive. I only want to minify the files at that level.

**Comment by tdewolff** [comment]
Good point, I'll see how I can work that in, and get back to you soon!

**Comment by tdewolff** [comment]
In that case you should use the `*` bash expansion, as in:

```
minify -o ../../../deploy/server/assets/goradd/js/ ../../../deploy/server/assets/goradd/js/*
```

Bash will automatically expand that to include all files in that directory, and minify will minify those files and overwrite them. Please let me know if that works well for you.

**Comment by hexabyte23** [comment]
hello,

Could you change doc accordingly:

`minify -o out/ .*` instead of `minify -o out/ .`

It's a bit confusing for newbie :-)
thanks

**Comment by tdewolff** [comment]
Thanks, I've updated the readme!

**Comment by tdewolff** [comment]
This appears to be solved, if not please reopen!
