### ISSUE TITLE
HTML: <script>

### ISSUE THREAD

**Issue by zhixuan666** [tdewolff/minify#363]
when i run ```minify.exe -r -s -o ./test ./public/```

before
```html
<script class="page-configurations">
  CONFIG.page = {
    sidebar: "",
    isHome : true,
    isPost : false,
    lang   : 'zh-CN'
  };
</script>
```

after
```html
<script class=page-configurations>CONFIG.page={sidebar:"",isHome:!0,isPost:!1,lang:'zh-CN'}</script>
```

It is missing ```;```

**Comment by tdewolff** [comment]
The semicolon `;` is not required at the end of a file in JavaScript. This should work fine as it is, in what way is this causing a problem for you?

**Comment by zhixuan666** [comment]
It's will be err
![image](https://user-images.githubusercontent.com/59254886/102082350-28a55c00-3e55-11eb-8804-cbd53792cace.png)

**Comment by tdewolff** [comment]
There is no arrow function parameter list in your example, so something else is going wrong. Can you be more explicit and how to reproduce?

**Comment by zhixuan666** [comment]
before
https://github.com/zhixuan666/zhixuan666.github.io/tree/master

after
https://github.com/zhixuan666/zhixuan666.github.io/tree/fcdccd49fa3ff4f8e9cefd5cfe1e04c2d028e5b4
