### ISSUE TITLE
svg minification breaks certain images

### ISSUE THREAD

**Issue by m-rei** [tdewolff/minify#365]
Example, original SVG:
```
<svg role="img" viewBox="0 0 24 24">
    <path d="M23.499 6.203a3.008 3.008 0 00-2.089-2.089c-1.87-.501-9.4-.501-9.4-.501s-7.509-.01-9.399.501a3.008 3.008 0 00-2.088 2.09A31.258 31.26 0 000 12.01a31.258 31.26 0 00.523 5.785 3.008 3.008 0 002.088 2.089c1.869.502 9.4.502 9.4.502s7.508 0 9.399-.502a3.008 3.008 0 002.089-2.09 31.258 31.26 0 00.5-5.784 31.258 31.26 0 00-.5-5.808zm-13.891 9.4V8.407l6.266 3.604z"/>
</svg>
```
![original](https://user-images.githubusercontent.com/18645499/102806223-bb497c00-43bc-11eb-8322-55e061e82fd5.png)

minified & broken:
```
<svg role="img" viewBox="0 0 24 24">
	<path d="M23.499 6.203c-1.87-.501-9.4-.501-9.4-.501s-7.509-.01-9.399.501c1.869.502 9.4.502 9.4.502s7.508.0 9.399-.502zm-13.891 9.4V8.407l6.266 3.604z"/>
</svg>
```
![broken](https://user-images.githubusercontent.com/18645499/102806221-bab0e580-43bc-11eb-97cb-39ef04121047.png)

minifcation has been added the way it was recommended in the [usage](https://github.com/tdewolff/minify#usage) section
`m.AddFunc("image/svg+xml", svg.Minify)`

**Comment by tdewolff** [comment]
Thanks for the bug report! Which version are you using? I'm getting the following output with the current version of `minify`:

```
<svg role="img" viewBox="0 0 24 24"><path d="M23.499 6.203A3.008 3.008.0 0021.41 4.114c-1.87-.501-9.4-.501-9.4-.501s-7.509-.01-9.399.501a3.008 3.008.0 00-2.088 2.09A31.258 31.26.0 000 12.01a31.258 31.26.0 00.523 5.785 3.008 3.008.0 002.088 2.089c1.869.502 9.4.502 9.4.502s7.508.0 9.399-.502a3.008 3.008.0 002.089-2.09 31.258 31.26.0 00.5-5.784 31.258 31.26.0 00-.5-5.808zm-13.891 9.4V8.407l6.266 3.604z"/></svg>
```

Which is showing up correct for me.

**Comment by m-rei** [comment]
these are the ones that were automatically added to my mod file:

    
	github.com/tdewolff/minify v2.3.6+incompatible
	github.com/tdewolff/parse v2.3.4+incompatible // indirect
	github.com/tdewolff/test v1.0.6 // indirect

**Comment by tdewolff** [comment]
You'll need to import `github.com/tdewolff/minify/v2` instead! Note the `v2` at the end, same for `parse`

**Comment by m-rei** [comment]
Oh, I was relying on Go to pull the latest ones... didn't even notice that! You even explicitly stated it in [installation](https://github.com/tdewolff/minify#installation), now that I read it. I'm so used to just copying the url and skimping over the docs, sry, my bad!

Anyway, I updated it to v2 and now it works. Great project btw.!

**Comment by tdewolff** [comment]
Thanks! Good to hear you enjoy it. Please let me know if you run into other issues! ;-)
