### ISSUE TITLE
HTML Minifier not compatible with Server-Side Rendered React

### ISSUE THREAD

**Issue by siosphere** [tdewolff/minify#366]
When using SSR (Server-Side Rendering) with React, the markup will contain empty comments:
```
<div>Some text token <!-- -->some variable</div>
```

When hydrating on the client-side, it uses these empty comments to build the proper JS DOM tree. Currently, when the server rendered result is passed through minification, these are removed, and the client-side will issue a warning:
```
Warning: Text content did not match. Server: "Some text token some variable" Client: "Some text token "
    in div (created by EmptyApp)
```

This causes the client to have to re-render the app, instead of hydrating efficiently.

There should be an option to preserve all comments, not just conditional comments.

**Comment by tdewolff** [comment]
Thanks! Does that work for you?

**Comment by siosphere** [comment]
> Thanks! Does that work for you?

Looks like that should do the trick! I'll test it out in this next week, but not expecting issues. Thanks for getting that in there so quickly.
