### ISSUE TITLE
SVG renders differently after minify

### ISSUE THREAD

**Issue by loveleif** [tdewolff/minify#367]
The following snippet renders differently after minifying:

```html
<div style="width: 100%; height: 2rem;">
  <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 46.113 46.113">
    <path d="M46.113 0L0 46.114h46.113z"/>
  </svg>
</div>
```

Before:

![test-svg](https://user-images.githubusercontent.com/429963/104158464-b2f9c500-53ed-11eb-8d36-9504cd32362f.png)

After minify:

![test-svg-minified](https://user-images.githubusercontent.com/429963/104158465-b3925b80-53ed-11eb-90ce-4528d9821de5.png)

**Comment by moorereason** [comment]
More details in https://github.com/gohugoio/hugo/issues/8129.

**Comment by tdewolff** [comment]
Thanks for the issue! The `<svg>` element puts the width and height by defaults at `auto`, which equals `100%`. Strangely, the behaviour for `auto` and `100%` is different. I will look into this. Mean while, does your CSS give a different value for width/height for svgs in your case? The default should be `100%`, so something must be changing it.

**Comment by moorereason** [comment]
Given:

```html
<html><body>

<p>100%</p>
<div style="width: 100%; height: 2rem; border: 1px solid red">
  <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 46.113 46.113">
    <path d="M46.113 0L0 46.114h46.113z" stroke="red"/>
  </svg>
</div>

<p>no-attr</p>
<div style="width: 100%; height: 2rem; border: 1px solid green">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46.113 46.113">
    <path d="M46.113 0L0 46.114h46.113z" stroke="green"/>
  </svg>
</div>

<p>auto</p>
<div style="width: 100%; height: 2rem; border: 1px solid blue">
  <svg xmlns="http://www.w3.org/2000/svg" width="auto" height="auto" viewBox="0 0 46.113 46.113">
    <path d="M46.113 0L0 46.114h46.113z" stroke="blue"/>
  </svg>
</div>

</body></html>
```

I tested this in windows/amd64 Chrome, FF, IE Edge, and IE11:

* Red (100%) - renders **correctly** in all browsers (this will be the definition of "correct" below)
* Green (no-attr) - renders **incorrectly** in all browsers except IE11.
* Blue (auto) - renders correctly in all browsers **except** FF.

**Comment by loveleif** [comment]
> Mean while, does your CSS give a different value for width/height for svgs in your case?

No, as moorereason kindly pointed out above, browsers make a difference between 100% and no width/height attributes by default.

**Comment by tdewolff** [comment]
Thanks for the in-depth test! I've added a fix to keep all values of `width` and `height` for the `<svg>` tag. Let me know if you run into any other trouble.

**Comment by moorereason** [comment]
Thanks, @tdewolff.  I'll watch for a new release of minify, but Hugo is still lagging behind on minify releases.
