### ISSUE TITLE
JS: debugger keyword removed

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#370]
Using minify v2.9.11, code:

```js
function assert(assertion) {
  if (!assertion) {
    debugger;
  }
}
```

is minified to:

```js
function assert(a){if(!a)}
```

`Uncaught SyntaxError: expected expression, got '}'`

**Comment by tdewolff** [comment]
I've fixed the syntax error it generated, but still using the original assumption that `debugger` statements are not desired in final production code (and you shouldn't minify non-production code I think!). Do you think people want to keep debugger symbols for some reason?

**Comment by jpodeszfa** [comment]
I agree that `debugger` statement is not desired in final production code but I think that minifiers should not change the logic of code, and in this example the function `assert` stops working as intended.

Google closure compiler does not remove `debugger` (with `--compilation_level=SIMPLE`):

```js
function assert(a){if(!a)debugger}
```

**Comment by tdewolff** [comment]
Good point, `debugger` statements are now kept!
