### ISSUE TITLE
cmd tool: js spread operator error (not supported?)

### ISSUE THREAD

**Issue by sgon00** [tdewolff/minify#373]
Is js spread operator not supported? I met the following error:

```
$ wget https://unpkg.com/vue@3.0.5/dist/vue.global.js
$ minify -o test.js vue.global.js 
ERROR: cannot minify vue.global.js: expected ) instead of ... in arguments on line 1283 and column 49
 1283: ...= 0 ? [] : [`\n`]), ...formatTraceEntry(e...
```

Btw, I am using the latest minify cmd tool go installed from git clone source at the time I am posting this issue.
Thank you very much.

**Comment by tdewolff** [comment]
Thanks for the report! The spread operator is supported, but only if at the end. In this case we have something like `f(...a, ...b)`, which is a case that I wasn't aware of. I will implement a fix soon!
