### ISSUE TITLE
function statement requires a name

### ISSUE THREAD

**Issue by ltheinrich** [tdewolff/minify#375]
```
let valid_login = false;

export function set_valid_login(valid) {
    valid_login = valid;
}
```
is minified to
`let valid_login=!1;export function(a){valid_login=a}`

That does not work in Firefox `Uncaught SyntaxError: function statement requires a name`

**Comment by ltheinrich** [comment]
Version 2.8.0 works fine, this bug exists since 2.9.0.

**Comment by tdewolff** [comment]
Thanks for the report! Should be fixed now, I'll bring out a new version soon!
