### ISSUE TITLE
"use strict" test fails after minify

### ISSUE THREAD

**Issue by spekary** [tdewolff/minify#376]
Starting with this code:
```
if (!function () {
    "use strict";
    return Function.prototype.bind && XMLHttpRequest && !this;
}()) {
    document.write("This browser is not supported. Try a different browser.");
}
```
It is minified to this:
```
(function(){return"use strict",Function.prototype.bind&&XMLHttpRequest&&!this})()||document.write("This browser is not supported. Try a different browser.")
```

This code works properly not minified, but fails after being minified, always reporting that the brower is not supported. This appears to be a recently introduced problem, this code worked for quite some time until I updated minify. Version I am running is v2.9.12-2-gb5f25ca

**Comment by tdewolff** [comment]
Thanks! I've added proper `"use strict"` support now, I'll release a new version soon!
