### ISSUE TITLE
Strict equality (===) gets minified to loose equality (==)

### ISSUE THREAD

**Issue by Lukasz032** [tdewolff/minify#378]
Minified the strict-mode valid JS code containing strict comparisons. Got the version with all strict equality operators (`a === b`) rewritten as loose equality operators (`a==b`).

This is not desired nor even expected. Loose comparisons sometimes pose a security risk, for example when comparing `null`, `undefined` or `''` to integer 0. When the original code use strict comparisons, they have to remain strict even after minifying, especially in `"use strict"` code.

**Comment by tdewolff** [comment]
I understand the difference between strict and loose equality (and inequality) in JS, but can you show me an example that is not working as expected? In particular, `a === b` should never be minified to `a==b`, but `typeof a === "int"` should be minified to `typeof a=="int"` (where `typeof` can be on the left or right). That is the only case currently considered for converting `=== -> ==` and `!== -> !=`, I'm happy to hear about other possibilities though.

**Comment by Lukasz032** [comment]
That may be the case, but I'll investigate this further just to be sure.

To clarify, I used Windows binary here. Minifier is a part of bigger CI process, which substitutes `require()` with appropriate module exports, minifies the result and then runs ESLint on it. It was ESLint that complained.

**Comment by tdewolff** [comment]
Can you please show what the error in ESLint was, and to what line it applied?

**Comment by Lukasz032** [comment]
`error: Expected '===' and instead saw '=='.`

```js
"use strict";typeof HTMLCollection.prototype.forEach=="undefined"&&(HTMLCollection.prototype.forEach=NodeList.prototype.forEach=Array.prototype.forEach),window.Zesp...
----------------------------------------------------^---------------------------------------------------------------------------------------------------------------
```

**Comment by tdewolff** [comment]
That is strange, because `typeof` can only ever return a string, and when comparing against another string there should be no need for `===`. In fact, ESLint explicitly allows it in https://eslint.org/docs/rules/valid-typeof. However, perhaps you've set https://eslint.org/docs/rules/eqeqeq to `always` and not to `smart`?

**Comment by Lukasz032** [comment]
Totally forgot CI env had its own `.eslintrc`, separate from Visual Studio one -.- After changing `eqeqeq` to `[2, 'smart']` build succeeds.
