### ISSUE TITLE
symlinks not synced

### ISSUE THREAD

**Issue by EthraZa** [tdewolff/minify#385]
I'm using minify as
```
minify --match '\.(css|html|js|json)$' -sar dev/ -o prod/
```
The match files are getting minified, the other files are getting synced, but the symlinks are been ignored and my prod is getting non functional as a result.
There is a way to sync symlinks as well?

**Comment by tdewolff** [comment]
Yes that could be supported. Do you want to copy the symlink itself, or do you want to treat it like a file/directory (that should be traversed)?

**Comment by EthraZa** [comment]
Copy the synlinks itself, since I have things like:
```
awesome-lib-v1.0/
awesome-lib-v1.1/
awesome-lib-latest -> awesome-lib-v1.1/
```

**Comment by tdewolff** [comment]
Yes, you were a little faster than I expected! Haha, please try again, the `no such file` errors should be fixed.

Remember that the target of the symlink doesn't change (this is similar to the `cp -P` functionality). That is, if you have `src/link => file`, you'll get `dst/link => file` and not `dst/link => ../src/file` if you get what I mean.

**Comment by EthraZa** [comment]
Hi!

```php
$ ~/go/bin/minify --version
minify v2.9.13-17-g273dcd6
```
**Without -p:**
I let this erratic symlink there, pointing to itself, just to test minify (:/).
But I don't get why it's exploding if there is no -p. The stable 2.9.13 just ignores it.

```php
$ ~/go/bin/minify --match '\.(css|html|js|json)$' -sar ./dev -o ./hml 
ERROR: stat dev/lib/libweb/ext-3.4.0/ext-core: too many levels of symbolic links
```

**With -p:**
Now it worked, mostly. I noticed just 2 things with this one error throwed.
1- It didn't copied this one link, not sure why..
2- The original file was copied, but the file permission was not honored, changing from 755 to 644.

```php
$ ~/go/bin/minify --match '\.(css|html|js|json)$' -sar ./dev -o ./hml 
ERROR: symlink ../nesbot/carbon/bin/carbon hml/php/libs/vendor/bin/carbon: no such file or directory

$ ls -l dev/php/libs/vendor/bin/carbon
lrwxrwxrwx 1 allan allan 27 fev 24 17:46 dev/php/libs/vendor/bin/carbon -> ../nesbot/carbon/bin/carbon*
$ ls -l dev/php/libs/vendor/nesbot/carbon/bin/carbon
-rwxr-xr-x 1 allan allan 378 fev 24 17:46 dev/php/libs/vendor/nesbot/carbon/bin/carbon*

$ ls -l hml/php/libs/vendor/nesbot/carbon/bin/carbon
-rw-r--r-- 1 allan allan 378 mar  9 20:01 hml/php/libs/vendor/nesbot/carbon/bin/carbon
$ ls -l hml/php/libs/vendor/bin/carbon
ls: cannot access 'hml/php/libs/vendor/bin/carbon': no such file or directory
```

**Comment by tdewolff** [comment]
Regarding ownership and file permissions, doesn't seem like we can set those for symlinks in Go...it only applies to its target.

**Comment by EthraZa** [comment]
**Replicating the issue:**
(copy and paste into a nix shell - and change the minify path)
```php
$ mkdir -p dev/real dev/link; cd dev/link/; echo "console.log('Minify...'); console.log('me.');" > ../real/tst.js; ln -s ../real/tst.js; cd ../../; ~/go/bin/minify --match '\.(css|html|js|json)$' -sarp ./dev -o ./tst
false
ERROR: symlink ../real/tst.js tst/link/tst.js: no such file or directory
```

**Comment by tdewolff** [comment]
It wasn't creating all the directories if they were missing, now it should work!

**Comment by EthraZa** [comment]
Looks like it's broken.

```php
$ ~/go/bin/minify --version
minify v2.9.13-24-g81aab62

$ ~/go/bin/minify --match '\.(css|html|js|json)$' -sarpv dev/ -o tst
infer mimetype from file extensions
minify to output directory tst/
ERROR: open dev/: invalid argument

$ ~/go/bin/minify --match '\.(css|html|js|json)$' -sarv dev/ -o tst
infer mimetype from file extensions
minify to output directory tst/
ERROR: open dev/: invalid argument
```

**Comment by tdewolff** [comment]
Ah sorry, how about now?

**Comment by EthraZa** [comment]
Now it is working.
```php
$ ~/go/bin/minify --version
minify v2.9.14-1-g1635632
```

The only difference I noticed was this one: 
**v2.9.13:**
`minify ./dev -o tst`
Will create **./tst/file.js**

**v2.9.14-1-g1635632:**
`minify ./dev -o tst`
Will create **./tst/dev/file.js**
and I was unable to get it act like the older version.

**Comment by tdewolff** [comment]
Yes, this is because this way it reflects better how `cp` works. You can use `minify ./dev/. -o tst` to get the original functionality where the `dev` directory will not be created.

**Comment by EthraZa** [comment]
Oh sorry, dumb of me, just skipped the dot way in the tests.
So, looks kike it's good now. Thank you.
