### ISSUE TITLE
minify.Number change the source data

### ISSUE THREAD

**Issue by qkzsky** [tdewolff/minify#386]
```
package main

import (
	"fmt"

	"github.com/tdewolff/minify/v2"
)

func main() {
	input := []byte("1000")
	out := minify.Number(input, 0)
	fmt.Println(string(input), string(out))
}
```
expect output:
> 1000 1e3

actual output：
> 1e30 1e3

**Comment by tdewolff** [comment]
Hi. thanks for reaching out! This is actually intended behaviour as it prevents needing to copy. This is slightly faster. If you _do_ want to use the original byte-slice, please copy it first: `orig := parse.Copy(input)`
