### ISSUE TITLE
Weird entrypoint in docker file

### ISSUE THREAD

**Issue by Arkerthan** [tdewolff/minify#387]
Usually, if there is a non default entrypoint for a docker it's some form of customized shell, but importantly still a shell.

In the dockerfile for this project however the entrypoint is the executable itself, which means you can only give arguments for the minify cli tool, but not access the actual shell.

This leads to two issues:

* When using the docker container manually you cannot supply a script, only use the minify tool directly. Annoying but not necessarily gamebreaking.
* More importantly however, it is not possible to use in (some) CI/CD systems. GitLab CI for example will fail before even getting to the custom commands, presumably because it cannot setup it's environment.

The solution would be simple, remove the last line from the Dockerfile and replace it with an alias or something to give easy access to the minify executable. The problem is just that it would break existing usages of the container if it would simply replace the current one.

**Comment by tdewolff** [comment]
Thank you for the feedback! The honest truth is that I don't have any Docker experience and someone added this as a PR. What would be your suggestion to do, and would you be able to put in a PR for that? Greatly appreciated!
