### ISSUE TITLE
"go get -u github.com/tdewolff/minify/cmd/minify" gives "package io/fs: unrecognized import path "io/fs": import path does not begin with hostname"

### ISSUE THREAD

**Issue by shlomif** [tdewolff/minify#388]
```
[shlomif@localhost ~]$ go get -u github.com/tdewolff/minify/cmd/minify
package io/fs: unrecognized import path "io/fs": import path does not begin with hostname
[shlomif@localhost ~]$ inxi -CSG                                      
System:
  Host: fedora Kernel: 5.10.21-200.fc33.x86_64 x86_64 bits: 64 
  Desktop: Xfce 4.14.3 Distro: Fedora release 33 (Thirty Three) 
CPU:
  Info: Quad Core model: Intel Core i5-8259U bits: 64 type: MT MCP 
  L2 cache: 6 MiB 
  Speed: 3500 MHz min/max: 400/3800 MHz Core speeds (MHz): 1: 3500 2: 3500 
  3: 3500 4: 3501 5: 3500 6: 3499 7: 3500 8: 3500 
Graphics:
  Device-1: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] driver: N/A 
  Display: server: Fedora Project X.org 1.20.10 driver: loaded: vesa 
  unloaded: fbdev,modesetting resolution: 1920x1080~77Hz 
  OpenGL: renderer: llvmpipe (LLVM 11.0.0 256 bits) v: 4.5 Mesa 20.3.4 
[shlomif@localhost ~]$ 
```

**Comment by tdewolff** [comment]
This must be because you're using a version of Go less than 1.16. Let me see if I can circumvent the usage of the `fs` package!

**Comment by shlomif** [comment]
> This must be because you're using a version of Go less than 1.16. Let me see if I can circumvent the usage of the `fs` package!

Thanks!

**Comment by tdewolff** [comment]
I've removed the dependency on the `io/fs` package, please let me know if this works!

**Comment by tdewolff** [comment]
Hm not entirely, looks like a lot of new functionality was added in 1.16 that I'd gladly use instead of copy. Can you switch to Go1.16?

**Comment by shlomif** [comment]
> Hm not entirely, looks like a lot of new functionality was added in 1.16 that I'd gladly use instead of copy. Can you switch to Go1.16?

I'll need to find out non-intrusive ways of upgrading to golang 1.16 on:

* fedora 33 x86-64
* debian bullseye
* travis-ci/etc.
*

**Comment by shlomif** [comment]
Hi! Why was this issue closed? "Don't be a dick"/etc.: https://www.shlomifish.org/philosophy/philosophy/putting-cards-on-the-table-2019-2020/putting-cards-on-the-table-2019-2020/benevolent-psychological-warfare.xhtml . The fact is that neither fedora 33 nor debian testing ( https://wiki.debian.org/DebianBullseye ) contain golang1.16, which puts me (and likely many other future users) between a rock and a hard place. Also see: https://www.shlomifish.org/humour/fortunes/show.cgi?id=joel-remarkable-customer-service-3 .

**Comment by tdewolff** [comment]
Should work for Go1.13 now

**Comment by shlomif** [comment]
@tdewolff : thanks! ♥️
