### ISSUE TITLE
html, regression: Removal of space after i with attributes

### ISSUE THREAD

**Issue by bep** [tdewolff/minify#391]
This is a follow up of #390 -- I tested v2.9.14 and the case below still fails:

```
<i class='fas fa-tags fa-fw'></i> Tags
```

Is minified to:

```
<i class='fas fa-tags fa-fw'></i>Tags
```

Ref. https://github.com/gohugoio/hugo/issues/8332

**Comment by tdewolff** [comment]
This was fixed in v2.9.15, please re-open if this a problem
