### ISSUE TITLE
cmd program, reading from stdin broken

### ISSUE THREAD

**Issue by Arkerthan** [tdewolff/minify#392]
Trying to use the feature, that if you don't specify a file to read from stdin will be used instead.

This command: `minify.exe --mime=image/svg+xml` (which should be the bare minimum to minify a svg file from stdin and output to stdout)

Produces this error message: `ERROR: Stat: Das System kann den angegebenen Pfad nicht finden.` Sorry for german, translated something like `The system can't find the supplied path.`

OS: Win 10

edit: Same on Manjaro (Linux): Error is: `ERROR: stat: no such file or directory.` Tried with the example given here: https://github.com/tdewolff/minify/tree/master/cmd/minify#examples

minify v2.9.15

**Comment by tdewolff** [comment]
Sorry about the regressions, should be working now
