### ISSUE TITLE
CSS issue - background-color: transparent changes to background-color: initial

### ISSUE THREAD

**Issue by coliff** [tdewolff/minify#394]
Hey there. I noticed what I think is a bug. Bootstrap 5 has a `.bg-transparent` class which has the properties:

```css
background-color: transparent !important;
```

However, minify (via Hugo v80.0) changes this to:

```css
background-color:initial!important
```

`background-color: initial` [isn't supported by Internet Explorer 11](https://developer.mozilla.org/en-US/docs/Web/CSS/initial). IE11 still has approx 2% desktop browser marketshare so I don't think minify should make breaking changes to CSS for IE users.

**Comment by tdewolff** [comment]
Thanks, this should be fixed using the `KeepCSS2` option!
