### ISSUE TITLE
Issue with CSS Minify when using z-index

### ISSUE THREAD

**Issue by stoyan-g** [tdewolff/minify#395]
Hey @tdewolff

We have encountered an issue with z-index property. The issue has been experienced using Chrome browser.

When a property is defined like `z-index: calc(var(………) + 1000);` when minified it becomes `z-index: calc(var(………) + 1e3);`

When minified 1000 becomes 1e3 but it gets marked as invalid when added to z-index. It works however on `width: 1e3px` property. When changing the 1000 value to a 999 it works perfectly fine, the same goes for any thousands value, eg. 2000 to 1999.

 Kind regards,
 Stoyan

**Comment by tdewolff** [comment]
Thanks, should be fixed now!
