### ISSUE TITLE
Issues with CSS Minify when using flex property

### ISSUE THREAD

**Issue by stoyan-g** [tdewolff/minify#398]
Hey @tdewolff,

We have encountered an issue with the flex property when minified.

The following `flex: 1 1 auto;` turns to `flex:auto` when minified.
The `flex: 3 1 auto;` but this turns into `flex:initial`

I can provide the full CSS code if needed.

Btw, thank you very much for the fast resolution of my previously posted issue!

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Thanks for the issue! The `flex:1 1 auto;` should be minified to `flex:auto`, so that seems correct. I've fixed the issue of `flex:3 1 auto;` which should NOT be minified to `flex:initial`, thanks for that! Let me know if this now works for you!

**Comment by stoyan-g** [comment]
Hey there t@dewolff, 

thank you very much for the fast reply. Would it be possible to push those fixes as well as any other modification you have made to an official release, so we can update the binary on our servers? If it is not possible at the moment could you provide an ETA of when a new release is expected?

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Absolutely! Just published v2.9.16!

**Comment by stoyan-g** [comment]
Awesome @tdewolff, thanks again for the fast response. We at SiteGround are using the binary on our servers, do you have any plans to release a new CLI version with this patch included, so we can update the binary everywhere?

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Yes, the release includes binaries (perhaps I uploaded them right after you took a look).

**Comment by stoyan-g** [comment]
Oh, I've must've missed that. Thank you very much! 

Kind Regards,
Stoyan
