### ISSUE TITLE
Folder creation fails in minify CLI

### ISSUE THREAD

**Issue by FabricioTeran** [tdewolff/minify#403]
`ERROR: open ou/out/www.youtube.com\s\desktop\1f1401a5\jsbin\web-animations-next-lite.min.vflset\web-animations-next-lite.min.js: The system cannot find the path specified.`

There seems to be a bug, minify uses slash instead of backslash when searching for directories in windows.

**Comment by AvtomatK** [comment]
Sorry for the late response, do you still need me to test it? If so I will try to test the commit and tell you if everything goes well.

**Comment by tdewolff** [comment]
Yes please, thanks!

**Comment by tdewolff** [comment]
Assuming this has been fixed now, if not please reopen!
