### ISSUE TITLE
split this projects as multi repo

### ISSUE THREAD

**Issue by danny007in** [tdewolff/minify#404]
because it any one what to use single repo it would be easy, also contributor/watcher will follow up to there fav repo

**Comment by danny007in** [comment]
also publish in npm 
like esbuild

**Comment by tdewolff** [comment]
Hi Daniel, thanks for your suggestions. I can assure you that adding a NPM package is a priority. But what do you mean with the splitting the project into multiple repos?

**Comment by danny007in** [comment]
>  But what do you mean with the splitting the project into multiple repos?

Split this tdewolff/minify  to:-

- tdewolff/go-minify-js
- tdewolff/go-minify-css

etc
