### ISSUE TITLE
JS: redeclaration of let

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#405]
In minify v2.9.16, code:

```js
function solveEquation(curve) {
  let a = curve[2], b = curve[1], c = curve[0];
  if (a === 0) {
    return 0;
  } else {
    let d = b * b - 4 * a * c;
    return d;
  }
}
```

is minified to:

```js
function solveEquation(a){let b=a[2],c=a[1],d=a[0];if(b===0)return 0;let d=c*c-4*b*d;return d}
```

resulting in error:

`Uncaught SyntaxError: redeclaration of let d` (firefox)

or:

`Uncaught SyntaxError: Identifier 'd' has already been declared` (chrome)

**Comment by tdewolff** [comment]
Thanks for the bug report, I can confirm it is reproducible. I'm working on a solution!
