### ISSUE TITLE
HTML: removing leading whitespace can cause issues (even when done carefully)

### ISSUE THREAD

**Issue by tillberg** [tdewolff/minify#41]
I ran into a confusing issue with the HTML minifier recently having to do with the (careful) stripping of leading whitespace.

My HTML looked like this:
```html
<p><span>Please <span id="verb"></span><span> to the store.</span></p>
```

And then I had JS fill in the missing value on page load, e.g. `document.getElementById('verb').innerText='walk';`

The HTML minifier does a very careful job of tracking whether the last non-empty element had trailing whitespace, and if it does, then it removes the leading whitespace from the next element. I've dabbled in HTML minification before a little without ever realizing that this could potentially be safe, so I was impressed, and I think it's really clever.

But alas, if the minifier doesn't or can't know the actual contents of all the elements, then it's not safe. Because "verb" is only filled in after-the-fact, it strips out the leading whitespace before "to the store", resulting in the user seeing something like this:

```
Please walkto the store.
```

For reference, I fixed this (by removing this optimization) on my own branch at https://github.com/tillberg/minify/commit/d6c88a27578e9cca04e30425be0ac718e206e8f5.

(side note: maybe it would be neat to package this and a couple of the other not-100%-safe optimizations under an optional `html.MinifyDangerous` method? most users could then benefit easily from a really fantastic implementation of basic HTML optimizations, while users seeking to cut every last possible byte could carefully apply the dangerous ones.)

**Comment by tdewolff** [comment]
There might be a need for passing options to the minifier so one can disable certain features, including this one. I will need to think this through, because it has some implications. An implementation for options is shown in https://github.com/omeid/minify/commit/e318d4d41748f9f2fcd3ff839e5f2ccae70dcbf2

**Comment by tdewolff** [comment]
This is now an option you can set!
