### ISSUE TITLE
Mangle CSS classe/id names across html css js

### ISSUE THREAD

**Issue by joelmo** [tdewolff/minify#418]
This reduces string length for classes/ids. Should be an optional optimization.

**Comment by tdewolff** [comment]
This is not possible in the current setup of the minifiers. The minifiers work on a file-by-file basis and we don't know which other files depend on the minified file. If we change class names, it might be that some other reference gets broken. To make this work there'd need to be a project-based minifier, that loads in all the website files and compresses them.
