### ISSUE TITLE
Inkscape SVGs keep <metadata> ending tags (and more)

### ISSUE THREAD

**Issue by jadaradix** [tdewolff/minify#42]
<img width="845" alt="screen shot 2015-09-06 at 04 13 40" src="https://cloud.githubusercontent.com/assets/6841082/9702269/067d8022-544e-11e5-80a6-3365cf1993f5.png">

The starting tags have been removed, but some ending tags still remain. The offending original markup is this:

    <metadata
       id="metadata4166">
      <rdf:RDF>
        <cc:Work
           rdf:about="">
          <dc:format>image/svg+xml</dc:format>
          <dc:type
             rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
          <dc:title />
        </cc:Work>
      </rdf:RDF>
    </metadata>

(Your work is very much appreciated - keep it up)

**Comment by tdewolff** [comment]
Thanks, I will fix this soon!

**Comment by tdewolff** [comment]
Fixed in the develop branch, will be merged sometime soon into master.
