### ISSUE TITLE
Installation hell

### ISSUE THREAD

**Issue by esperlu** [tdewolff/minify#420]
Sorry if I bother you with something that might be trivial , but I am new to the use of Go Modules and I am totally confused and unable to install minify at all.
```
$ env
GOBIN=/home/jeanluc/golang/bin
GO111MODULE=auto
GOPATH=/home/jeanluc/golang

$ go version
go version go1.15.3 linux/amd64

$ go get "github.com/tdewolff/minify/v2"
cannot find package "github.com/tdewolff/minify/v2" in any of:
	/usr/local/go/src/github.com/tdewolff/minify/v2 (from $GOROOT)
	/home/jeanluc/golang/src/github.com/tdewolff/minify/v2 (from $GOPATH)
```
Something is installed in `$HOME/golang/src/github.com/tdewolff` though.

When I build a go file with : 
```
import (
	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/html"
)
```
I get this : 

```
$ go build mini.go 
mini.go:4:2: cannot find package "github.com/tdewolff/minify/v2" in any of:
	/usr/local/go/src/github.com/tdewolff/minify/v2 (from $GOROOT)
	/home/jeanluc/golang/src/github.com/tdewolff/minify/v2 (from $GOPATH)
mini.go:5:2: cannot find package "github.com/tdewolff/minify/v2/html" in any of:
	/usr/local/go/src/github.com/tdewolff/minify/v2/html (from $GOROOT)
	/home/jeanluc/golang/src/github.com/tdewolff/minify/v2/html (from $GOPATH)

```
Also the [installation doc](https://github.com/tdewolff/minify#installation) mention `GO111MODULES` as env. variable. Is the plural a typo ?

**Comment by esperlu** [comment]
... well found that I needed to initiate `go.mod` file for my project and all went smoothly afterwards. May I suggest to add this to the doc for other users that might skip that `go mod init` step ? Thanks for the good work.

**Comment by tdewolff** [comment]
Yes, `go mod init` is important. I've added some more instructions, thanks!

**Comment by esperlu** [comment]
`go modules` is cool... once you know how to use it. And what about the env. variable, is it `GO111MODULE` or `GO111MODULES` (plural) as stated in the installation instructions? I can find no mention of the plural form in the Go doc.
Cheers. Jean-Luc.

**Comment by tdewolff** [comment]
Good point! I've amended the readme.
