### ISSUE TITLE
HTML Keep Quotes Not Working

### ISSUE THREAD

**Issue by saefulrahman** [tdewolff/minify#421]
I added `--html-keep-quotes` on my hugo blog, according to the existing [docs](https://github.com/tdewolff/minify/tree/master/cmd/minify). But when minify process, the syntax is not found or does not exist. 
This is my code :
```
minify -r -o public/ --match=\.html --html-keep-quotes --html-keep-document-tags --html-keep-end-tags  public/
minify -r -o public/ --match=\.js public/
minify -r -o public/ --match=\.css public/
```
And this is a screenshot of the error that appears
![Screenshot from 2021-06-15 13-38-01](https://user-images.githubusercontent.com/6184154/122005080-63298a80-cddf-11eb-8952-72191c18671c.png)

I am using minify v2.5 from apt ubuntu. When I install according to the [docs](https://github.com/tdewolff/minify/tree/master/cmd/minify), an error appears and can't install minify.
![Screenshot from 2021-06-15 22-14-17](https://user-images.githubusercontent.com/6184154/122078830-11a4ee00-ce27-11eb-9a4c-7eeaf4397914.png)

**Comment by tdewolff** [comment]
Yes, minify v2.5 appears to not have supported `--html-keep-quotes`, you'll need to latest version for that. As to your error when installing bash completion, I'm really at odds because it works fine on my computer (Arch Linux) using `sh`. You can leave out the bash completion part, it's not necessary.

What bash are you using, is `sh` a symlink to another type of bash?

**Comment by saefulrahman** [comment]
I use oh my zsh.  I don't know, when I tried it it didn't work. When I type the `make install` on terminal, then an error message appears in `cmd/minify/bash_completion`.

**Comment by tdewolff** [comment]
Please let me know if this works!

**Comment by saefulrahman** [comment]
I tried it on another OS on Linux Mint 20.1, but the result is the same. An error appears in the `bash_completion` file.

But I'm still trying to fix it, so it can be installed on my computer. I'll let you know if it works.

**Comment by saefulrahman** [comment]
> Please let me know if this works!

I tried it again, after you did the update. But the result is still the same, the following error appears.
```
Installing v2.9.17-6-g99354c7
/bin/sh: 20: cmd/minify/bash_completion: Syntax error: "(" unexpected (expecting "fi")
make: *** [Makefile:13: install] Error 2
```
