### ISSUE TITLE
JS: Problem with default parameters

### ISSUE THREAD

**Issue by carlmjohnson** [tdewolff/minify#422]
```js
f = ({ a: b = 1} = {}) => b
```

(Explanation for the unfamiliar, this creates an arrow function in which b is set to the .a attribute of the first argument, and the argument defaults to an empty object and the attribute defaults to 1.)

Expected output: same but no spaces.

Actual output:

```
f=({a:}={})=>a
```

The actual output is a syntax error.

**Comment by tdewolff** [comment]
Thanks! Should be fixed now. Please note that `({a:b=1}={})=>b` could be rewritten as `({a:a=1}={})=>a` which is the same as `({a=1}={})=>a`. Another 2 bytes saved ;-)
