### ISSUE TITLE
[feature] official alpine package

### ISSUE THREAD

**Issue by quasis** [tdewolff/minify#423]
Will be more than useful to those who install Ubuntu just to get the updated tool without the fuss of checking checksums.
https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by tdewolff** [comment]
Thanks, that is a great idea. I'll try and create an Alpine package soon, though I hope the requirement at the top that says "To build a package for Alpine Linux you need an Alpine Linux installation" isn't too strict, as I only have Arch Linux available.

**Comment by M1sth1os** [comment]
I was actually making a package of the minify binary when i saw this issue.
Just dropping by to say that the package is now available on alpine edge in the testing repo.

**Comment by tdewolff** [comment]
Excellent, thank you @M1sth1os !! Please keep us in the loop when the package gets into the main repository so that I can add a description to the GitHub page of the CLI tool on how to install.

**Comment by M1sth1os** [comment]
its in the edge community repo now. next stable release will include it but u can get it right now as well when running edge :)

**Comment by M1sth1os** [comment]
hey, 
Minify can be found in the community repo of 3.16 & edge

**Comment by tdewolff** [comment]
Excellent @M1sth1os ! Thank you very much for the effort, it is highly appreciated. Will new versions of `minify` be automatically updated in the alpine package, or would each new version of alpine consider upgrading `minify`? Will you be keeping an eye out for updates?

**Comment by M1sth1os** [comment]
Hey,
Edge will always try to have the latest (as edge is rolling)
Releases itself will be supported for 6months and will include at least bug fix releases (might include feature releaes as well depending on the breakage).
As for me I will keep an eye on minify but it always possible for others to open a merge request to the alport repo on the alpine gitlab to update the package if I am not available.
