### ISSUE TITLE
Issue with gclid scrpit

### ISSUE THREAD

**Issue by stoyan-g** [tdewolff/minify#425]
Hey there, the following script from Google -> https://support.google.com/google-ads/answer/7012522 is breaking when minified. 

`function getExpiryRecord(value) {
var expiryPeriod = 90 * 24 * 60 * 60 * 1000; // 90 day expiry in milliseconds

var expiryDate = new Date().getTime() + expiryPeriod;
return {
value: value,
expiryDate: expiryDate
};`

I guess the issue is causrd by the comment // 90 day expiry in milliseconds
and the black line underneath it, so when minified the var expiryDate part gets moved right after the comment making it look something like this :
`var expiryPeriod = 90 * 24 * 60 * 60 * 1000; // 90 day expiry in milliseconds var expiryDate = new Date().getTime() + expiryPeriod;`

which is breaking the script.

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Hi Stoyan, thanks for the report. I'm not fully understanding your conclusion, the minifier should remove the line-comment entirely, so it shouldn't influence the script. Can you verify that? Furthermore, the script is missing a closing `}`, when adding that it minifies to:

```go
function getExpiryRecord(a){var b=90*24*60*60*1e3,c=(new Date).getTime()+b;return{value:a,expiryDate:c}}
```

The only thing that comes to mind, is that `1e3` is a float that would otherwise be an integer. Perhaps this influences the addition to `getTime()`. Could you see if replacing `1e3` with `1000` helps?

**Comment by stoyan-g** [comment]
Hey there tdewolff ,
My bad for not posting the code properly. This is actually just a part of the whole snippet Google is providing so you can enable the lead tracking system.
The whole code can be found at the link I've sent. I am also posting it here for your convenience:

`<script>


function getParam(p) {
var match = RegExp('[?&]' + p + '=([^&]*)').exec(window.location.search);
return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function getExpiryRecord(value) {
var expiryPeriod = 90 * 24 * 60 * 60 * 1000; // 90 day expiry in milliseconds

var expiryDate = new Date().getTime() + expiryPeriod;
return {
value: value,
expiryDate: expiryDate
};
}

function addGclid() {
var gclidParam = getParam('gclid');
var gclidFormFields = ['gclid_field', 'foobar']; // all possible gclid form field ids here
var gclidRecord = null;
var currGclidFormField;

var gclsrcParam = getParam('gclsrc');
var isGclsrcValid = !gclsrcParam || gclsrcParam.indexOf('aw') !== -1;

gclidFormFields.forEach(function (field) {
if (document.getElementById(field)) {
currGclidFormField = document.getElementById(field);
}
});

if (gclidParam && isGclsrcValid) {
gclidRecord = getExpiryRecord(gclidParam);
localStorage.setItem('gclid', JSON.stringify(gclidRecord));
}

var gclid = gclidRecord || JSON.parse(localStorage.getItem('gclid'));
var isGclidValid = gclid && new Date().getTime() < gclid.expiryDate;

if (currGclidFormField && isGclidValid) {
currGclidFormField.value = gclid.value;
}
}

window.addEventListener('load', addGclid);

</script>`

So when SiteGround customers want to add this to their website, they add that snippet. I am aware that the comment should be removed entirely but for some reason, it is not. It is just removing the blank line under 
`var expiryPeriod = 90 * 24 * 60 * 60 * 1000; // 90 day expiry in milliseconds  `

and pushes `var expiryDate` and the line stays commented.

I can confirm that when minifying the HTML, the comment is not being removed. However, if I move the comment above var 

`expiryPeriod = 90 * 24 * 60 * 60 * 1000;`

The minification is not breaking the code, but it's not removing the comments for some reason. The same goes if I remove the blank line under the comment.

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Hi Stoyan, sorry for the late response, I was on vacation.

Regarding the issue, if I minify the given snippet as using the HTML minifier (which invokes the JS minifier for the <script> part), I get the following output:

```html
<script>function getParam(b){var a=RegExp('[?&]'+b+'=([^&]*)').exec(window.location.search);return a&&decodeURIComponent(a[1].replace(/+/g,' '))}function getExpiryRecord(a){var b=90*24*60*60*1e3,c=(new Date).getTime()+b;return{value:a,expiryDate:c}}function addGclid(){var e=getParam('gclid'),f=['gclid_field','foobar'],b=null,d=getParam('gclsrc'),g=!d||d.indexOf('aw')!==-1,c,a,h;f.forEach(function(a){document.getElementById(a)&&(c=document.getElementById(a))}),e&&g&&(b=getExpiryRecord(e),localStorage.setItem('gclid',JSON.stringify(b))),a=b||JSON.parse(localStorage.getItem('gclid')),h=a&&(new Date).getTime()<a.expiryDate,c&&h&&(c.value=a.value)}window.addEventListener('load',addGclid)</script>
```

As you can see, I don't have the comment problem you describe and I fail to reproduce the error. Can you make sure you have the latest minify and try again, given the snippet you posted and invoking `minify -o out.html in.html`?

**Comment by stoyan-g** [comment]
Hey there @tdewolff ,

We've updated the binary to the latest version, added the snippet to the website as most of our clients add it and when we minify the output we get the same result. Here's a link where the issue is visible -> https://stoyang63.sg-host.com/binarka_test/ . Ping me if you need any additional details.

Kind regards,
Stoyan

**Comment by tdewolff** [comment]
Hi @stoyan-g , thanks for the example. I can see that the example you gave is badly minified, actually I don't think it's minified at all! I notice the comment at line 85 which you mention. However, as soon as I minify the HTML source, the code around that comment becomes:

```html
content!<h6 id=wp-block-themeisle-blocks-advanced-heading-4334554b class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-4334554b"><strong>TIFFANY BRYANT</strong></h6></div></div></div><p></div></div></div></div></main><footer class=site-footer id=site-footer><div class=hfg_footer><div class="footer--row footer-bottom layout-full-contained" id=cb-row--footer-bottom data-row-id=bottom data-show-on=desktop><div class="footer--row-inner footer-bottom-inner footer-content-wrap"><div class=container><div class="hfg-grid nv-footer-content hfg-grid-bottom row--wrapper row" data-section=hfg_footer_layout_bottom><div class="builder-item hfg-item-last hfg-item-first col-12 desktop-center tablet-center mobile-center hfg-item-v-middle"><div class="item--inner builder-item--footer_copyright" data-section=footer_copyright data-item-id=footer_copyright><div class=component-wrap><p><a href=https://themeisle.com/themes/neve/ rel=nofollow>Neve</a> | Powered by <a href=http://wordpress.org/ rel=nofollow>WordPress</a></div></div></div></div></div></div></div></div></footer></div><script>function getParam(b){var a=RegExp('[?&]'+b+'=([^&]*)').exec(window.location.search);return a&&decodeURIComponent(a[1].replace(/\+/g,' '))}function getExpiryRecord(a){var b=90*24*60*60*1e3;return{value:a,expiryDate}}function addGclid(){var e=getParam('gclid'),f=['gclid_field','foobar'],b=null,d=getParam('gclsrc'),g=!d||d.indexOf('aw')!==-1,c,a,h;f.forEach(function(a){document.getElementById(a)&&(c=document.getElementById(a))}),e&&g&&(b=getExpiryRecord(e),localStorage.setItem('gclid',JSON.stringify(b))),a=b||JSON.parse(localStorage.getItem('gclid')),h=a&&(new Date).getTime()<a.expiryDate,c&&h&&(c.value=a.value)}window.addEventListener('load',addGclid)</script><script defer src=stoyang_files/regenerator-runtime.js id=regenerator-runtime-js></script><script src=stoyang_files/wp-polyfill.js id=wp-polyfill-js></script><script defer src=stoyang_files/themeisle-gutenberg-animation-frontend.js id=themeisle-gutenberg-animation-frontend-js></script><script defer src=stoyang_files/lazysizes.js id=siteground-optimizer-lazy-sizes-js-js></script><script id=neve-script-js-extra>var NeveProperties={ajaxurl:"https://stoyang63.sg-host.com/binarka_test/wp-admin/admin-ajax.php",nonce:"cb467e2b65",isRTL:"",isCustomize:""}</script><script defer src=stoyang_files/neve-script.js id=neve-script-js async></script><script defer src=stoyang_files/comment-reply.js id=comment-reply-js></script><script src=stoyang_files/wp-embed.js id=wp-embed-js></script>
```

I strongly suspect that the website is not properly minified, or that something goes wrong in your pipeline. Can you verify that minifying the HTML source gets rid of the comment?

**Comment by stoyan-g** [comment]
Hey there @tdewolff, 

After some digging, I found out the issue was not related to the Minify at all...

I am really sorry if this thread caused some inconvenience. 

Thank you very much for the time spent trying to figure it out and for the awesome project! I really appreciate it!

Kind regards,
Stoyan
