### ISSUE TITLE
JS: switch statement regression

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#426]
Code:

```js
switch ('jpg') {
  case 'jpg':
    data = '<h1><span style="color:gray;">' + tr('Image') + ': <\/span> ' + fname[1] + '.' + fname[2] + '<\/h1>' + '<img src="' + file + '"><\/img>';
    Math.random();
    Math.random();
}
```

is minified to:

```js
switch('jpg'){case'jpg':data='<h1><span style="color:gray;">'+tr('Image')+': </span> '+fname[1]+'.'+fname[2]+'</h1>'+'<img src="'+file+'"></img>',Math.random(),Math.random();data='<h1><span style="color:gray;">'+tr('Image')+": </span> '"+fname[1]+'.'+fname[2]+"</h1>'"+'<img src="'+file+'"></img>\'',Math.random();data='<h1><span style="color:gray;">'+tr('Image')+": </span> '"+fname[1]+'.'+fname[2]+"</h1>'"+'<img src="'+file+'"></img>\',Math.random(),Math.random()}
```

resulting in error:

`Uncaught SyntaxError: Invalid or unexpected token`

Additionally, the size is increased:
```
Ratio:  207.6%
Size:  225B → 467B
```

You can add more Math.randoms to increase the ratio even more.

I have run a git bisect:

bb43a7ed31343de6fe5914c46a5cdd77472ae60a is the first bad commit
commit bb43a7ed31343de6fe5914c46a5cdd77472ae60a
Author: Taco de Wolff <tacodewolff@gmail.com>
Date:   Mon May 10 22:02:40 2021 -0400

    JS: add variable scope to switch statement

**Comment by tdewolff** [comment]
Thanks for the issue, should be fixed now!
