### ISSUE TITLE
CSS Flex shorthand

### ISSUE THREAD

**Issue by timohuber** [tdewolff/minify#431]
```
.flexrow > * {
flex: 0 1 auto
}
```
converts to 
```
.flexrow>*{
flex: 0 1;
}
```
`flex-basis: auto;` is required.
Otherwise it does not behave the same way: [Codepen](https://codepen.io/tihu/pen/NWjVVEb)

**Comment by tdewolff** [comment]
Thanks for the report! However, for me `flex:0 1 auto` is minified to `flex:initial`. Also `flex:0 2 auto` doesn't have the `auto` cut off either. Do you have the latest version of minify?

**Comment by timohuber** [comment]
Thanks for the quick reply. 

Yes. minify --version returns `minify version master`

I use it in gitlab pipelines for a while and this issue didn't occure when they run the last time.

**Comment by tdewolff** [comment]
I assume this issue fixed then! Please re-open if this persists.

**Comment by chuckwagoncomputing** [comment]
I'm having this problem now.
With 2.12.1 from the Ubuntu repo, `flex: 0 1 auto;` gets changed into `flex: 0 1;`
With 2.12.4 from the AUR, `flex: 0 1 auto;` gets changed into `flex: initial;`

**Comment by chuckwagoncomputing** [comment]
Actually I was mistaken regarding the Ubuntu repo version, it was in fact 2.7.2 from the Debian repo.
The issue with 2.12.4 is still a thing.

**Comment by tdewolff** [comment]
Thanks for raising the issue, I will take a look at this in March!
