### ISSUE TITLE
HELP: Run docker image as a HTTP service

### ISSUE THREAD

**Issue by shinsenter** [tdewolff/minify#433]
Thank you for a great tool!

> If you want to use Docker, please see https://hub.docker.com/r/tdewolff/minify.

Please teach me how to run the docker image as a HTTP service (like your demo).

**Comment by tdewolff** [comment]
I'm not really a Docker expert, but running

```bash
docker pull tdewolff/minify
docker run -i tdewolff/minify
```

will download the container and run it in interactive mode (`-i`). You can now type `echo "function test() { return 5; }" | minify --type js` and it will return `function test(){return 5}` (the minified result).

To run as an HTTP service you'll need to build some HTTP front-end that redirects to the minify tool, this completely depends on what you'd like to do! Not sure I can help you much, the demo is built using Go and directly calls the library.
