### ISSUE TITLE
--sync switch is not preserving timestamps

### ISSUE THREAD

**Issue by EthraZa** [tdewolff/minify#435]
I'm using `minify --all  --sync --recursive ...` but it is not preserving files dates and times.
There is an option or is it possible to implement it to act more like a cp -p or -a?

From **man cp**:
```yml
-a, --archive
              same as -dR --preserve=all
-p     same as --preserve=mode,ownership,timestamps
-d     same as --no-dereference --preserve=links
-R, -r, --recursive
              copy directories recursively
```

Or if **minify --sync** could just be like **cp --preserve=all**, at least for the files that where not minified, would be great.

**Comment by tdewolff** [comment]
Thanks for the suggestion! This seems like a great idea, I will try and implement this as soon as I get some time on my hands!

**Comment by tdewolff** [comment]
Please check this implementation (remark: setting file ownership only works on Linux)

You can now pass `-p` or `--preserve` to keep mode,ownership,timestamps, or set it manually using e.g. `--preserve=mode,timestamps`, exactly like `cp`!

**Comment by EthraZa** [comment]
-p seems working like a chram. 

Thank you.
