### ISSUE TITLE
Whitespace in <a rel=""> is not trimmed

### ISSUE THREAD

**Issue by geekman** [tdewolff/minify#436]
Tested with v2.9.21.

```
$ echo '<a href=# rel="noopener ">link</a>' | ./minify --mime text/html
<a href=# rel="noopener ">link</a>
                       ^
```

`rel` should be a set of space-separated keywords, so I believe whitespace can be stripped here.

I have taken a quick look through the [HTML test cases](https://github.com/tdewolff/minify/blob/master/html/html_test.go), which leads me to believe that not all whitespace in all attributes are trimmed.

**Comment by tdewolff** [comment]
Good find, this would be a great feature to add, I'll look into it!

**Comment by tdewolff** [comment]
I've added this feature, let me know what you think!
