### ISSUE TITLE
async lambda with object argument breaks

### ISSUE THREAD

**Issue by jon49** [tdewolff/minify#439]
I start with this (file `temp.js`):

```js
const temp = async ({val, val2}) => {
    console.log(val, val2)
}

temp({val: "yes", val2: "no"})
```

When I use `minify` (`minify temp.js`) it compiles to:

```js
const temp=async{val:a,val2:b}=>{console.log(a,b)};temp({val:"yes",val2:"no"})
```

As you can see it removes the parentheses when it shouldn't.

**Comment by tdewolff** [comment]
Thanks for the bug report. Can you please check which version of `minify` you are using? Using the latest version this doesn't seem to be an issue.

**Comment by jon49** [comment]
Whoops, I forgot to do the most important thing before creating a bug...upgrading to the latest. I was on `2.9.10`. But upgrading to `2.9.22` fixes the issue.
