### ISSUE TITLE
Minified canvases with nested paragraph not rendered correctly.

### ISSUE THREAD

**Issue by jon49** [tdewolff/minify#440]
I have some `HTML` that looks like this:

```html
<style>
canvas {
    border: solid black 2px;
    height: 100px;
    width: 400px;
}
</style>

<main>
    <canvas id=first><p>loading...</p></canvas>
    <canvas id=second><p>loading...</p></canvas>
</main>
```

It is minified like this:

```html
<style>canvas{border:solid #000 2px;height:100px;width:400px}</style><main><canvas id=first><p>loading...</canvas>
<canvas id=second><p>loading...</canvas></main>
```

And chrome renders it like this (not including the `style` tag for brevity). Notice that the first canvas wraps the second canvas and paragraph.

```html
<main>
    <canvas id="first"><p>loading...
    <canvas id="second"></canvas></p><p>loading...
</p></canvas></main>
```

The work around is to just wrap the `canvas` tags in a `div` tag. The library (chart.js) I'm using says to do that anyways. So, that is what I'll do.

**Comment by tdewolff** [comment]
I've pushed out a fix, let me know if that works for you!

**Comment by jon49** [comment]
Is there a way I could download the windows version or would I need to build it manually? I downloaded the latest version but it is from 8 days ago.

I don't have `Go` installed on my computer but I could install it.

**Comment by tdewolff** [comment]
Easiest is install Go and run `make install` from the repository. The new version will be released next week probably.
