### ISSUE TITLE
binary for raspberry pi

### ISSUE THREAD

**Issue by hexabyte23** [tdewolff/minify#443]
Hello,

I try to compile a version for rpi, but make command freeze on last line:

Installing v2.9.22-8-g5f59503
go: downloading github.com/fsnotify/fsnotify v1.5.1
go: downloading github.com/matryer/try v0.0.0-20161228173917-9ac251b645a2
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/tdewolff/parse/v2 v2.5.22
go: downloading golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c

**Comment by tdewolff** [comment]
That is strange. What Go version are you using? What Raspberry Pi do you have? Other people seem to be successful in installing `golang.org/x/sys` on a Raspberry (if that even is the problem). Can you run the installation with more verbosity (adding `-v` once or twice)?

**Comment by tdewolff** [comment]
Assuming this is no longer a concern, please reopen if it is so!
