### ISSUE TITLE
How to preserve type="text"?

### ISSUE THREAD

**Issue by bobvanluijt** [tdewolff/minify#444]
Similar to [this](https://github.com/middleman/middleman-minify-html/issues/9) issue, `minify --match='\.html' -r -o _site_min/ _site/` removes all `type="text"`'s.
How can I preserve them?
Thanks :)

**Comment by tdewolff** [comment]
There is currently no option to keep those attributes (though maybe in the future there will be). In the mean time you could use `input:not([type]), input[type=""], input[type="text"]` to select all text input fields, not just the ones that are explicitly set. This may actually be desirable to ensure you style all input text fields in all cases (most CSS frameworks should have this implemented).
