### ISSUE TITLE
Unexpected character for every file

### ISSUE THREAD

**Issue by LucasGorgal** [tdewolff/minify#448]
I am trying to minify a folder in Windows using the binary, and every file it will output something like this:

```
ERROR: cannot minify site-test/assets/iconfonts/boxicons/fonts/._boxicons.svg: XML parse error: unexpected NULL character on line 1 and column 1
    1: ········Mac OS X        ·········2···�·······�···········...
       ^
```

Link to download this file to see it: https://transfer.sh/kqRzhu/._boxicons.svg

**Comment by tdewolff** [comment]
The file seems to be something else than an SVG files (it seems to be a binary file, not a text file!), so it is not a Scalable Vector Graphics (SVG) file format. That will not be parsed well, so the error is expected. How come those files are binaries?

**Comment by tdewolff** [comment]
Assuming you we're minifying SVG files, closing this issue now. Please reopen if you think this is still a valid concern!
