### ISSUE TITLE
Easier install

### ISSUE THREAD

**Issue by spekary** [tdewolff/minify#453]
Just a suggestion for an easier install.

Go 1.17 introduced the following syntax for installing executables written in GO:

```
go install github.com/tdewolff/minify@latest
```

Currently you get an error message when you run this. I think the fix is simply a matter of moving your main.go to the top level of your repo.

**Comment by tdewolff** [comment]
You'll need to run
```
go install github.com/tdewolff/minify/cmd/minify@latest
```
to install the latest version of `minify`. I recommend the guide at https://github.com/tdewolff/minify/tree/master/cmd/minify though in order to properly set the version build tag for the command (for `minify --version`). Thanks anyways!

**Comment by tcurdt** [comment]
Speaking of easy installs....
Building from source is not great for all occasions. Maybe `goreleaser` could be used for future releases?
A homebrew install would be great, too.

**Comment by tcurdt** [comment]
Ah, I didn't see the tap. The link in the README I totally missed. Thanks!
Surely makes it easier. That said a binary install/formula still would be nicer (e.g. for CI/CD)

I checked [the releases](https://github.com/tdewolff/minify/releases) but the last release has only source assets. And older releases don't include darwin on arm.

**Comment by tdewolff** [comment]
True, like I said the latest doesn't have binaries because I'm about to release a new version. There is a Makefile that is specifically for installing actually, use `make install` from the root directory to install the binary. Anyways, old releases are history ;-)

**Comment by mrbluecoat** [comment]
Requires ZSH?

```
$ make install
Installing v2.9.29-8-gfe5284a
/bin/sh: 20: cmd/minify/bash_completion: Syntax error: "(" unexpected (expecting "fi")
make: *** [Makefile:13: install] Error 2
```

**Comment by mrbluecoat** [comment]
Found a workaround for my needs:

```
cd /tmp
git clone https://github.com/tdewolff/minify.git
cd minify/cmd/minify
go build
mv minify /usr/local/bin
```

**Comment by tdewolff** [comment]
It's a little weird since the bash completion script should only be executed by `bash` (which is why it starts with `#!/usr/bin/env bash`) which has array support. It kind of looks like you're using `sh` or something that only supports POSIX. I've tried to make it more POSIX compliant with 7ff011b2d6dbf75efc9589eef91e9d6c0e1bb000, but I haven't seen anyone really make a POSIX compliant bash completion script. I'd be happy to know how to write `COMPREPLY=($(compgen ...))` in a POSIX compliant way...
