### ISSUE TITLE
Add module awareness

### ISSUE THREAD

**Issue by spekary** [tdewolff/minify#454]
I have written a file utility which does a variety of file operations here:

github.com/goradd/gofile

In there, I have exported a function in the sys package called GetModulePath()

If a path is preceded by a module path, it will output the physical location. This is great for build systems that need to be module aware. Some use cases:

- If you want to minify a file that is in a package managed by Go,  it will find the location of that file in the go modules cache.
- You have a "replace" statement in your go.mod file and you want to find a file in that path.

For example, the path github.com/tdewolff/minify/test would be changed to /loc/on/disk/test. 

It would make minify even more useful in build systems if the file paths fed to it would be processed through GetModulePath() first.

**Comment by tdewolff** [comment]
Thanks for the suggestion! I'm not entirely following what you want. The `minify` tool tries to mimic the behaviour of `cp` (copy) where we are besides copying also minifying the files. That means it needs an input file path and an output file path. Both are Go-agnostic, as in it is a tool that can be used for any type of application and it doesn't really revolve around minifying file in Go modules only. Why should `minify` be Go module aware, if people can just pass the absolute path? And if `minify` were Go module aware, how would someone minify a regular file that has nothing to do with a Go module?

**Comment by spekary** [comment]
Never mind. I thought of another way to do it. I will just make a command line tool to convert module paths to real paths, and then that can be past to minify. You are right, minify shouldn't worry about it.
