### ISSUE TITLE
JS minify question using v2.9.28

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#455]
Is this expected?

a.js

```js
var x; x = 5, document.getElementById("demo").innerHTML = x * 10
```

b.js

```js
var x;
x = 5;
document.getElementById("demo").innerHTML = x * 10;
```

a.js minified

```js
var x;x=5,document.getElementById("demo").innerHTML=x*10
```

b.js minified

```js
var x=5;document.getElementById("demo").innerHTML=x*10
```

In comparison, `https://jscompress.com/` produces the same output for each one:

```js
var x=5;document.getElementById("demo").innerHTML=10*x;
```

**Comment by tdewolff** [comment]
Given the new restructuring of comma-expressions, this should now be pretty easy to implement. I'll get to it ASAP, thanks for the suggestion!
