### ISSUE TITLE
Removes spaces around code tag in the middle of a sentence

### ISSUE THREAD

**Issue by tv42** [tdewolff/minify#46]
Example from the spec, https://html.spec.whatwg.org/multipage/semantics.html#the-code-element

```
<p>The <code>code</code> element represents a fragment of computer
code.</p>
```

Minified result:

```
<p>The<code>code</code>element represents a fragment of computer code.
```

Browsers will render that as words run together:

![image](https://cloud.githubusercontent.com/assets/419909/9983656/89b3e438-5fb9-11e5-80dd-33c92a5170ee.png)

**Comment by tdewolff** [comment]
I have added `code`, `del`, `ins`, `textarea` and `script` as inline tags. Good find!

**Comment by tdewolff** [comment]
Further improved whitespace removal with f175959bef7f743d20d8c7bd889c5d9c9466fb91, it will now remove all whitespace around the given list of block elements. Beforehand it removed it from all elements except inline elements. This is more robust for newly added tags for example.
