### ISSUE TITLE
unexpected paths

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/minify#460]
I am running `minify -v -r -o dist/ public/`

What I am getting:
```
infer mimetype from file extensions
minify to output file dist/
(114.125µs, 2.1 kB, 1.6 kB,  77.4%,  18 MB/s) - public/css/styles.css to dist/public/css/styles.css
( 54.917µs,  685 B,  577 B,  84.2%,  12 MB/s) - public/de/index.html to dist/public/de/index.html
( 48.667µs,  600 B,  492 B,  82.0%,  12 MB/s) - public/en/index.html to dist/public/en/index.html
(  43.75µs,  205 B,  164 B,  80.0%, 4.7 MB/s) - public/index.html to dist/public/index.html
```

what I would have expected:
```
infer mimetype from file extensions
minify to output file dist/
(114.125µs, 2.1 kB, 1.6 kB,  77.4%,  18 MB/s) - public/css/styles.css to dist/css/styles.css
( 54.917µs,  685 B,  577 B,  84.2%,  12 MB/s) - public/de/index.html to dist/de/index.html
( 48.667µs,  600 B,  492 B,  82.0%,  12 MB/s) - public/en/index.html to dist/en/index.html
(  43.75µs,  205 B,  164 B,  80.0%, 4.7 MB/s) - public/index.html to dist/index.html
```

**Comment by tdewolff** [comment]
`minify` emulates the behaviour of `cp` to be more intuitive. That means that trailing slashes have no effect on the destination path.

Assuming we have a directory `in` with one file: `in/file.js`. There are three cases:
1. `minify -o out in`: we expect to minify `in/file.js` to `out/file.js`, unless `out` exists and is a directory, in which case we expect to minify  `in/file.js` to `out/in/file.js`
2. `minify -o out in/*`: we expect to minify  `in/file.js` to `out`, unless `out` exists and is a directory, in which case we expect to minify `in/file.js` to `out/file.js`

Now assume we have `in/dir/test.js` as our input:
3. `minify -o out in`: we expect to minify `in/dir/file.js` to `out/dir/file.js`, unless `out` is a directory, in which case we expect to minify  `in/dir/file.js` to `out/in/dir/file.js`
4. `minify -o out in/*`: we expect to minify  `in/dir/file.js` to `out/file.js`, unless `out` is a directory, in which case we expect to minify  `in/dir/file.js` to `out/dir/file.js`

I'm working on an update to make it work in all cases.

**Comment by tcurdt** [comment]
I see. So essentially I should have used `minify -v -r -o dist public/*`.
TBH I am not sure `cp` is the best to emulate - but I understand the sentiment.

**Comment by tdewolff** [comment]
What other tool do you recommend to emulate? Based on the fact that we copy files (while minifying) from A to B, and there is a `--sync` option which basically is like a `cp`, I thought it made sense.
