### ISSUE TITLE
[Request] Input absolute path for minify cli

### ISSUE THREAD

**Issue by haoadoresorange** [tdewolff/minify#461]
As title said,
Would you want to ? I can make a PR I think.

**Comment by tdewolff** [comment]
What is the request, absolute paths don't work?

**Comment by tdewolff** [comment]
I this for the Windows platform? We're fixing that at the moment, release should be out soon!

**Comment by tdewolff** [comment]
This should be fixed in a8af516dfba3e67eece84332fee72701c95ab579, please re-open if not!

**Comment by haoadoresorange** [comment]
Hi,
Sorry for my lack of information, based on the behaviour I thought it is what supposed to be.
I'm using the cli on linux, and there's always a `./` that's prepended to the argument path. Is this a bug ?

**Comment by haoadoresorange** [comment]
Thanks ! And thanks so much for the work ! I'm using it to minify my static blog. The most reliable tool I've tried so far. However it took me a while to find it, it's burried in google search result.

**Comment by tdewolff** [comment]
Thanks so much! Great to hear it's so useful to you ;-). I know it is kind of buried on Google, would be useful to get people to blog about minify haha

**Comment by haoadoresorange** [comment]
That's good ! I'm writing a blog about how I built my blog, I will link to minify (I just started so I dont have hug reads tho (: but hope it helps in anyway it can)
