### ISSUE TITLE
Changing <, <= to >, >= may change behavior

### ISSUE THREAD

**Issue by Arkerthan** [tdewolff/minify#462]
When both sides of the comparison modify the same variable, changing <, <= to >, >= may change behavior.

Take this function for example:

```js
function test () {
	let stack = [1,2];
	return stack.pop() < stack.pop()
}
```

It returns `false`.

It minifies to `function test(){let e=[1,2];return e.pop()>e.pop()}`, expanded:

```js
function test(){
	let e = [1,2];
	return e.pop() > e.pop()
}
```

It returns `true`.

**Comment by tdewolff** [comment]
Great point, the actual gain for GZIP compression is so low that we're going to skip this optimization altogether.

**Comment by Arkerthan** [comment]
Thanks for the quick fix!
