### ISSUE TITLE
Update Ubuntu package

### ISSUE THREAD

**Issue by rootwork** [tdewolff/minify#464]
I was trying to figure out why the flags I was able to use in my locally-installed package on Ubuntu (actually Linux Mint) differed from the help documents and then I realized it was 5 minor versions out of date -- [2.5.2](https://packages.ubuntu.com/focal/minify) vs [2.10.0](https://github.com/tdewolff/minify/releases).

I ended up just downloading the binary, but if you get a chance could you publish a newer version to the Ubuntu repo?

Thanks!

**Comment by tdewolff** [comment]
Thanks for the suggestion, however I do not maintain the Ubuntu repositories and I'm not sure how to update the library there. In fact, it seems they pin to a version of minify depending on the version of Ubuntu you're running. E.g.:

- bionic (18.04LTS): 2.1.0
- focal (20.04LTS): 2.5.2
- hirsute (21.04): 2.7.2
- impish (21.10): 2.7.2
- jammy: 2.9.22

Not sure if there is anything I can do...

**Comment by rootwork** [comment]
Interesting, OK. Maybe then worth adding a note to the Ubuntu/Debian section of https://github.com/tdewolff/minify/blob/master/cmd/minify/README.md ? Seems like downloading the binary directly is the better way to go.

**Comment by tdewolff** [comment]
Looks like `kinetic` will update `minify` to `v2.11.10`
