### ISSUE TITLE
JS: Incorrect renaming variables

### ISSUE THREAD

**Issue by malcom** [tdewolff/minify#469]
Probably the new/rewritten JS variable renamer introduced in v2.9.27 have some bugs that can lead to unexpected behavior in minified code.

The issue is observable and reproducible on [minified `Hyphenopoly_Loader.js`](https://raw.githubusercontent.com/mnater/Hyphenopoly/47e070ad5909d61304ea942bba7588e13b565277/docs/min/Hyphenopoly_Loader.js) file, for example some mismatched names:
```
source: s.res.he.set(t,{w:e.fetch(s.paths.patterndir+n,{credentials:s.s.CORScredentials})}),g.set(n,t)};
2.9.26: a.res.he.set(b,{w:n.fetch(a.paths.patterndir+c,{credentials:a.s.CORScredentials})}),m.set(c,b)};
2.9.27: e.res.he.set(t,{w:e.fetch(e.paths.patterndir+n,{credentials:e.s.CORScredentials})}),h.set(n,t)};
        ^                 ^       ^ ...
```

**Comment by ShaneMcC** [comment]
I ran a `git bisect` on this - and fb5ce737b24885f08ed63bc67d5fad6fc18d1cb7 is the commit that introduced the broken behaviour - so it is indeed the new variable renamer.

**Comment by jmooring** [comment]
This appears to be a whitespace problem. If I reformat the OP's example in vscode, then minimize, vars are renamed correctly.

**Comment by tdewolff** [comment]
Thanks for the bug report, I will be looking into this!

**Comment by tdewolff** [comment]
This has been fixed in https://github.com/tdewolff/parse/commit/3a696f877e23726368415e6f513bb397e61dd0df, a new released will be out soon as I have some other outstanding work

**Comment by tdewolff** [comment]
This has been fixed and released in v.2.11.0!
