### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#471]
If would be helpful to see the commit hash of both minify and parse when visiting https://go.tacodewolff.nl/minify.

I'd rather not create a new issue if it has already been resolved in HEAD of either minify or parse.

**Comment by tdewolff** [comment]
Great idea, I've added the version of minify in the first text line as it was running fairly outdated (at v2.9.17). I don't think it is desired to let it run on HEAD directly though.
