### ISSUE TITLE
JS minify: incorrect assignment order 

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#472]
source

```
(function() {
  var foo = bar;
  var baz = foo.wibble, quz = foo.wobble;
})();
```

2.9.29 (correct)

```
(function(){e=bar;var e,t=e.wibble,n=e.wobble})()
```

2.10.0 (incorrect)

```
(function(){var t=e.wibble,n=e.wobble,e=bar})()
```

**Comment by tdewolff** [comment]
Hi Joe, thanks for reporting. This is a high priority issue, I'm looking into it.

**Comment by tdewolff** [comment]
Should be fixed now, waiting for some outstanding work to be incorporated to release a new version.
