### ISSUE TITLE
JS: breaking error

### ISSUE THREAD

**Issue by elandorr** [tdewolff/minify#474]
If this [^1] file is minified it bricks with: 
`Uncaught TypeError: e.indexOf is not a function`

(Yes, it's already minified, but it's part of a bundle, and I tried it standalone too.)

[^1]: https://moment.github.io/luxon/es6/luxon.min.js

Terser handles it fine, so it must be a bug in 'minify'.

**Comment by tdewolff** [comment]
Thanks for the bug report, can you please attach a small piece of JS code that you invoke reproducing the error?

**Comment by tdewolff** [comment]
This may be fixed in v2.11.0, can you please verify?

**Comment by elandorr** [comment]
No, it's still broken. I'm sorry for the delay, life has been absolute horror ever since dictatorships took over in the west. Let me make you a reproducible example now.

(It was a lot harder to strip down than anticipated, but now I can trigger it in a few lines.)

We start with

```
luxon-es6.min.js from upstream
test.html
index.js
```

`test.html`
`<script type="module" src="bundle-minify.js"></script>`

`index.js`
```js
import { DateTime } from "./luxon-es6.min.js";

let locale = "en";

function convertAll() {
    DateTime.fromSeconds(1649442485).setLocale(locale);
}
document.querySelector("body").addEventListener("input", convertAll);
```
(doesn't make any sense of course, I stripped it as much as possible)

As it's a module it needs a server, but who am I telling, you're the pro here.

We bundle it:
`rollup index.js --file bundle.js --format es --compact`

We minify:
`minify.exe bundle.js -o bundle-minify.js`

and we get a bricked file with a different error now:
`Uncaught SyntaxError: redeclaration of var l`

Meanwhile this works fine:

`terser bundle.js -cm --module --toplevel --ecma 2015 -o bundle-terser.js`

I have no clue how to even debug something like the insanity that is minification. All I know for sure is that 'minify' (an absolutely un-findable name by the way) is wicked fast, at only a little bit of compression lost compared to the others. I'm just a very small time amateur, but it'd be a 'nice to have' tool. Hope this helps!

**Comment by tdewolff** [comment]
Thanks for passing the code. I've been trying to get this running just by calling `DateTime.fromSeconds(1649442485).setLocale(locale);` in a simple HTML page. I've included the luxon file as above, and separately as a minified file (minified by this minifier). Both cases it seems to work fine for me. You are sure that you minified the file you attached above, and not the already broken file you must have on your file system, right?

At which position is the redeclaration error in the minified file? Could you pass me the minified file that gives you that error?

**Comment by elandorr** [comment]
Yes, I'm certain. Here it's packed: https://tmpfiles.org/dl/258762/minify_test.7z.
You can verify with the commands 1:1, and you need to include the eventlistener line. Without it, I suppose rollup will remove it altogether as it's never called.

**Comment by tdewolff** [comment]
Now I was able to track it down :-), thanks! Please let me know if this works for you as well

**Comment by elandorr** [comment]
Not only is your tool fast, you are too! Works fine now, thank you!
