### ISSUE TITLE
HTML: scheme data validation error 

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#475]
We have an SVG element:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y="90" font-size="90">A</text></svg>
```

This is encoded into a `link` element's `href` attribute using the `data` URI scheme:

```
<link rel="icon" href="data:image/svg&#43;xml,%3csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20100%20100%22%3e%3ctext%20y=%2290%22%20font-size=%2290%22%3eA%3c/text%3e%3c/svg%3e">
```

When minified, `%20` is replaced by spaces:

```
<link rel=icon href="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22%3E%3Ctext y=%2290%22 font-size=%2290%22%3EA%3C/text%3E%3C/svg%3E">
```

The resulting page does not validate on `https://validator.w3.org/`:

> Illegal character in scheme data: space is not allowed

**Comment by tdewolff** [comment]
The specification isn't 100% clear on which characters are allowed and which not, see e.g. https://github.com/tdewolff/minify/issues/180#issuecomment-559581401. Browsers seem to differ in their implementation, and so do data URI generators. Actually, the following HTML file shows up fine in Firefox and Chrome:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test</title>
</head>
<body>
    <img src="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22%3E%3Ctext y=%2290%22 font-size=%2290%22%3EA%3C/text%3E%3C/svg%3E">
</body>
</html>
```

I'll ask in the original issue at Hugo which browser is causing the issue.

**Comment by jmooring** [comment]
<https://datatracker.ietf.org/doc/html/rfc2396#section-2.4>

> Data must be escaped if it does not have a representation using an unreserved character

The space character does not have a representation using an unreserved character.

**Comment by tdewolff** [comment]
Well, the following are not allowed in any URL/URI: `non-printables, space, <, >, #, %, "`. Additionally, the following are unwise (and disallowed only by IE11): `\, [, ], ```, {, }, |, ^`. Another fact is that the specification never mentions that a space may be represented as a `+` in any URL/URI (which we were doing), so I've changed that as well to `%20`. See:

- https://github.com/tdewolff/parse/commit/7054e8cae76c462bff6f871ad4c88eb29e9275ee
- https://github.com/tdewolff/parse/commit/8a4cf11dbf6ce767b34e0f165d1640a20d1834db
- https://github.com/tdewolff/parse/commit/7ecf472dc39043f2f4d09bc82c8bcba5add8893c

**Comment by tdewolff** [comment]
This has been fixed and released in v.2.11.0!
