### ISSUE TITLE
Integrated into webpack?

### ISSUE THREAD

**Issue by nyngwang** [tdewolff/minify#476]
As title. I'm coming from a repo showing that this minifier is working very well compared to the other ones. I did some search but I haven't found a webpack plugin that bridges it. Any idea?

(Sorry for probably being an inappropriate question since I don't have much background knowledge).

**Comment by tdewolff** [comment]
I'm not a user of webpack, but I'll look into creating a plugin, thanks for the idea!

**Comment by tdewolff** [comment]
Work has been put in #379 to support a JS binding natively. It should already compile and build, if anyone's interested in making a webpack plugin I'd be happy to help!

**Comment by tdewolff** [comment]
Official JS bindings have been released to https://www.npmjs.com/package/@tdewolff/minify from v2.12.0 onwards.
