### ISSUE TITLE
JS minify problem

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#479]
Source

```js
if (!(0 < 1 && 1 < 2)) {
  throw new Error('this is impossible');
}
```

2.10.0 (PASS)

```js
if(!(0<1&&1<2))throw new Error("this is impossible")
```

2.11.0  or 2.11.1 (FAIL)

```js
if(!0<1||!1<2)throw new Error("this is impossible")
```

The logical NOT (`!`) operator has higher precedence than comparison operators, so the above is the same as:

```js
if(true<1||false<2)throw new Error("this is impossible")
```

**Comment by tdewolff** [comment]
Thanks for the trimmed down example! Should be fixed now, please let me know if it works :+1:

**Comment by jmooring** [comment]
@tdewolff Thank you; works as expected. Please create a new release when you have a moment.

**Comment by tdewolff** [comment]
Done!
