### ISSUE TITLE
Minify breaks setters with unused arguments

### ISSUE THREAD

**Issue by Arkerthan** [tdewolff/minify#481]
Take this valid javascript:

```js
class Test {
	set x(e) {
		throw  Error("Operation not supported");
	}
}
```

It minifies to `class Test{set x(){throw Error("Operation not supported")}}`, expanded:

```js
class Test {
	set x() {
		throw Error("Operation not supported");
	}
}
```

which is invalid javascript.

**Comment by tdewolff** [comment]
Thanks for the report, should be fixed now on master.
