### ISSUE TITLE
[maybe non issue] recurse into files and minify further

### ISSUE THREAD

**Issue by maraisr** [tdewolff/minify#482]
Given the html;

```html
<!-- some html here -->
<script type=module>
const my_long_var = 'something not minified';
</script>
<!-- more html here -->
```

And I run;

`minify -vrs build/ -o .`

Can the output recurse into that script tag, and minify it as though it was a `.js` file.

to produce _something like_;

```html
<!-- some html here (not a comment) -->
<script type=module>var x = 'tiny thingy now';</script>
<!-- more html here (not a comment) -->
```

**Comment by tdewolff** [comment]
That is because your mimetype for the script is module, which is not automatically understood to be JS. Should now be fixed, thanks for the issue!

**Comment by maraisr** [comment]
Thank you ever so much for fixing this! <3 and thanks for the lovely util!

**Comment by maraisr** [comment]
Thanks again, do you think similar to supporting the module type in html files that `my-file.mjs` files can also be minified?

**Comment by maraisr** [comment]
You're on absolute fire @tdewolff 🚀🚀
