### ISSUE TITLE
minifier.Add Error

### ISSUE THREAD

**Issue by teschste-reyrey** [tdewolff/minify#483]
In existing code, I had the following that had been working fine:

`

	var minifier *minify.M

	minifier = minify.New()
	minifier.Add("text/html", &html.Minifier{KeepEndTags: true})
`

However I just downloaded the latest versions of minify and minify/html and now, on "&html.Minifier{KeepEndTags: true}", I am getting the following error:

`
cannot use &(html.Minifier literal) (value of type *html.Minifier) as minify.Minifier value in argument to minifier.Add: wrong type for method Minify (have func(m *invalid type, w io.Writer, r io.Reader, _ map[string]string) error, want func(*github.com/tdewolff/minify.M, io.Writer, io.Reader, map[string]string) error)
`

According to the documentation, this should still work.

Has something changed and the doc not been updated or is this broke?

Thanks!

**Comment by tdewolff** [comment]
I think there must be something off at your end, since it works fine and nothing has changed. Especially since your error mentions `invalid type` I think your setup has an error. Are you sure import `github.com/tdewolff/minify/v2` (note the `v2`)? Are you using Go modules? Make sure to update to the latest version.

**Comment by teschste-reyrey** [comment]
Due to internal issues, I am not currently using modules, that support is planned for later this year.  That being said, I have tried completely unloading and reloading minify multiple times and it seems to be hit and miss.  At the moment I have it working and have been able to compile my application.  Hopefully it will stabilize after we move to modules, so I do not have to find an alternate solution.
Thanks for looking at it!
