### ISSUE TITLE
single quotes escaped in js minify

### ISSUE THREAD

**Issue by gyuber** [tdewolff/minify#485]
Hi.

I minify html + js, But the single quotes are escaped
see my code ( https://go.dev/play/p/KBD5FkLWW3w ) 
how to keep single quotes?

Thanks!
```go
package main

import (
	"fmt"
	"regexp"

	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/html"
	"github.com/tdewolff/minify/v2/js"
)

func main() {
	m := minify.New()
	m.Add("text/html", &html.Minifier{
		KeepQuotes:   true,
		KeepEndTags:  true,
		KeepComments: true,
	})

	m.AddFuncRegexp(regexp.MustCompile("^(application|text)/(x-)?(java|ecma)script$"), js.Minify)

	tag := `<a onclick="click('a')">`
	s, err := m.String("text/html", tag)
	if err != nil {
		panic(err)
	}
	fmt.Println(s)
}
```

```
<a onclick="click(&#34;a&#34;)">
```

**Comment by tdewolff** [comment]
Hm, not sure what is going on, since it seems to work fine for me: https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmh0bWwmaHRtbC1rZWVwY29tbWVudHM9b24maHRtbC1rZWVwZW5kdGFncz1vbiZodG1sLWtlZXBxdW90ZXM9b24mc3JjPSUzQ2Erb25jbGljayUzRCUyMmNsaWNrKCdhJyklMjIlM0U=

Do you have the latest version?

**Comment by tdewolff** [comment]
Sorry, you were right. There were actually three bugs, not one! All are fixed, please reopen if you still have problems.

**Comment by gyuber** [comment]
oh! problem has been solved!
Thank you
