### ISSUE TITLE
blockStmt.Scope.NumForDeclared undefined (type "github.com/tdewolff/parse/v2/js".Scope has no field or method NumForDeclared)

### ISSUE THREAD

**Issue by leewithyuan** [tdewolff/minify#486]
blockStmt.Scope.NumForDeclared undefined (type "github.com/tdewolff/parse/v2/js".Scope has no field or method NumForDeclared)
github.com/tdewolff/minify/v2@v2.11.3/js/js.go:424

**Comment by tdewolff** [comment]
Please downgrade to parse@v2.5.30
