### ISSUE TITLE
Incorrectly discarding group in if-condition

### ISSUE THREAD

**Issue by cixtor** [tdewolff/minify#487]
I encountered a problem where [minify v2.11.7](https://github.com/tdewolff/minify/releases/tag/v2.11.7) (latest version as of now) discards groups in if-conditions.

### Source

```js
if ($(".K").length) {
    let timer = setInterval(function () {
        $(".K").text(timeNow());
    }, 1000);
}
```

### Expected Output

```js
if($(".K").length){let timer=setInterval(function(){$(".K").text(timeNow())},1e3)}
```

### Current Output

```
<empty>
```

### Additional Notes

Individual pieces of code minify correctly, as you can see below:

```js
if ($(".K").length) {
    console.log("K");
}
let timer = setInterval(function () {
    $(".K").text(timeNow());
}, 1000);
```

```js
$(".K").length&&console.log("K");let timer=setInterval(function(){$(".K").text(timeNow())},1e3)
```

[Commit 6561da2](https://github.com/tdewolff/minify/commit/6561da27ad89acf3ae0b4b154054b269daf18a86) apparently addresses a similar issue, but does not fix it completely.

**Comment by tdewolff** [comment]
Thanks for the detailed bug report! I would actually expect a different output since the `let` variable is never used (and only defines a variable in the if scope). However, the value it is given may have side-effect we should not remove. So I'd expect:

```js
$(".K").length&&setInterval(function(){$(".K").text(timeNow())},1e3)
```

**Comment by tdewolff** [comment]
Should  work now, please let me know if you still experience problems
