### ISSUE TITLE
JS public static class fields

### ISSUE THREAD

**Issue by intrnl** [tdewolff/minify#488]
[Online demo](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmphdmFzY3JpcHQmanMtcHJlY2lzaW9uPTAmc3JjPWNsYXNzK0NvbXBvbmVudCslN0IlMEQlMEErK3N0YXRpYytvYnNlcnZlZEF0dHJpYnV0ZXMrJTNEK2ZvbyUzQiUwRCUwQSU3RCUwRCUwQQ==)

It seems that public static fields aren't supported yet.

```js
export class Component {
  static observedAttributes = [];
}
```

throws this parsing error, happens on v2.11.9 and v2.11.3 (online demo)

```
expected ( instead of = in method definition on line 2 and column 29
    2:   static observedAttributes = foo;
                                   ^
```

**Comment by tdewolff** [comment]
Added support! Thanks for the issue.
