### ISSUE TITLE
Html minifier is not respecting self closing tags

### ISSUE THREAD

**Issue by geekyme-fsmk** [tdewolff/minify#492]
Example [here](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmh0bWwmaHRtbC1rZWVwZW5kdGFncz1vbiZodG1sLWtlZXBxdW90ZXM9b24mc3JjPSUzQ3RhYmxlK2RhdGEtbGF5b3V0JTNEJTIyZGVmYXVsdCUyMiUzRSUwRCUwQSsrJTNDY29sZ3JvdXAlM0UlMEQlMEErKysrJTNDY29sK3N0eWxlJTNEJTIyd2lkdGglM0ErMTI1cHglMjIrJTJGJTNFJTBEJTBBKysrKyUzQ2NvbCtzdHlsZSUzRCUyMndpZHRoJTNBKzYzNXB4JTIyKyUyRiUzRSUwRCUwQSsrJTNDJTJGY29sZ3JvdXAlM0UlMEQlMEElM0MlMkZ0YWJsZSUzRSUwRCUwQQ==) - 

The expected result should be:

```
<table data-layout="default"><col style="width:125px" /><col style="width:635px" /></table>
```

But the `/>` were stripped away.

**Comment by geekyme-fsmk** [comment]
It works fine when I select [XML as the type](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRnhtbCZzcmM9JTNDdGFibGUrZGF0YS1sYXlvdXQlM0QlMjJkZWZhdWx0JTIyJTNFJTBEJTBBKyslM0Njb2xncm91cCUzRSUwRCUwQSsrKyslM0Njb2wrc3R5bGUlM0QlMjJ3aWR0aCUzQSsxMjVweCUyMislMkYlM0UlMEQlMEErKysrJTNDY29sK3N0eWxlJTNEJTIyd2lkdGglM0ErNjM1cHglMjIrJTJGJTNFJTBEJTBBKyslM0MlMkZjb2xncm91cCUzRSUwRCUwQSUzQyUyRnRhYmxlJTNFJTBEJTBB).

**Comment by tdewolff** [comment]
I think you mean it strips `/` (but not `/>`)? That is exactly what it should do. Common usage of the `<col>` tag is without the closing or self-closing tag. Self-closing is still allowed though by the HTML specification for legacy reasons. Remember, HTML is not XML!

Is this causing an issue for you?

**Comment by geekyme-fsmk** [comment]
Ah got it. Yes it's causing an issue when I upload HTML to confluence cloud. They require the self closing tags to be present.
