### ISSUE TITLE
keep the html tag if a lang is present

### ISSUE THREAD

**Issue by elandorr** [tdewolff/minify#498]
I read #289 and would like to hear your opinion, as you made probably the most well-researched minifier.

The validator warns about a lack of it, and it seems logical to keep it if a language is set as minification shouldn't remove content.

Or is there another way to set a document wide language that works?

I researched a little and found that even HTTP headers are to be disregarded by the UA. (and setting custom HTTP headers when dealing with multilang static pages is unreasonable anyhow) It sure looks like the html tag is at least semantically 100% required just for setting the lang.

Your take?

I love how you even looked into little things so I'd rather not just disable the tag omission feature.

Cheers

**Comment by elandorr** [comment]
I'm sorry, just noticed you already keep that in mind. Great work, you sure put a lot of love in it!

Thank you.

**Comment by tdewolff** [comment]
Thanks for the kind and encouraging words! I'm happy to hear you enjoy using the minifiers ;-)

Yes, when attributes are present the `html` tag will not be omitted, you can check here: https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmh0bWwmc3JjPSUzQ2h0bWwrbGFuZyUzRCUyMmVuJTIyJTNF

Thanks for the research though! If you ever come across anything I'd be happy to hear to keep improving the minifiers :-D
