### ISSUE TITLE
JavaScript static variables not supported

### ISSUE THREAD

**Issue by fschr** [tdewolff/minify#513]
minimal example of something that is not supported but should be:

```
class A {
    static foo = 'bar';
}
```

minifying that code snippet will give the error:

```expected ( instead of = in method definition on line 2 and column 17```

but this is valid javascript and should be able to be minified.

**Comment by tdewolff** [comment]
This was introduced in v2.11.10, please update to the latest version. See https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmphdmFzY3JpcHQmanMtcHJlY2lzaW9uPTAmc3JjPWNsYXNzK0ErJTdCJTBEJTBBKysrK3N0YXRpYytmb28rJTNEKydiYXInJTNCJTBEJTBBJTdE for an example showing it works at the latest version. If there are further questions, don't hesitate to reopen!
