### ISSUE TITLE
JS: private class methods

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#514]
Private class methods are unsupported (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

Code:
```js
class ClassWithPrivateMethod {
  #privateMethod() {
    return 'hello world';
  }
  static #privateStaticMethod() {
    return 'hello world';
  }
}
```

result:
```
expected Identifier, String, Numeric, or [ instead of ( in method or field definition on line 2 and column 17
    2:   #privateMethod() {
                       ^

```

**Comment by Toffee1347** [comment]
It seems this has since broken again. If you put `class a { #a(){} }` (from the tests) into https://go.tacodewolff.nl/minify you get the same error as before
