### ISSUE TITLE
BUG: HTML removed html tags

### ISSUE THREAD

**Issue by eddyxu** [tdewolff/minify#52]
minify seems to remove html tags. 

```go
# Input HTML
h := `
	<html><body>
	<p>  this is a hello world.  </p>
	</body></html>
`
```
```
# Output
b, _ := minify.Bytes(m, "text/html", buf.Bytes())
println("MINIFY: [" + string(b) + "]")
```

`MINIFY: [<p>this is a hello world.]`

Also tried on the "PI 2 online live demo" site, the result is the same.

**Comment by tdewolff** [comment]
That is intended behaviour, see http://www.w3.org/TR/html5/syntax.html#optional-tags

Why do you think this is a bug? Does your website break?

**Comment by eddyxu** [comment]
Ok. Thanks for the clarifications. It could be my misunderstanding of how it works.
