### ISSUE TITLE
Expose writer to allow package abstraction

### ISSUE THREAD

**Issue by chr1sto14** [tdewolff/minify#524]
#### Problem:

Abstracting the M.Writer method to allow for easier testing, but the private `writer` prevents this code pattern.

```golang
type MinifyWriter interface {
  Writer(mediatype string, w io.Writer) *minify.writer
}
```

#### Request:

Either make the `writer` public `Writer`. Or change the method signature to
```golang
func (m *M) Writer(mediatype string, w io.Writer) io.WriteCloser
```

**Comment by tdewolff** [comment]
Good suggestion, it now returns `io.WriteCloser` so as to not clutter the API with the writer.
