### ISSUE TITLE
js: New nilpointer

### ISSUE THREAD

**Issue by bep** [tdewolff/minify#528]
I don't have a simple reproduceable for you, but this issue is pretty informative:

https://github.com/gohugoio/hugo/issues/10230

This happened after this deps upgrade:

https://github.com/gohugoio/hugo/commit/60ede146b613100286144bd110e697334cab9902

**Comment by anthonyfok** [comment]
See also https://github.com/tdewolff/parse/commit/e61ad7abb4fac5fc29271320a0e9a6e5ee8abb21 for the main part of the code fix
