### ISSUE TITLE
“\n” not minified in inside backticks

### ISSUE THREAD

**Issue by zrajm** [tdewolff/minify#529]
First, I found it cool that minify minifies `\n` – then I noticed some inconsistencies. When running the following through minify,  (e.g. on the web page https://go.tacodewolff.nl/minify):

    console.log('\n', `\n`)

I get

    console.log(`
    `,`\n`)

But I expected to get:

    console.log(`
    `,`
    `)

The `\n` occurring in the backtick quote is never minified. (While the one which was in a single quote to begin with is turned into a backtick quote and minified, just like one would expect.)

**Comment by tdewolff** [comment]
Great observation, I've implemented proper minification of template literals. Thanks!
