### ISSUE TITLE
JS: semicolon syntax errors in output

### ISSUE THREAD

**Issue by nwidger** [tdewolff/minify#53]
Running JQueryUI v1.11.4 file through the JS minifier using the latest code from `master` generates a file with syntax errors.  Here is a gist with the file before and after being run through the minifier:

https://gist.github.com/nwidger/616248f0c8bdd7d7a513

While not the only error, this is the first error that Firefox spits out:

```
SyntaxError: expected expression, got ')' jquery-ui.min.js:1:73117
```

It looks to me like the semicolon removal algorithm is a little too greedy.  A `for` loop goes from looking like this:

``` js
for(g=1,v=y;;){...}
```

to this:

``` js
for(g=1,v=y;){...}
```

Trying to evaluate this code in Firefox's JS console gives me a syntax error:

``` js
for(g=1,v=y;){}
SyntaxError: expected expression, got ')'
```

**Comment by tdewolff** [comment]
Yes, that was a recent change that shouldn't have made it to `master`. I have reverted the changes in #54, let me know if this works for you!

I am working on a JS parser to enable much better JS minification, including (working) semicolon omission and variable renaming. In the meanwhile this JSmin port should work!

**Comment by nwidger** [comment]
Thanks so much for the quick response!  I’ll verify the fix on Monday.  :)

**Comment by nwidger** [comment]
Looks like the fix worked.  Thanks again!
