### ISSUE TITLE
Option to disable removing trailing skew (or transform) unit

### ISSUE THREAD

**Issue by ciaranevans-xydus** [tdewolff/minify#533]
If I have a transform statement like:
```css
transform: skew(20deg,0deg)
```

When I use `minify`, the output is rather:
```css
transform: skew(20deg,0)
```

The lack of the unit in the Y field is causing errors downstream in other tooling, having to go through and replace all `0)`'s with `0deg)` is a bit of a pain 😛

**Comment by tdewolff** [comment]
Actually `transform:skew(20deg)` would be an even shorten and valid notation, but both should be valid. The parameters are of type [`<angle>`](https://developer.mozilla.org/en-US/docs/Web/CSS/angle) which explicitly states that the unit is optional after the `0`. The other tooling seems to fail to parse valid CSS, would it be possible to raise a bug report there?

**Comment by ciaranevans-xydus** [comment]
Yeah sorry, CSS noob here. I agree, it is valid so _should_ handle it.

But, the removal is strange 😛

**Comment by tdewolff** [comment]
Hehe I don't think it is strange, it's the job of a minifier! ;-)
