### ISSUE TITLE
Regression in 2.12.1

### ISSUE THREAD

**Issue by perrin4869** [tdewolff/minify#537]
Running `2.12.2` on my application I found that trying to minify https://github.com/kriszyp/json-schema/blob/master/lib/validate.js was failing.
It worked on `2.12.0` but fails on `2.12.1`.
Maybe it was introduced in https://github.com/tdewolff/minify/commit/2d24fc4cc3c0a552de8dcee3ca6f6a0941681b90 ?
Seems like a very tricky issue ^^;;

**Comment by tdewolff** [comment]
Yes you're right, this is a bug. The fact is that the specification is quite unclear about this, I don't really understand it at least.
