### ISSUE TITLE
Regression in template literals in 2.12.2

### ISSUE THREAD

**Issue by perrin4869** [tdewolff/minify#538]
There was a regression introduced in https://github.com/tdewolff/minify/commit/6923a736f60b83d3274ddec7d402a62624d3801f

Having `foo.js`:
```js
const foo = 'hello world';
console.log(`$${foo}`);
```

```
$ node foo.js
$hello world
```

With `minify@2.12.1`:

```
./minify --mime application/javascript foo.js | node
$hello world
```

Under `minify@2.12.3`:

```
./minify --mime application/javascript foo.js | node
`hello world
```

**Comment by tdewolff** [comment]
Thanks for the issue, found another related bug and fixed both.

**Comment by perrin4869** [comment]
No, thank you!!!
