### ISSUE TITLE
Removing unused catch params breaks JS on older Apple devices

### ISSUE THREAD

**Issue by kamermans** [tdewolff/minify#540]
Hi, thanks for all your hard work!

I noticed you recently removed try/catch params if there are no parameter bindings: https://github.com/tdewolff/minify/commit/2e77ff31bcd4eab25e4afc058c4a521384be68b0

This produces statements like this:
```javascript
try {
   1/0
} catch {
   console.log('Oops!')
}
```

This code is valid in most browsers, but not in older Apple devices (Safari on desktop or iPhones / iPads).  So far this is the only incompatibility I've noticed when minifying JS for these platforms, and my only workaround is to explicitly reference the parameter so the minifier doesn't drop the param.

Here's what it looks like in a Safari console:
![image](https://user-images.githubusercontent.com/266265/199272097-2f117487-0f4d-40ed-b3d0-08935ce34c69.png)

I'm not sure what level of compatibility you're aiming for, but if we could put this behind a flag or handle it differently, that would be great!

I am a Go developer, so if you'd like a PR, just let me know what path you'd like to go down.

**Comment by kamermans** [comment]
This problem might be more widespread than I first though.  According to the sites I've checked, `Optional Catch Binding` was introduced in ES10 in 2019.

![image](https://user-images.githubusercontent.com/266265/199332934-2d789bbe-bf18-4db7-9eac-2d1f834e6e79.png)
https://caniuse.com/mdn-javascript_statements_try_catch_optional_catch_binding

**Comment by tdewolff** [comment]
Thanks for the issue, this should now be fixed by passing the `Version = 2018` option to the JS minifier.

**Comment by kamermans** [comment]
Awesome, thanks @tdewolff!
