### ISSUE TITLE
Case its important sometimes

### ISSUE THREAD

**Issue by BLLuis** [tdewolff/minify#541]
For many embedded devices, were the use of minify its very important due to low memory availability, the case of some objects or labels its very important too, for example in tpl files used in web pages on some of the devices we use a lot of labels like #SomeLabelId# or tags like @TagId@ and the code inside, usually C or C++, its expecting the label/tag in the same case, I see no cmd ñline option for preserve case.

Could you add a option for this requirement?
Thanks

**Comment by tdewolff** [comment]
What minifier do you refer to? Is this for CSS or HTML? Labels or tags for what, do you have an example?

**Comment by BLLuis** [comment]
Sorry to not explain tpl files (I been using for more than 20 years), many embedded devices use tpl files like html files, but they are processed on the board (server side) before sent to client as html code, the process consist of replace special tags with values, for example:

`
%MCSL% replaced with 250
%HTMLCHK_syslogEnabled% replaced with checked
`

This kind of file have many tags inside that are replaced before sent, here a fragment as example:

`<h3>Syslog</h3>
Server:<input type="text" name="syslogServer" maxlength="%MCSL%" value="%syslogServer%"/>
<input type="checkbox" name="syslogEnabled" %HTMLCHK_syslogEnabled%/><span> Enabled</span>`

After minify:

`<h3>Syslog</h3>Server:<input name=syslogServer maxlength=%MCSL% value=%syslogServer%>
<input type=checkbox name=syslogEnabled %htmlchk_syslogenabled%>`

Note that the case of the MCSL and syslogServer tags were preserved while the
HTMLCHK_syslogEnabled was changed to lowercase, I think that because the first two ones are html values for properties while the last one its just a text inside a tag. I see some other tpl files (not mines) that use tags like this:  [tag] {tag} @tag@.
For every tag in this example, value or free text, the case its important.

Despite my request or my examples or just my problem, I think that the case should be preserved no matter the type of input file or text inside.

Let me know if you need more info.

Thanks

**Comment by tdewolff** [comment]
Thanks for clarifying! Unfortunately there is no TPL minifier (yet), and passing a TPL file to the HTML minifier is a very bad idea. Even though TPL looks like HTML (and is converted to it), it is still not trivial for all edge cases to be covered. There have been many requests though, and I'd like to create a TPL minifier that can accept any type of begin/end tags (such as `%`, `<?php`, `?>`, ...)

**Comment by BLLuis** [comment]
Thank you but Im not asking for a tpl minifier, just a option to NOT change case in html files, something like --html-preserve-case, if its too complex to implement it could be --html-preserve-case-of-unknown-things, hehehe, the last one its a joke, never mind, thanks that exists some others minifiers, anyway Im still using this one and made a script to search for tags in destination files then replaced by original tags PRESERVING case.
