### ISSUE TITLE
How to filter <script> tags in Html.Minify

### ISSUE THREAD

**Issue by amourjun** [tdewolff/minify#543]
Hi，
  There are some"<script type="text/html">" tags on my page, I don't want to minify it.
  How do I filter out <script> tags in the case of ”AddFunc("text/html", html.Minify)“ ？

**Comment by tdewolff** [comment]
You can't selectively minify some part of the document. If minifying the
content of that script tag is invalid, it is probably not text/html, but
perhaps some sort of template script?

**Comment by amourjun** [comment]
> 

Yes, those template scripts are working. Am I not able to use minify in this case

**Comment by tdewolff** [comment]
No, because you misspecified the MIME type of your template scripts, this may actually break in other cases as well. I recommend fixing the mime type to represent that correct template language you use, that way you can continue using minify.
