### ISSUE TITLE
Build & Release  shared libraries

### ISSUE THREAD

**Issue by JKamsker** [tdewolff/minify#544]
Hey,

I am currently building a .net wrapper for minify. 
Therefore i would need the shared libraries for all the arches of linux, windows and MacOS.

All supported versions: 

OS | Binaries
-- | --
Linux | Arm32 \| Arm32 Alpine \| Arm64 \| Arm64 Alpine \| x64 \| x64 Alpine
macOS | Arm64 \| x64
Windows | Arm64 \| x64 \| x86
All |  

</body>
</html>

Source: https://dotnet.microsoft.com/en-us/download/dotnet/7.0

A 1:1 copy  of the js binding lib would be enougth

On windows i use ``go build --buildmode=c-shared -ldflags="-s -w"  -o main.dll .\minify.go `` to build a dll which works for me

**Comment by tdewolff** [comment]
Hey, thanks for the issue! What is a .net wrapper? What will it allow? You could use it in C#, F#, ...?

What do you need from me? I think the best way would be to add a build script after each release that would build the arches you need. See the `Makefile` for the `release` command. Adding more targets is easy.

**Comment by JKamsker** [comment]
The wrapper is basically the same as the js bindings, just for c#.
It will be able to be used from every .net language (C#, VB.NET, F#. Since its all the same MSIL).

With it you can use your minifier from any .net based language like this:
```csharp
var type = new MinifierMediaType("text/html");
var unminifiedString = "<span style=\"color:#ff0000;\" class=\"text\">Some  text</span>";
var minified = Minifier.MinifyString(type, unminifiedString);
```


As i said, shared libraries for each arch i listed before would be nice. 
Autobuild and release would give plus points.

I only managed to build one dll for my system (windows/x64) but having all binaries would be crucial for testing.

**Comment by tdewolff** [comment]
What I'm thinking is, given that with Go it is extremely easy to cross-build, can't you just build the other arches on the fly with Go and use that in your binding?

```go tool dist list
aix/ppc64
android/386
android/amd64
android/arm
android/arm64
darwin/amd64
darwin/arm64
dragonfly/amd64
freebsd/386
freebsd/amd64
freebsd/arm
freebsd/arm64
illumos/amd64
ios/amd64
ios/arm64
js/wasm
linux/386
linux/amd64
linux/arm
linux/arm64
linux/loong64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/riscv64
linux/s390x
netbsd/386
netbsd/amd64
netbsd/arm
netbsd/arm64
openbsd/386
openbsd/amd64
openbsd/arm
openbsd/arm64
openbsd/mips64
plan9/386
plan9/amd64
plan9/arm
solaris/amd64
windows/386
windows/amd64
windows/arm
windows/arm64
```

then see the Makefile and do something like

```
VERSION=`git describe --tags`
FLAGS=-ldflags "-s -w -X 'main.Version=${VERSION}'" -trimpath
GOOS=windows GOARCH=arm64 go build ${FLAGS} -o outfile ./cmd/minify
```

**Comment by tdewolff** [comment]
Assuming this issue is fixed with your release of the .NET wrapper? Please re-open if not to find a solution!
