### ISSUE TITLE
HTML entity conversion is over-eager

### ISSUE THREAD

**Issue by JRaspass** [tdewolff/minify#546]
```go
package main

import "github.com/tdewolff/minify/v2/minify"

func main() {
	html, err := minify.HTML("&amp;parameterize")
	if err != nil {
		panic(err)
	}

	println(html)
}
```
Minify un-escapes the `&amp;` like so:
```
$ go run .
&parameterize
```

And then browsers (I've tried Chrome and Firefox) interpret this as the paragraph entity, despite the lack of trailing semicolon:
```
¶meterize
```
Firefox displays this warning when you view source:
![image](https://user-images.githubusercontent.com/184356/206478386-24932571-0d97-4b28-86c9-fb2301e7adb1.png)

https://stackoverflow.com/questions/18689230/why-do-html-entity-names-with-dec-255-not-require-semicolon imples the browsers might be being more forgiving than the actual spec so I'm not sure what heuristic they use but I feel a good idea would be to not unescape entities unless they have whitespace around them? Or just never unescape `&amp;` as that could lead to this cascade.

For context this came up on a Raku website, which like Perl uses a leading ampersand to denote a subroutine.

**Comment by tdewolff** [comment]
Thanks James for the issue, should be fixed now!
