### ISSUE TITLE
Minify regex in markdown format failing

### ISSUE THREAD

**Issue by Ravinou** [tdewolff/minify#549]
Hi, i have a hugo site with documentation. I regularly share in this documentation regular expressions in markdown format (blocks with ```). But I have very often errors in the build because of minify.

For example :

```bash
userTest ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /var/userTest/[[\:xdigit\:]]*/repos/repo[[\:digit\:]]*, /usr/bin/mkdir -p /var/userTest/[[\:xdigit\:]]*/.ssh
```

I have this error : 
```
Error: Error building site: MINIFY: failed to transform "index.js" (application/javascript): unexpected \ in expression on line 158 and column 3552
  158: ...t\\:]]*/repos/repo[[\\:digit\\:]]*, /usr/...
```

My temporary fix is to disable JS with config.toml : 
```
[minify]
  disableJS = true
```

What do you recommend to share regular expressions in markdown format like I do regularly ?

Thanks

**Comment by tdewolff** [comment]
Can you please post the `index.js` it refers to? I don't understand the first code section you posted, what language is that?

**Comment by Ravinou** [comment]
> Can you please post the `index.js` it refers to? I don't understand the first code section you posted, what language is that?

It's the content of a config file (sudoers), it's here on my website : https://borgwarehouse.com/docs/admin-manual/debian-installation/#configure-the-user

**Comment by tdewolff** [comment]
I don't follow, why do you minify that file? That is not JavaScript nor is it `index.js`, so why do you run the minifier over it?

**Comment by Ravinou** [comment]
I use this Hugo Theme : https://getdoks.org/docs/overview/introduction/

Problems occurs on build. Maybe the question is for the maintainers instead of you ?

**Comment by tdewolff** [comment]
I guess so. I need to see the JavaScript input to see how I can resolve the issue. If it is Hugo related, maybe it's best to take it up with them. I fail to see the connection with a configuration file in sudoer.d and a JavaScript file that gets minified...

**Comment by tdewolff** [comment]
From the issue it seems this is not a problem with this library but with another library that uses `minify`, however please re-open if you still think it is!
