### ISSUE TITLE
&gt; unescaped in minify

### ISSUE THREAD

**Issue by gyuber** [tdewolff/minify#556]
hi!  I using minify html + js

but `>` character unescape in html text

share my code
https://go.dev/play/p/qnO6EJfFXfR

```html
<!-- html template result -->
<span>&gt;&lt;</span>

<!-- minify result -->
<span>>&lt;</span>
```

Can you check if it's right?

**Comment by tdewolff** [comment]
Hi, thanks for raising the issue. The behavior of minify is correct in this
case, since the closing bracket cannot be confused with a tag and does not
need escaping. The opening bracket does! Is this causing problems in your
case?

**Comment by gyuber** [comment]
It seems to be a problem if the closing parenthesis is in the attribute.
but testing, it seems to be escaped in the attribute.

Is not escaping  only in the text area of ​​html?

**Comment by tdewolff** [comment]
Exactly!
