### ISSUE TITLE
p > table vs. p + table

### ISSUE THREAD

**Issue by carlmjohnson** [tdewolff/minify#561]
Input:

```html
<p>
one
<table>
</table>
</p>

<p>
two
</p>

<table>
</table>
```

Expected:

```
<p>one<table></table><p>two</p><table></table>
```

Actual:

```
<p>one<table></table><p>two<table></table>
```

**Comment by tdewolff** [comment]
Thanks for the bug report, in March I'll be back to fix the issue

**Comment by tdewolff** [comment]
According to the HTML5 spec this is correct behaviour. The P tag is assumed to close automatically just before the `<table>` tag. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p:

> The start tag is required. The end tag may be omitted if the [<p>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) element is immediately followed by an [<address>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address), [<article>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article), [<aside>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside), [<blockquote>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote), [<div>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div), [<dl>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl), [<fieldset>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset), [<footer>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer), [<form>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form), [h1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [h2](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [h3](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [h4](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [h5](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [h6](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements), [<header>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header), [<hr>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr), [<menu>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu), [<nav>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), [<ol>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol), [<pre>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre), [<section>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section), [<table>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table), [<ul>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul) or another [<p>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) element, or if there is no more content in the parent element and the parent element is not an [<a>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) element.

Is this causing an issue for you?

**Comment by carlmjohnson** [comment]
Go’s x/net/html parser doesn’t interpret it correctly so the bug with them.
