### ISSUE TITLE
Input path goes inside Output path

### ISSUE THREAD

**Issue by EthraZa** [tdewolff/minify#562]
1st run:
`minify --sync --all --recursive --preserve=links,mode,ownership,timestamps --match '\.(css|html|js)$' dir/a/ -o dir/b/`

**dir/b** will get created as expected.

2nd run:
`minify --sync --all --recursive --preserve=links,mode,ownership,timestamps --match '\.(css|html|js)$' dir/a/ -o dir/b/`

It will create **dir/b/a** with the content I would expect in **dir/b**. 

It does not metter  if I add "**/**" at the end of the paths or not. 
If I use **dir/a/\* -o dir/b/**, it will do it right but will ignore the recursive part and will not create/sync the sub directories.

Is it a bug or am I missing something?

**Comment by tdewolff** [comment]
I can't test right now, but it seems correct in sofar it replicates the
behaviour of the cp tool (if not, this is a bug). Your final comment does
sound like something is off, the * should include directories when -r is
set. I can take a look in March!

**Comment by tdewolff** [comment]
I've run some tests, and this behaviour is the same as with `cp -rv dir/a/ dir/b/`. The first run will put the contents of `dir/a` into `dir/b`, but the second run will put the contents of  `dir/a` directory into `dir/b/a`.

The `/` at the end of the path used to be a way to explicitly mean a directory, but this has been removed to be in line with `cp` and could in general be deduced automatically.

As to the final comment about using `dir/a/*`, I've added a subdirectory as `dir/a/sub` and ran `minify -sro dir/b dir/a/*` and indeed there is a problem that when `dir/b` doesn't exist, the contents of `dir/a/sub` appear in `dir/b` the first time, and in `dir/b/sub` the second time. It should be the latter always.

**Comment by tdewolff** [comment]
Fixed the last part by throwing an error that the directory doesn't exist, much like `cp`. Let me know what you think!

**Comment by EthraZa** [comment]
That worked like a charm. Thank you.

The only thing I have noticed but, at least for me, is not a big problem, is that at first run (minify --sync --all --recursive --preserve=links,mode,ownership,timestamps a/* --output b/), the time of directories are not preserved, they get the actual run time - I guess it's because minify is mkdiring they when they does not exist yet.

**Comment by tdewolff** [comment]
I've pushed an update to fix that, please try. Additionally, I've added support for `--preserve=all` which would shorten the command in your case.
