### ISSUE TITLE
CSS nest, bundle, minify files

### ISSUE THREAD

**Issue by edimoldovan** [tdewolff/minify#563]
I am looking for a way to nest, bundle and minify my CSS all this from my Go app if possible. Seems that bundle and minify is possible, but is nesting also possible? And to clarify what I mean I would like the imports below to replced by the contents of the respective files, then bundled and minified into one output file.
```
@import '_root/colors.css';
@import '_root/utopia-space-values.css';
@import '_root/utopia-text-sizes.css';
@import '_root/fonts.css';
```
Is this doable?

**Comment by tdewolff** [comment]
Thanks for contacting. The CSS minifier only minifies content and does not
process commands, including import statements. A separate tool would be
required in order to bundle web packages, including HTML sources, that is
not currently the scope of this tool unfortunately!
