### ISSUE TITLE
JS: private class methods not working

### ISSUE THREAD

**Issue by Toffee1347** [tdewolff/minify#564]
- This issue is the same as #514 (but the issue is happening again, so creating a new issue)
- Private class methods starting with `#` aren't accepted by the JS minifier
- Example:
```JS
class a { #a(){} }
```
- Fails with:
```
expected Identifier, String, Numeric, or [ instead of ( in method or field definition on line 1 and column 13
    1: class a { #a(){} }
                   ^
```

**Comment by kayabe** [comment]
https://go.tacodewolff.nl/minify is using v2.11.11.
latest release (v2.12.4) doesnt have this issue

**Comment by Toffee1347** [comment]
> https://go.tacodewolff.nl/minify is using v2.11.11. latest release (v2.12.4) doesn't have this issue.

Yeah I was using the wrong version in my code, thanks!
