### ISSUE TITLE
Thinking of a more accessible name?

### ISSUE THREAD

**Issue by gwsbhqt** [tdewolff/minify#571]
As the title

**Comment by tdewolff** [comment]
What do you mean?

**Comment by gwsbhqt** [comment]
@tdewolff 
The current name may not be eye-catching, you may need a cooler name. You can refer to, esbuild, swc, vite, etc

**Comment by tdewolff** [comment]
I think the name is fine, it describes exactly what it does. It doesn't need to be eye-catching by its name, it should be eye-catching by the quality and speed it minifies :-)
