### ISSUE TITLE
data:image minify error

### ISSUE THREAD

**Issue by Mckill3r** [tdewolff/minify#575]
Hi
i'm having a issu when using minify. 

My data:image got transform and are now broken : 

Original :
`background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjUiIGhlaWdodD0iMjYiIHZpZXdCb3g9IjAgMCAyNSAyNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyLjc2MDQgMjIuODk1OEw5Ljc0OTM1IDE2LjI3MTVMMy4xMjUgMTMuMjYwNEw5Ljc0OTM1IDEwLjI0OTNMMTIuNzYwNCAzLjYyNUwxNS43NzE1IDEwLjI0OTNMMjIuMzk1OCAxMy4yNjA0TDE1Ljc3MTUgMTYuMjcxNUwxMi43NjA0IDIyLjg5NThaIiBmaWxsPSIjNjRDODk0Ii8+Cjwvc3ZnPgo=) no-repeat left center;
`

After minified : 
`background: url(data:image/svg+xml,%3Csvg+width%3D%2225%22+height%3D%2226%22+viewBox%3D%220+0+25+26%22+fill%3D%22none%22+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath+d%3D%22M12.7604+22.8958+9.74935+16.2715+3.125+13.2604l6.62435-3.0111L12.7604+3.625l3.0111+6.6243+6.6243+3.0111-6.6243+3.0111-3.0111+6.6243z%22+fill%3D%22%2364c894%22%2F%3E%3C%2Fsvg%3E)no-repeat 0`

**Comment by tdewolff** [comment]
What version of `minify` are you using? The `+` bug has been fixed for quite some time, see the following result which replaces spaces with `%20` correctly:

https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmNzcyZjc3MtcHJlY2lzaW9uPTAmc3JjPWRpdiU3QmJhY2tncm91bmQlM0ErdXJsKGRhdGElM0FpbWFnZSUyRnN2ZyUyQnhtbCUzQmJhc2U2NCUyQ1BITjJaeUIzYVdSMGFEMGlNalVpSUdobGFXZG9kRDBpTWpZaUlIWnBaWGRDYjNnOUlqQWdNQ0F5TlNBeU5pSWdabWxzYkQwaWJtOXVaU0lnZUcxc2JuTTlJbWgwZEhBNkx5OTNkM2N1ZHpNdWIzSm5Mekl3TURBdmMzWm5JajRLUEhCaGRHZ2daRDBpVFRFeUxqYzJNRFFnTWpJdU9EazFPRXc1TGpjME9UTTFJREUyTGpJM01UVk1NeTR4TWpVZ01UTXVNall3TkV3NUxqYzBPVE0xSURFd0xqSTBPVE5NTVRJdU56WXdOQ0F6TGpZeU5Vd3hOUzQzTnpFMUlERXdMakkwT1ROTU1qSXVNemsxT0NBeE15NHlOakEwVERFMUxqYzNNVFVnTVRZdU1qY3hOVXd4TWk0M05qQTBJREl5TGpnNU5UaGFJaUJtYVd4c1BTSWpOalJET0RrMElpOCUyQkNqd3ZjM1puUGdvJTNEKStuby1yZXBlYXQrbGVmdCtjZW50ZXIlN0Q=

**Comment by Mckill3r** [comment]
Hi, i'm running on debian 10, the version return is : minify version master

**Comment by Mckill3r** [comment]
i have testing again on 1 file with only this css : 


```shell
cat test.css
div{background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjUiIGhlaWdodD0iMjYiIHZpZXdCb3g9IjAgMCAyNSAyNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyLjc2MDQgMjIuODk1OEw5Ljc0OTM1IDE2LjI3MTVMMy4xMjUgMTMuMjYwNEw5Ljc0OTM1IDEwLjI0OTNMMTIuNzYwNCAzLjYyNUwxNS43NzE1IDEwLjI0OTNMMjIuMzk1OCAxMy4yNjA0TDE1Ljc3MTUgMTYuMjcxNUwxMi43NjA0IDIyLjg5NThaIiBmaWxsPSIjNjRDODk0Ii8+Cjwvc3ZnPgo=) no-repeat left center;}
minify test.css
div{background:url(data:image/svg+xml,%3Csvg+width%3D%2225%22+height%3D%2226%22+viewBox%3D%220+0+25+26%22+fill%3D%22none%22+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath+d%3D%22M12.7604+22.8958+9.74935+16.2715+3.125+13.2604l6.62435-3.0111L12.7604+3.625l3.0111+6.6243+6.6243+3.0111-6.6243+3.0111-3.0111+6.6243z%22+fill%3D%22%2364c894%22%2F%3E%3C%2Fsvg%3E)no-repeat 0}
```

**Comment by Mckill3r** [comment]
I just find the current version : 

Version: 2.7.2-1+b6
Built-Using: golang-1.15 (= 1.15.9-6), golang-fsnotify (= 1.4.9-2), golang-github-dustin-go-humanize (= 1.0.0-2), golang-github-matryer-try (= 1+git20161228.6.9ac251b-2.1), golang-github-spf13-pflag (= 1.0.5-2), golang-github-tdewolff-parse (= 2.4.2-1), golang-golang-x-sys (= 0.0~git20210124.22da62e-1)
Priority: optional
Section: devel
Source: golang-github-tdewolff-minify (2.7.2-1

**Comment by Mckill3r** [comment]
I have updated the binary and everything is working fine :) thanks for your help

**Comment by tdewolff** [comment]
Thanks for the reply, great to hear it's working for you!
