### ISSUE TITLE
Octal escape sequences are not allowed

### ISSUE THREAD

**Issue by sank3** [tdewolff/minify#577]
When I compress a JS file,  It gives a syntax error when the JS is loaded in a browser.

`Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode. (at pdf-worker-min.js:28:110842)`

I have attached the original and minified files here.

[files.zip](https://github.com/tdewolff/minify/files/11438100/files.zip)

Module version v2.12.5
Golang 1.18

**Comment by tdewolff** [comment]
I've pushed a fix where escaped NULL characters are now replaced with a literal NULL. Can you please check if this works before I push out a new version?
