### ISSUE TITLE
Unexpected token '!' error after the JS files compressed

### ISSUE THREAD

**Issue by section1Q84** [tdewolff/minify#584]
The raw js files:
[combine.zip](https://github.com/tdewolff/minify/files/11716339/combine.zip)

**Comment by tdewolff** [comment]
Couldn't reproduce the exact error, but I got another error in the browser after running:

```bash
minify 1_jquery.min.js 2_bootstrap.min.js 3_jquery.placeholder.min.js 4_jquery.waypoints.min.js 6_main.js --bundle -o out.js
```

Let me know if this fixes it for you, and otherwise please post the exact command you used to reproduce the error.
