### ISSUE TITLE
cmd tool not work

### ISSUE THREAD

**Issue by awsom82** [tdewolff/minify#59]
after last updates 'cmd/minify' stop working, they does nothing.

just return same files without minification

**Comment by tdewolff** [comment]
The `-x` command-line argument has been renamed to `-type` to better adhere to the naming style of common tools. I've reflected that change in the readme now, sorry I had forgot that!

Let me know if that was the problem.

FYI: I will remove the `-d` argument soon. Directories would be passed in the `[input]` array, so you can minify multiple directories.

**Comment by awsom82** [comment]
Yeah, I've check code, and see that. But it does not help.

when i pass
```minify -type css public/css/fonts.css```

They return same file, without minification.
```
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  src: local('Source Sans Pro'), local('SourceSansPro-Regular'), url(/fonts/SourceSansPro.ttf) format('truetype');
}
```

**Comment by awsom82** [comment]
Thanks, Taco.
Now single files work

>FYI: I will remove the -d argument soon. Directories would be passed in the [input] array, so you can minify multiple directories.

`-d` won't work for now
`minify -d public/css/` does nothing.

I'am using static site generator. And my deploy script just pass `minify -d public/ -r`. And it was do all stuff, after that, I'm just move *.min* files over older ones and have all html, css etc minificated. it dramatically shrink all files. 

minify works well, but have few bugs with xml and on some page they remove tag name.
I report about that bugs in different tickets.

P.S. Im a switcher for golang, I'm just start lear it, it hard to help the project, but I'm try.

Thanks for the tool!
And have a good day!!

Igor.

**Comment by tdewolff** [comment]
If you could report bug reports for the files that got broken that would be great!
I must admit this CLI tool hasn't been my first priority, but I'll checkout the `-d` flag now.

And by the way, any help and participation is great, also from novice Go users!

**Comment by tdewolff** [comment]
Checkout the new CLI tool, I rewrote it completely to implement all the new features. Just update the package with `go get -u github.com/tdewolff/minify`. Let me know what you think.

Did you find those bugs you mentioned with XML files? Would be great if you could make an issue for those!

**Comment by awsom82** [comment]
@tdewolff wow, many thanks!
You are fantastic, man!!

I'm just start testing & using
Looks like problem with xml minification is gone.
Mystic problem with tag strange symbols described in #61

And few tickets is open #63 and #62
