### ISSUE TITLE
Support FastHTTP

### ISSUE THREAD

**Issue by gaby** [tdewolff/minify#590]
Currentl the Middleware() and MiddlewareWithError() functions only support `net/http`, would it be possible to add a separate one with support for FastHTTP?

**Comment by tdewolff** [comment]
Sure, what would be needed to support FastHTTP? Would you be able to create a PR for that?

**Comment by gaby** [comment]
@tdewolff I'm not sure, which is why I'm asking here. My guess is that it has something to do with doing a custom response write, but i'm not sure where to start.

**Comment by gaby** [comment]
I'm going to try some stuff, If i get it working I will post my solution here. I think it may work by getting the Response Body and passing that to `m.Bytes("text/html", body)`

**Comment by gaby** [comment]
As expected I was able to use the `fasthttp.Response().Body()` and pass it to `minified, err := m.Bytes()`

**Comment by tdewolff** [comment]
Great, thanks for sharing!
