### ISSUE TITLE
version 2.12.7  silently dropping some files in subfolders

### ISSUE THREAD

**Issue by iicuken** [tdewolff/minify#594]
i have this dir structure: 
./ 
 scripts.js  js.min.js
lib/
1jquery.min.js         jquery.form.min.js  jquery.jgrowl.min.js          owl.carousel.min.js
jquery-1.10.2.min.map  jquery.jgrowl.map   jquery.magnific-popup.min.js

when i am doing: 
rm js.min.js; minify  --recursive --bundle    lib   scripts.js   -o js.min.js

in recent versions it silently drops jquery.magnific-popup.min.js  when it in lib subfolder.
but when i copy jquery.magnific-popup.min.js in ./ folder  its all ok:
rm js.min.js; minify  --recursive --bundle    lib  jquery.magnific-popup.min.js
  scripts.js   -o js.min.js

I test prev versions  just about month  ago, it was no such problems.
map files in lib folder mean nothing here - when i delete them bug is in place

**Comment by tdewolff** [comment]
Thanks for reaching out, so your directory looks like:

```
- scripts.js
- js.min.js
- lib/
  - 1jquery.min.js
  - jquery.form.min.js
  - jquery.jgrowl.min.js
  - owl.carousel.min.js
  - jquery-1.10.2.min.map
  - jquery.jgrowl.map
  - jquery.magnific-popup.min.js
```

That is, only `scripts.js` is outside the `lib/` directory? And only `jquery.magnific-popup.min.js` doesn't get bundled? What is the output when you use the `--verbose` flag? I cannot reproduce this bug unfortunately.

**Comment by iicuken** [comment]
Good day.
Here test data for my issue:  https://kyrsi-rzn.ru/minfy_test.zip
Unzip and minify --recursive --bundle lib scripts.js -o js.min.js.
Then 'less js.min.js'. Search 'Kindle'  - word part of   jquery.magnific-popup.min.js.
See that no such word in js.min.js so no jquery.magnific-popup in js.min.js.

**Comment by tdewolff** [comment]
Thanks for the test case. It appeared that concatenating files caused an issue when the preceding file ends in a line comment, that is why the first line of  lib/jquery.magnific-popup.js was commented and removed from the output. This should now be fixed!
