### ISSUE TITLE
Panic with malformed conditional HTML comment

### ISSUE THREAD

**Issue by jmooring** [tdewolff/minify#596]
This issue should have a really, really low priority.

This works fine:

```text
<!--[if IE]>foo<![endif]-->
```

This causes a panic (it's malformed):

```
<!--[if IE]foo<![endif]-->
```

**Comment by tdewolff** [comment]
Thanks Joe as always! Actually, I believe panics are high priority, I'm surprised this wasn't caught by the fuzzer!
