### ISSUE TITLE
Github workflow for Python Wheels?

### ISSUE THREAD

**Issue by pydsigner** [tdewolff/minify#599]
Right now, the build and release of the python bindings seem to be an essentially manual process, and only produces sdists. Would you be open to a PR that adds a Github Action to build and publish wheels for various platforms? I don't have much experience with Go itself, but all the commands appear to be there in the Makefile and setup.py, just needing to be plugged into a standard workflow. After publishing pure-Python and PyO3 (Rust binding) packages, I'd be willing to give this a shot.

**Comment by tdewolff** [comment]
Thanks, that would be highly appreciated! And yes, the makefile is all it takes to publish (`make publish`). Looking forward to your PR! :-)

**Comment by pydsigner** [comment]
I have wheel builds working for x86_64 for Linux and Windows. I've disabled Mac builds because they seem to be an unsolved mess:
https://stackoverflow.com/questions/71530820/how-to-cross-compile-from-linux-amd64-to-darwin-arm64-with-cgo

This could perhaps be a solution worth checking out:
https://stackoverflow.com/questions/75209245/golang-cross-compiling-with-cgo-inside-docker-image

**Comment by tdewolff** [comment]
This is done, right?

**Comment by pydsigner** [comment]
I think so. I thought about editing it to have a checklist of things like macOS wheels, but that platform certainly wasn't in the explicit scope of the issue.

**Comment by tdewolff** [comment]
It was succesfully released to PyPI! Thanks a lot for the commitment!!!

**Comment by pydsigner** [comment]
Thanks for all your work to make this possible as well! Way too many PRs 😅
