### ISSUE TITLE
<h2> tag problem

### ISSUE THREAD

**Issue by awsom82** [tdewolff/minify#61]
Most strange error happened with `<h2 id="site-description">`.

Only on one page, they minified as
```
<п id=site-description>Разработка сайтов и мобильных приложений</h2>
```
 
Notice `п` instead of `h2`

This tag located in header, that block have same content on whole site.
But that bug appears only on one concrete page.

Site contents is cyrillic in UTF-8, generated by Hugo static site generator.
The generated content looks completely the same.

I will include two files, the [good.html](https://github.com/tdewolff/minify/files/33937/good.txt) and the [bad.html](https://github.com/tdewolff/minify/files/33938/bad.txt).
After minifation, the described problem appears in bad.

P.S. Sorry for .txt sources, github does not allow attaching a .html

**Comment by tdewolff** [comment]
Seems like a memory sanity issue. Great find, I can reproduce the issue. Will work on this after the weekend.
