### ISSUE TITLE
Optional chaining doesn't seem to work

### ISSUE THREAD

**Issue by guigiffoni** [tdewolff/minify#612]
Using optional chaining in JavaScript makes the minifier not generate the file.
Tested in version v2.19.10

[MDN Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by tdewolff** [comment]
Thanks for raising the issue, optional chaining should be supported, but it is strange that there is no output. What is your input? What JavaScript version do you pass to the JS minifer (e.g. `0`, or `2020`)?

**Comment by guigiffoni** [comment]
After checking closer, I realised that it does output the file, the issue is how I used optional chaining. It does not allow the usage of assignments, so: `this?.variable = 123` is not valid, and JavaScript throws `SyntaxError: invalid assignment left-hand side`.

Sorry for the inconvenience
[MDN Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_assignment_left-hand_side#using_optional_chaining_as_assignment_target)
