### ISSUE TITLE
Minify HTML using a CLI, issues can arise with the 'for...in' statement within script tags.

### ISSUE THREAD

**Issue by Yi-pixel** [tdewolff/minify#619]
I removed too much stuff so it wouldn't interfere, keeping only the smallest bit that can be reproduced.

I could change `var` to `let` or `const` to solve the problem, but this seems like it shouldn't happen.

When I format the code below using the CLI (minify v2.19.10) on Windows, it gives the unexpected.

- Command

```bash
minify2.exe --js-keep-var-names -o t1.html .\b.html
```

- Input: b.html

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
<script>
    try {
        function transformListInfo () {
            if (aid) {
                if (foo > 2) {
                    var item_list = [];
                    for (var i = 0; i < pro.length; i++) {item_list.push(pro[i].id + '');}
                } else if (typeof aid == 'object') {
                    var listInfo = getListInfo(pro_ids);
                    for (var i in listInfo) {
                        new_items.push(items_obj);
                    }
                    var item_list = [];
                    for (var i = 0; i < listInfo.length; i++) {item_list.push(listInfo[i].id + '');}
                }
            }
        }
    } catch (e) {console.warn(e);}
</script>
</html>
```

- Output: t1.html

```html
<!doctype html><html lang=en><meta charset=utf-8><meta name=viewport content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1"><meta http-equiv=x-ua-compatible content="ie=edge"><title>Document</title>
<script>try{function transformListInfo(){if(aid)if(foo>2)for(var item_list=[],i=0;i<pro.length;i++)item_list.push(pro[i].id+"");else if(typeof aid=="object"){var listInfo=getListInfo(pro_ids);for(in listInfo)new_items.push(items_obj);for(var item_list=[],i=0;i<listInfo.length;i++)item_list.push(listInfo[i].id+"")}}}catch(e){console.warn(e)}</script>
```

The above output may not be easy to read, there is a problem with `for...in` here

![image](https://github.com/tdewolff/minify/assets/31845646/384aecc6-21e4-4a74-8248-6415eddd0bbd)

When I remove the `--js-keep-var-names` option, the generated code will have no problems (but I still want to keep this option, because it helps me to accurately detect exceptions when they occur. position)

In some cases, Javascript minify may not be necessary, but currently there does not appear to be an option to disable JavaScript minify.

Looking forward to providing an option to disable JavaScript minify. Although I have cloned the code to my local machine and manually removed the JavaScript minify logic.

Thanks.

**Comment by tdewolff** [comment]
Thanks for the bug report! I can reproduce this and I'm working on a fix as soon as possible.

**Comment by tdewolff** [comment]
This has been fixed, please wait for a new release as I'm doing some fixes in the underlying `tdewolff/parse` library!

**Comment by Yi-pixel** [comment]
@tdewolff 

Sorry, I didn't reply in time due to some delays.

Thanks for the fix.

> By the way, regarding your comment on disabling JS minification, you could just not attach the JS minifier? Or are you using the command line interface?

Yes, I am processing my HTML files in my PHP code in a cli way.

However, JS and CSS are currently minified by default.

Can you provide a command line option to disable minifiers for CSS and JS?

But this may not help identify potential problems.

I currently clone the code myself and remove the relevant Minifier in `/cmd/minify/main.go`, which meets my needs.

Thanks.
