### ISSUE TITLE
[CMD] No carriage return symbol in help 

### ISSUE THREAD

**Issue by awsom82** [tdewolff/minify#62]
not a big problem, but may look better
![2015-11-13 15 55 45](https://cloud.githubusercontent.com/assets/5804704/11146438/669500aa-8a1f-11e5-87ac-db8e8f2a4b6b.png)

**Comment by tdewolff** [comment]
Do you mean that when lines overflow the width of the terminal, they are not properly indented? Like `wiki/Syntax` and `edende over -type`?

**Comment by awsom82** [comment]
No. The the last line not ended, and promt line in appers same line.

![669500aa-8a1f-11e5-87ac-db8e8f2a4b6b](https://cloud.githubusercontent.com/assets/5804704/11148447/de5c9568-8a2d-11e5-9b19-d128a49cf3b6.png)
