### ISSUE TITLE
Attribute value in form tag becaome lowcase

### ISSUE THREAD

**Issue by gyuber** [tdewolff/minify#620]
Hello~

special attribute are lowcased
example)
https://go.dev/play/p/5Ntxc6sP35r
```go
func main() {
	m := minify.New()
	m.Add("text/html", &html.Minifier{
		KeepQuotes:   true,
		KeepEndTags:  true,
		KeepComments: true,
	})

	m.AddFuncRegexp(regexp.MustCompile("^(application|text)/(x-)?(java|ecma)script$"), js.Minify)

	tag := `<form target="TarGet" method="Method">`
	s, err := m.String("text/html", tag)
	if err != nil {
		panic(err)
	}
	fmt.Println(s)
}

<form target="target" method="method">
```

expect 
```
<form target="TarGet" method="Method">
```

Can you help me?

**Comment by tdewolff** [comment]
Hi, the attribute value is case-insensitive. It shouldn't matter if it's lowercase. The minifier uses lowercase to improve the optimization by GZIP (after minification).

What is the problem you're having? Is this related to JS?

**Comment by gyuber** [comment]
I know that attribute name is case-insensitive.
but value is no mention

**Comment by tdewolff** [comment]
Well, the HTML minifier doesn't lowercase values in general, but a specific set of attribute are lowercased according to this list: https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-selectors

What problem do you have?

**Comment by gyuber** [comment]
Agree .. method can be case-insensitive..
Can I Check to [attrmap](https://github.com/tdewolff/minify/blob/cb84f810c28e8b55a6dafa619cdec71ee82a247f/html/table.go#L165) case-insensitive or case-sensitive ?

**Comment by tdewolff** [comment]
I've disabled attribute value lowercasing, it is causing too many problems for various users.
