### ISSUE TITLE
Bug: return statement causes error

### ISSUE THREAD

**Issue by alexander-zierhut** [tdewolff/minify#623]
`unexpected return in expression on line 37 and column 23`

![Screenshot from 2023-10-30 12-12-44](https://github.com/tdewolff/minify/assets/26348781/ea226ccc-a4f4-4d6a-a770-dc49645bc863)

I am guessing this is an error or is this formatting not allowed?
Is there an option to skip such lines, if there is an error?
Also, docker hub only has the `latest` tag, so I can't downgrade the version. Am I missing the tags?

**Comment by tdewolff** [comment]
Thanks, this bug seeped in with the last changes, should be fixed now!
