### ISSUE TITLE
Max amount of exclude statements

### ISSUE THREAD

**Issue by alexander-zierhut** [tdewolff/minify#624]
While working on #623, I tried a temporary fix by using the exclude statement like so:
```bash
minify
--recursive
--verbose
--exclude '**/folder1/**'
--exclude '**/folder2/**'
--exclude '**/folder3/**'
--output folder_output/
folder_input/
```
This results in:
`minify: must specify --type in order to use stdin and stdout`

[Possibly relevant code](https://github.com/tdewolff/minify/blob/master/cmd/minify/main.go#L251-L256)

**Comment by tdewolff** [comment]
Thanks, this was silly...there was still some debugging code in the `argp` package which prevented from parsing too many arguments. Should be fixed now.

On the issue, `--exclude` allows to pass multiple values, such as: `--exclude '**/folder1/**' '**/folder2/**' '**/folder3/**'` would work fine. This might give unexpected results when it is followed immediately by the input files, as it would be included in the excludes, and not inputs: `--exclude dir_to_exclude folder_input` would be unexpected. You would need to do: `--exclude dir_to_exclude -- folder_input`. I'm not 100% convinced if this is the way of "least surprises" by users...
