### ISSUE TITLE
Docker hub tags

### ISSUE THREAD

**Issue by alexander-zierhut** [tdewolff/minify#625]
While encountering an error today, I tried to downgrade. This doesn't seem possible using [docker hub](https://hub.docker.com/r/tdewolff/minify/tags).

Am I missing the tags?

![image](https://github.com/tdewolff/minify/assets/26348781/343eb0e3-021f-4581-ac7b-5b350707af95)

I recommend that the tags should reflect the versioning of Github.

**Comment by tdewolff** [comment]
I've updated the GitHub action, I believe the next version will create a version tag!

**Comment by limo49** [comment]
It seems that the latest version 2.20.6 (November 2, 2023) still does not have a tag on Docker

**Comment by tdewolff** [comment]
Thanks, there was a small typo in the workflow, should be fixed for the next version release!
