### ISSUE TITLE
JS: "SyntaxError: Invalid or unexpected token" after minifying pdfmake.js

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#653]
Minifying file [pdfmake.js](https://github.com/bpampuch/pdfmake/blob/0.2.9/build/pdfmake.js) (with default options) results in "SyntaxError: Invalid or unexpected token".

Last working version is v2.12.5.

Git bisect result:

9fbf9105be774ca8d4174c54f08525c799269319 is the first bad commit
commit 9fbf9105be774ca8d4174c54f08525c799269319
Author: Taco de Wolff <tacodewolff@gmail.com>
Date:   Sun May 14 21:21:45 2023 -0400

JS: decode unicode escape sequences in strings to UTF-8 literals

**Comment by tdewolff** [comment]
Thanks for raising this issue, this was fixed in 55d52d2cdf701ddaeff2483569946a1d1e72cf6f!
