### ISSUE TITLE
JS: '\u0022' minified to """

### ISSUE THREAD

**Issue by jpodeszfa** [tdewolff/minify#654]
One more bug in minimized strings.

'\u0022' is minified to """ and it ends in syntax error.

34d9a1213f5c8e70b30d492be09e875fb2552de0 is the first bad commit
commit 34d9a1213f5c8e70b30d492be09e875fb2552de0
Author: Taco de Wolff <tacodewolff@gmail.com>
Date:   Mon Sep 4 09:07:56 2023 +0200

    JS: fix bug in replacing unicode escapes; don't reparse already replaced escapes

**Comment by tdewolff** [comment]
Well, that was some buggy code in `minifyString`! Thanks for bringing this to my attention. Fixed it in the commit above and will be releasing a new version now.
