### ISSUE TITLE
Middleware skips some mimetype

### ISSUE THREAD

**Issue by ahdyt** [tdewolff/minify#660]
Hi there I'm using the minify Middleware and would like to skip some mimetype like image/png, because it's causing error. Is there any docs about it?

**Comment by tdewolff** [comment]
Was this fixed or was it never a problem?

**Comment by ahdyt** [comment]
Hi, I end up using below workaround, would be good if there's cleaner option.

`go

var fs http.Handler
if strings.Contains(r.URL.Path, ".html") || strings.Contains(r.URL.Path, ".css") || strings.Contains(r.URL.Path, ".js") || strings.Contains(r.URL.Path, ".svg") || strings.Contains(r.URL.Path, ".json") {
    fs = http.StripPrefix(pathPrefix, minify.Middleware(http.FileServer(root)))
} else {
    fs = http.StripPrefix(pathPrefix, http.FileServer(root))
}
fs.ServeHTTP(w, r)
`

**Comment by tdewolff** [comment]
I've pushed a fix so that unsupported mediatypes (extension or Content-Type) are passed without minification.
