### ISSUE TITLE
File 1.css has a restrictive license, triggering license scanning software.

### ISSUE THREAD

**Issue by nanderv** [tdewolff/minify#663]
The 1.css file is under a CC-NC-SA license, which triggers our license scanning software. Although this doesn't seem to be an issue (the file isn't actually compiled with), it would still be nice if it would be replaced by an equivalent, permissively licensed file.

**Comment by tdewolff** [comment]
Thanks, I've replace it

**Comment by nanderv** [comment]
Wow, fast fix :).
