### ISSUE TITLE
Regression error compiling jquery-1.12.4.js:  unexpected /*!

### ISSUE THREAD

**Issue by espinosa** [tdewolff/minify#664]
I try to minify  jquery-1.12.4.js
Worked fine with minify version 1.12.8 and 2.20.6
The error is with version 2.20.9 and upper.
I don't have tried with version 2.20.7-8

jquery source can be downloaded here: https://code.jquery.com/jquery-1.12.4.js
# Error
```
unexpected /*!
 * Sizzle CSS Selector Engine v2.2.1
 * http://sizzlejs.com/
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: 2015-10-17
 */ in expression on line 580 and column 1
  580: /*!
       ^
```

**Comment by tdewolff** [comment]
Thanks, issue has been fixed.
