### ISSUE TITLE
HTML: foreign elements themselves are not XML minified

### ISSUE THREAD

**Issue by luixxiul** [tdewolff/minify#67]
I got the following error:

````
This page contains the following errors:

error on line 1 at column 13: AttValue: " or ' expected
````

Removing quotes from ``height`` and ``width`` attributes seems to cause it.

**Comment by tdewolff** [comment]
Yes, that is because SVG must be valid XML, and XML forbids unquoted attribute values.

But it seems however that most browsers use the HTML parser for inline-SVG and the XML parser for standalone SVG. This is wrong according to the specs, but it might be convenient...

**Comment by luixxiul** [comment]
Yes, probably that is why the browser (chrome) does not show the linked SVG images.

**Comment by tdewolff** [comment]
We've discussed this in Gitter, but basically if you run the HTML minifier over an SVG, it will minify the SVG tag itself by the HTML minifier and its contents by the SVG minifier. It is unclear whether this poses a problem (does the SVG tag belong to the HTML or the SVG?) and the spec isn't very clear about this.

**Comment by tdewolff** [comment]
The [W3C HTML validator](https://validator.w3.org/nu/#textarea) confirms this bug with:

``` html
<!doctype html>
<html>
 <head>
  <title>title</title>
 </head>
 <body id=1>
  <svg id=2>
   <path d="M0.5 0.5z"/>
  </svg>
 </body>
</html>
```
