### ISSUE TITLE
"ERROR: src is not part of root path: src= root=" when using --watch and --bundle options on windows

### ISSUE THREAD

**Issue by espinosa** [tdewolff/minify#672]
2.12.8 OK
2.12.9 no exe in asset
v2.19.10 cannot start, exit
v2.20.0 cannot start, exit
v2.20.1 cannot start, exit
2.20.12 ERROR: src is not part of root path: src= root=
2.20.17 ERROR: src is not part of root path: src= root=

Maybe this bug was introduced with the version 2.12.9
The message is displayed on the first change of an input file once the command is running, not at the startup

**Comment by tdewolff** [comment]
Thanks, should be fixed now!

**Comment by espinosa** [comment]
Gracias Taco por su reactividad!
