### ISSUE TITLE
Compilation error on latest jquery.min.js

### ISSUE THREAD

**Issue by iicuken** [tdewolff/minify#689]
I have  bundle of javascript files for my site  where exists   latest jquery.min.js. 
In latest versions of minify i got error that  not happening before: 
minify   --bundle  --recursive  lib/1jquery.min.js      -o js.min.js                                                          
ERROR: cannot minify lib/1jquery.min.js: unexpected ! in expression on line 1 and column 60443
    1: ...is}}),c=l.props;for(!function(e,t){var n,...

This exaple illustrate that error happen only on latest jquery.min.js.
On non minifyed  latest jquery.js  all works fine. 

Minify version 2.20.10

**Comment by tdewolff** [comment]
This was fixed in [v2.20.13](https://github.com/tdewolff/minify/releases/tag/v2.20.13), please update to the latest version!
