### ISSUE TITLE
html, script space minify

### ISSUE THREAD

**Issue by gyuber** [tdewolff/minify#691]
I using mixed html, script text

```
<span>15      min</span>
<script>var v = "15      min"</script>
```

but html space working, script space not working
can you check if this is right?

let me share my test code
https://go.dev/play/p/OC3alMni7uR

**Comment by tdewolff** [comment]
Hi Hansung, yes this is correct. You specify a string literal with content `15      min`, we can't remove the spaces like we do with HTML. Only in HTML are multiple spaces the equivalent as a single space. In JS strings this is not the case...

**Comment by gyuber** [comment]
ok! i will find other way...
