### ISSUE TITLE
should sourceMappingURL be preserved?

### ISSUE THREAD

**Issue by Marzal** [tdewolff/minify#692]
Hi, newcomer to minify and CSS in general.

I'm playing with hugo and when using minify I get  `/*# sourceMappingURL=main.css.map */` removed from the last line.

I'm not sure if minify should treat this line as a especial case and keep it.

Thanks for this great project!

Resources:
https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/use_a_source_map/index.html
https://developer.chrome.com/blog/sourcemappingurl-and-sourceurl-syntax-changed
https://sourcemaps.info/spec.html

**Comment by tdewolff** [comment]
Thanks David, this has been implemented for CSS!

**Comment by Marzal** [comment]
Thanks, that was a quick response :+1:

**Comment by myitcv** [comment]
I've raised a bug from the perspective of Hugo as of https://github.com/gohugoio/hugo/issues/13654

**Comment by jmooring** [comment]
@myitcv Instead of commenting on a closed issue, please open a new issue in this repository..
