### ISSUE TITLE
javascript with calls to String.raw gets incorrectly minified

### ISSUE THREAD

**Issue by perrin4869** [tdewolff/minify#701]
I put together a small reproduction [here](https://github.com/perrin4869/minify-string-raw-repro)

**Comment by tdewolff** [comment]
Thanks Julian, should be fixed now!

**Comment by perrin4869** [comment]
thanks for the lightning speed fix 😄
when you have time, can you update the npm module? :)

**Comment by tdewolff** [comment]
Just churned out a new release, the NPM release should come up shortly after the GitHub action finishes.

**Comment by perrin4869** [comment]
seems the CI failed because the macos image doesn't have golang installed?

**Comment by tdewolff** [comment]
This is now fixed in the latest release!

**Comment by tdewolff** [comment]
Are you sure it is downloading the latest commit from GitHub? Maybe add a `go get -u github.com/tdewolff/minify/v2@v2.20.24` or `@latest` to make sure it uses the latest version (I've noticed it does some caching sometimes).

Otherwise, I believe that x86 will use the precompiled binaries from the GitHub workflow, but ARM will probably need to build from source, but that should just work...not sure what the problem could be...

**Comment by perrin4869** [comment]
btw, it seems we can soon run arm linux github actions :)
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by tdewolff** [comment]
You're right, I've made some changes, do they look good to you? If so, I'll release a 
new version for you to test.

PS: ARM support would be a great relieve!

**Comment by perrin4869** [comment]
I don't think those would work, because the makefile is calling `git` to produce the hash, but the node module isn't a git repository... I think you'd need to get those values and inject them into the make file at build time

**Comment by tdewolff** [comment]
Or perhaps just `go get -u github.com/tdewolff/minify/v2@latest`, that should get the latest version...the whole reason of the workflows and build scripts was to avoid changing the contents for every release (ie. I release a new version and the next commit involves updating the new version throughout all build files).

**Comment by perrin4869** [comment]
right, this is not a fun problem to solve ^^;;
the only problem with `go get -u github.com/tdewolff/minify/v2@latest` is that you would get unpredictable versions of the minifier...
I think what could work in a predictable fashion, is getting the version from the `package.json` file, perhaps via node or grep? But just using `latest` wouldn't be bad either, just not ideal

**Comment by perrin4869** [comment]
`node -e 'console.log(require("./package.json").version)'` seems to do the trick

**Comment by tdewolff** [comment]
I've pushed out a commit, it will work with the next version (or do you need me to release a new version?).

**Comment by perrin4869** [comment]
Thanks man! That's very helpful!!
Yeah, if you publish a new version I can update my code, otherwise I'll wait 🙂

**Comment by tdewolff** [comment]
I've just released v2.20.25 for you, let me know if it works!
