### ISSUE TITLE
Minify incorrectly removes spaces after `</code>` element that contains a template

### ISSUE THREAD

**Issue by infogulch** [tdewolff/minify#703]
`<code>` [is an inline element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code) but `minify` removes spaces after a closing `</code>` tag where the code element contains a template tag:

```html
<p>Hello, <code>{{""}}</code> abc</p>
```

...incorrectly minifies to (note the missing space before `abc`):
```html
<p>Hello, <code>{{""}}</code>abc</p>
```

In contrast, this:

```html
<p>Hello, <code></code> abc</p>
```

... correctly minifies to this:
```html
<p>Hello, <code></code> abc</p>
```

**Comment by tdewolff** [comment]
Thanks Joe, this has been fixed in the commit above.
