### ISSUE TITLE
How to minify HTML, but only HTML and JS i.e. excluding CSS

### ISSUE THREAD

**Issue by softwarespot** [tdewolff/minify#711]
I have checked the documentation and I know it's currently not possible to do, but curious how trivial would it be to minify HTML, in which CSS is skipped from minification?

My use case (see #710) is I would like to instead minify as HTML, but only HTML and JS, thus skipping the CSS,

I see https://github.com/tdewolff/minify/blob/master/html/html.go#L165 would likely be the place to implement such a fix, is this correct?

**Comment by tdewolff** [comment]
Are you using the library or the CLI? If you're using the library you can simply omit adding a CSS minifier, for example: omitting this line https://github.com/tdewolff/minify/blob/master/minify/minify.go#L20

Using the CLI there is unfortunately no way to disable minifiers, it's an all-or-nothing solution.

**Comment by softwarespot** [comment]
CLI, but I can build a CLI using the library, which is what I expected anyway. Just thought I would double check. Thanks again for getting back to me
