### ISSUE TITLE
JS: remove subsequent "use strict"s

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/minify#72]
Remove any occurrence of `"use strict"` after the first statement. This enables save concatenation of scripts and still valid JS code.

**Comment by omeid** [comment]
use strict is scope dependent.

```js

function strict(){
  // Function-level strict mode syntax
  'use strict';
  function nested() { return "And so am I!"; }
  return "Hi!  I'm a strict mode function!  " + nested();
}
function notStrict() { return "I'm not strict."; }
```

**Comment by tdewolff** [comment]
This will happen whenever a proper JS parser is written, see #18 
I will use #18 to keep track of things that need to happen for that parser
