### ISSUE TITLE
XML CDATA minify issue

### ISSUE THREAD

**Issue by amoledwatchfaces** [tdewolff/minify#722]
`<![CDATA[ %d ]]> `where empty space is before and after %d results in  " %d" - space after %d is stripped. 

Can this be improved in the future so CDATA maintains white spaces more properly?

**Comment by tdewolff** [comment]
In the general case, XML whitespace should be preserved as it is up to the parser/application to decide if it's significant (e.g. whitespace at the beginning or end of a tag). In most cases it is not significant, much like HTML, which has been the default for the XML minifier. You should enable the `KeepWhitespace` option to keep all whitespace at the start/end of a tag's content.

**Comment by amoledwatchfaces** [comment]
@tdewolff 

I've tried **KeepWhitespace** but it still removes empty spaces at the end of the CDATA content. 

Can I somehow force this inside of the CDATA?

**Comment by tdewolff** [comment]
Do you have a small but complete XML example? This shouldn't happen inside a tag.

**Comment by amoledwatchfaces** [comment]
> Do you have a small but complete XML example? This shouldn't happen inside a tag.

@tdewolff Here, test.xml, test-minify.xml & test-minify-keepwhitespace 
[test-xml.zip](https://github.com/user-attachments/files/16098709/test-xml.zip)

test.xml
![image](https://github.com/tdewolff/minify/assets/92080649/b01ff392-9095-4971-8b9b-523eb4eb3af5)

test-minify.xml (removes spaces completely)
![image](https://github.com/tdewolff/minify/assets/92080649/8cfdc09a-311b-41c1-98a6-c7faead87505)

test-keep-whitespace-minify (removes space at the end)
![image](https://github.com/tdewolff/minify/assets/92080649/e3d38021-3921-4d1a-9480-0891b171bfd2)

**Comment by amoledwatchfaces** [comment]
I would expect from simple minify to output this?
![image](https://github.com/tdewolff/minify/assets/92080649/62ec1110-b2b4-4268-b130-4131a3ab2863)

**Comment by tdewolff** [comment]
I believe that `test-minify.xml` outputs as expected. We can debate if the `KeepWhitespace` option should be on or off by default though.

The `test-keep-whitespace-minify.xml` is also as I expect. There is a whitespace before _and after_ the `%s` part: before it is a space 0x20, and after it is a newline 0x0A. Both are valid whitespace. Perhaps we shouldn't collapse multiple whitespace as we do in HTML?

The original content between `<Template>` and `<Parameter ...` is: `[space]%d[space][newline][tab][tab][tab][tab][tab][tab]`. You say you only expect the spaces to be kept but all other whitespace to be removed, or do you which to remove all whitespace? Then what is the purpose of minifying?

**Comment by amoledwatchfaces** [comment]
> You say you only expect the spaces to be kept but all other whitespace to be removed

This. Application that parses this xml needs to maintain all spaces correctly inside CDATA. This is used in a watch face renderer. 
So after minifying CDATA should keep all spaces correctly [0x20][%d][0x20].

Newline renders wrong result unfortunately. Perhaps there could be --xml-keep-cdata ?

**Comment by tdewolff** [comment]
I've added a fix that keeps all whitespace inside CDATA as-is.

**Comment by amoledwatchfaces** [comment]
Thanks! Two coffees on me ;)

**Comment by tdewolff** [comment]
Awesome, thank you very much!!

**Comment by amoledwatchfaces** [comment]
@tdewolff qq: is there any way to build windows CLI from the source code on windows?
So far all methods are working only with latest release which is v2.20.35

**Comment by tdewolff** [comment]
I've released v2.20.36 with this fix!

**Comment by amoledwatchfaces** [comment]
> I've released v2.20.36 with this fix!

Thanks! 🙂
