### ISSUE TITLE
Removing parenthesis of expression containing optional chaining can make different output

### ISSUE THREAD

**Issue by hyp3rflow** [tdewolff/minify#724]
Below program raises TypeError, because it can be reduced to `undefined.c`.
```javascript
((void 0)?.b).c;
```
However, the current implementation removes parenthesis so due to [the optional chaining specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), output will not raise TypeError.
```javascript
(void 0)?.b.c;
```

**Comment by tdewolff** [comment]
Fixed! Nice find
