### ISSUE TITLE
CLI doesn't handle directory inputs with trailing forward slashes on Windows

### ISSUE THREAD

**Issue by ChristianLW** [tdewolff/minify#726]
It seems that the CLI version no longer handles directory inputs properly.
Specifically, using a trailing slash doesn't prevent the directory name from being copied over.
For example, `minify -ro out/ src/` puts everything in **out/src/** instead of just **out/**.

It used to function with forward slashes, but seems to have broken at some point.
Generally, Windows does accept forward slashes as an "alternative path separator", so it should work.

I'm using v2.20.36 for Windows x64.

**Comment by tdewolff** [comment]
Thanks Christian, I believe a bugfix fixed the path separation problem on Windows but this meant that you could only use backslash as a path separator. I wasn't aware that on Windows you can use the forward slash as well. I've added a fix!
