### ISSUE TITLE
minify.exe run error Exception 0xc0000005

### ISSUE THREAD

**Issue by OmlineEditor** [tdewolff/minify#739]
when I launch the program an error appears and I can't use it

```
d:\work>minify.exe --help
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x46d03a
...
```

minify v2.20.37 ( minify_windows_amd64.zip )
Windows 7 x64 SP1
I know I have an old version of windows, but I can't use another one.

**Comment by tdewolff** [comment]
This is related to https://github.com/golang/go/issues/64622. You should perhaps try and clone the repository and run `go install ./cmd/minify` inside the repo's directory. That should give you a binary that works.
