### ISSUE TITLE
html: Whitespace isn't collapsed when text includes "&"

### ISSUE THREAD

**Issue by thatguystone** [tdewolff/minify#743]
The following HTML is valid (according to [the W3C validator](https://validator.w3.org/nu/#textarea)), but it's not being minified properly:

```html
<!doctype html>
<html lang="en">
<head><title>Lorem ipsum</title></head>
<h5>
	Lorem & ipsum, 
	elit.
</h5>
```

Got
```html
<!doctype html><html lang=en><title>Lorem ipsum</title><h5>Lorem & ipsum, 
	elit.
</h5>
```

Expected:
```html
<!doctype html><html lang=en><title>Lorem ipsum</title><h5>Lorem & ipsum, elit.</h5>
```

[Playground link](https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmh0bWwmc3JjPSUzQyFkb2N0eXBlK2h0bWwlM0UlMEQlMEElM0NodG1sK2xhbmclM0QlMjJlbiUyMiUzRSUwRCUwQSUzQ2hlYWQlM0UlM0N0aXRsZSUzRUxvcmVtK2lwc3VtJTNDJTJGdGl0bGUlM0UlM0MlMkZoZWFkJTNFJTBEJTBBJTNDaDUlM0UlMEQlMEElMDlMb3JlbSslMjYraXBzdW0lMkMrJTBEJTBBJTA5ZWxpdC4lMEQlMEElM0MlMkZoNSUzRQ==)

**Comment by tdewolff** [comment]
Thanks, this has now been fixed.
