### ISSUE TITLE
HTML: Space between text and <svg> tag is not preserved

### ISSUE THREAD

**Issue by scalisi** [tdewolff/minify#751]
`text <svg>` is minified to `text<svg>`. Is this intended?

Commit https://github.com/tdewolff/minify/commit/3dd6c8b3ef4b897604967ca6600f09f727dbae9d that was made in response to issue #89 ensured that space between text and an `<img>` is preserved, and I wasn't sure if space between text and an `<svg>` should also be preserved.

I started using `--html-keep-whitespace` as a solution to this issue and I really appreciate that this option exists. Thanks!

**Comment by tdewolff** [comment]
Thanks for the report, this has been fixed!
