### ISSUE TITLE
js: incorrect behavior when minifying optional chaining with bracket notation (a?.["b"])

### ISSUE THREAD

**Issue by ksw2000** [tdewolff/minify#757]
## Description

When using the minifier to process JavaScript code that includes optional chaining with bracket notation, such as `a?.["b"]`, the output is incorrect. This issue appears to be the root cause of #744 , where similar behavior was observed. The specific problem lies in how the minifier transforms `a?.["b"]` into `a?..b`, which is invalid JavaScript.

## Reproduce

In `js/js_test.go`

```go
func TestOptionalChainingWithBracket (t *testing.T) {
	m := minify.New()
	o := Minifier{KeepVarNames: true, useAlphabetVarNames: true}
	r := bytes.NewBufferString(`
		let a = {
			"b": "foo"
		};
		console.log(a.b);
		console.log(a?.b);
		console.log(a["b"]);
		console.log(a?.["b"]);    // Unexpected Behavior Here!!
	`)
	w := &bytes.Buffer{}
	o.Minify(m, w, r, nil)
	fmt.Println(w)
}
```

```sh
go test --run TestOptionalChainingWithBracket  -v
```

output:
```js
let a={b:"foo"};console.log(a.b),console.log(a?.b),console.log(a.b),console.log(a?..b)
```

The last line of the output `console.log(a?..b)` is incorrect. The minifier improperly handles the bracket notation in optional chaining, resulting in invalid JavaScript syntax.

## Expected Behavior

The minified code should correctly preserve the bracket notation in optional chaining. The expected output should be:

```js
let a={b:"foo"};console.log(a.b),console.log(a?.b),console.log(a.b),console.log(a?.["b"])
```

---

![image](https://github.com/user-attachments/assets/427cd95c-a677-41ac-b819-2172c1fbf954)

**Comment by tdewolff** [comment]
Fixed in v2.21.1, thank you!
