### ISSUE TITLE
css: removing whitespace breaks calc()

### ISSUE THREAD

**Issue by fatalbanana** [tdewolff/minify#767]
The whitespace inside some expression like `calc(100vh - 46px)`  appears to be required for some reason (apparently to distinguish operator vs negative 46) and the minifier is removing that.

**Comment by tdewolff** [comment]
Are you sure you're using v2 of this library? All your issues seem to work fine for me, e.g: https://go.tacodewolff.nl/minify?q=b21pbWU9dGV4dCUyRmNzcyZjc3MtcHJlY2lzaW9uPTAmc3JjPWElN0JjYWxjKDEwMHZoKy0rNDZweCklN0Q=

**Comment by fatalbanana** [comment]
Well, no. :( I was on 2.3.6 and not v2 ... Yes; everything looks good to me ....
