### ISSUE TITLE
space and attribute ends with /

### ISSUE THREAD

**Issue by hao1118** [tdewolff/minify#77]
`<select>
<option value="/new/">/new/</option>
</select>
`
becomes
`
<select>
<option value=/new/>/new/
</select>
`
then this option cannot display, because of "/>"

and the only one space between two elements in the same line should be kept, I think.

Thanks a lot!

**Comment by tdewolff** [comment]
What browser do you use? I've just tested this in Chrome and the select option works fine, with KeepWhitespace on and off.

The `/>` ending is valid HTML5 (but not HTML4), is that the problem? This minifier works only for HTML5, which is supported by all modern browsers.

What whitespace do you mean? All of your whitespace is conserved in this example...
