### ISSUE TITLE
Broken PHP tag minifying .html file

### ISSUE THREAD

**Issue by doompadee** [tdewolff/minify#777]
I have a HTML file with several PHP tags. The first tag is partially removed when minifying (during a Hugo build). Using the online demo:

    <span class="text-sm self-end">Name *</span> <?php echo $form->erroneous('name') ? $form->getErrorHint('name') : '' ?>
    <input name="name" type="text"<?php echo $form->erroneous('name') ? ' autofocus data-error' : '' ?><?php echo (isset($_POST['name']) && !empty($_POST['name'])) ? (' value="' . $_POST['name'] . '"') : '' ?> class="form-input">

becomes

    <span class="text-sm self-end">Name *</span> erroneous('name') ? $form->getErrorHint('name') : '' ?>
    <input name=name <?php echo $form->erroneous('name') ? ' autofocus data-error' : '' ?> class="form-input">

**Comment by tdewolff** [comment]
Do you have the PHP tags set as "TemplateDelim" for the HTML parser? The output you have is similar to what I get when I minify a PHP file as an HTML file (i.e. without setting the template delimiters).

**Comment by doompadee** [comment]
No, that was it!

Thanks much for your quick reaction. Have a great weekend!
