### ISSUE TITLE
learn to minify SVG with SVGOMG

### ISSUE THREAD

**Issue by tomByrer** [tdewolff/minify#78]
https://jakearchibald.github.io/svgomg/
What I use currently, 20-50% reduction.

**Comment by tdewolff** [comment]
Good point Tom. I know about SVGO and have been investigating their techniques. Over the last couple of months I have slowly implemented many of the techniques, they are in the `svg-paths` branch.

It isn't fully tested yet, that is why it hasn't been merged yet. The biggest impact on minification still has to be implemented and that is number truncation after the nth decimal (ie. rounding after three decimals for example). Merging paths into one `<path>` would also be a great addition.

So: I'm working on it! The path data compression has already been implemented and is most error-prone, so if you like it would be helpful if it was tested against various SVGs.

**Comment by tdewolff** [comment]
`svg-paths` has been merged into master. Decimal truncation has been implemented which greately enhances minification ratios. Merging pathdata will not be fixed soon because I will be away for several months.
