### ISSUE TITLE
Option to ignore js comments inside html script tag

### ISSUE THREAD

**Issue by Lakshmanshankar** [tdewolff/minify#780]
```html
<body>
<script type="application/ld+json" data-bullet-head-type="global">
// ignore
</script>
</body>
```

Error: Error building site: failed to render pages: failed to process "/portfolio/index.html": "/tmp/hugo-transform-error1566733714:315:67": JSON parse error: unexpected character '/' on line 315 and column 67
    2: // ignore
    
    
Currently, we cannot minify the page with a script tag that has a single-line or multiline comment. Is there any option to safely ignore these comments?

**Comment by tdewolff** [comment]
That looks difficult. You're saying that the content of the script tag is JSON-LD, but then it is invalid JSON-LD. You could either disconnect the JSON minifier or correct the invalid data. Not sure what else we can do here...

**Comment by Lakshmanshankar** [comment]
Hi Tdewolff,

Thank you for your quick response. I should have considered this earlier—your insights have significantly simplified things for us. I truly appreciate the time and effort you took to provide your input.
