### ISSUE TITLE
manage dependencies

### ISSUE THREAD

**Issue by rusenask** [tdewolff/minify#79]
Hello, thanks for this great library. I was wondering whether you could use vendor to manage your dependencies. This morning got a weird error due to updated Minify and https://github.com/tdewolff/strconv repositories. This could be avoided if you version your dependencies in this repository as well.

**Comment by tdewolff** [comment]
Thanks for the feedback. Do you mean that strconv needs to have a v1 as well? Or do you mean that the import paths must use gopkg with version information? I guess it is too late to add v1 dependency versioning for minify.v1...

What do you propose that could work? I am constantly working on the master branches of all the packages, and I try to keep them to compile together. Travis CI makes sure of that.

**Comment by rusenask** [comment]
hey, v1 is not needed on strconv, it would just be nice if you could have a /vendor/ dir in this library with it's own dependencies. Basically like this https://github.com/SpectoLabs/hoverfly/tree/master/vendor/github.com . The package then becomes autonomous so you will be sure that this library will still compile even though you update other master branches with breaking changes (since these git submodules will be pointing to specific git commits). 
Now I have added strconv to my own vendor packages but it's quite difficult to manage dependencies of your dependencies.. :)

**Comment by tdewolff** [comment]
I have asked a question on reddit (https://www.reddit.com/r/golang/comments/4fjv3e/what_is_the_preferred_way_of/) and I think it would be best that users would use their own preferred vendor method. In your case you should vendor all of my packages and not just minify. This way the dependency complexity of my packages remain simple and anyone can use their way of vendoring.

v2 has been added, which will compile when used with parse-v2. Also, all packages on tip should compile successfully (except for occasional breakage).

It might be better if cmd would be moved out to another package and have vendoring of my packages. Maybe I'll do this soon.
