### ISSUE TITLE
CSS: hsla color conversion skips % sign, if 3rd parameter is 0%

### ISSUE THREAD

**Issue by danchenkov** [tdewolff/minify#84]
`div.red { background-color: hsla(340, 100%, 0%, 1); }` minifies to `hsl(340,100%,0)`, which is an error in most browsers.

**Comment by tdewolff** [comment]
Thanks for notifying. It is because 0 and 0% should be the same thing, but maybe the browser expects a percentage. I'm away now but I will fix this in August

**Comment by danchenkov** [comment]
Added a PR 0ef68c54acd7449e8bc444203b6706e0d8f4ee45, would appreciate your review.

**Comment by tdewolff** [comment]
Fixed by merge #86
