### ISSUE TITLE
Do one thing, do it well.

### ISSUE THREAD

**Issue by omeid** [tdewolff/minify#9]
Hello there,

I really like the work you're doing but putting everything in a single package is not only not idiomatic Go but I believe it is generally advised against.

Is there any reason you haven't broke the CSS, HTML into their own packages and possibly provide a common interface?

I wanted to create a binding for a build system, [slurp](https://github.com/omeid/slurp), which I am using regularly but come across this issue, so I thought I would hear what you think.

**Comment by tdewolff** [comment]
Hi omeid,

Thanks for the feedback. I should indeed break the packages up, perhaps by using subpackages? Like tdewolff/minify/html and tdewolff/minify/css, what do you think?

There is a common interface for the minification functions, namely https://github.com/tdewolff/minify/blob/master/minify.go#L45 or what do you mean?

How did you get across this issue with slurp? What does it require?

**Comment by omeid** [comment]
Yes, sub packages would be great.

As for the common interface, I was talking more of an overall abstraction, namely the`Minifier`, to exist in the main package and use the subpackages as "providers".

I did not had technical problem, I just rather use well refined packages. :)

**Comment by tdewolff** [comment]
Minifiers are put in subpackages and the `Minifier` struct is an abstracted by an interface in 07fd6367fdc192e6ce30e129a85a94ffc73e6b69 and ffdf840d882c9ce34d62c1c92f843a1998d5c6fb
