### ISSUE TITLE
<html> and <head> tags are crucial

### ISSUE THREAD

**Issue by JoeArizona** [tdewolff/minify#90]
Hi Taco – If Minify removes `<html>` and `<head>` tags, it will break many, perhaps most, websites.

I know that the HTML spec describes those tags as optional, but they're not really optional on the modern web, for at least two reasons:

Those elements often have attached attributes. For example, here's the code from the page we're on right now (https://github.com/tdewolff/minify):

```
<html lang="en" class=" is-copy-enabled is-u2f-enabled">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
```

There are language tags on the HTML element, as well as a class, and then Open Graph metadata in the head tag, which is common. (Sometimes the og: metadata is in the HTML tag.) The metadata helps with FB and SEO.

The second reason is that the `<head>` element contains lots of metadata that is not consumed by the browser, but rather by social networks and search. There are a bunch of FB and Twitter lines, Dublin Core, and now Schema.org. It's important to note that the browser isn't the only consumer of the HTML. All that new metadata is for formatting links and cards on Twitter and FB when users link to a page. Those systems expect to find the metadata in the head element. It's not clear what they would do if there is no head. It would be crazy to delete those elements without thoroughly testing how it impacts the Twitter Card and similar metadata systems.

Also, deleting attribute quotes is a bad idea for security because it makes it much easier for Cross Site Scripting and other attacks to break out of the attribute value. This is mostly an issue when accepting untrusted input from users, like comments, but consistency in all markup is a good idea.

**Comment by tdewolff** [comment]
Hi Joe,

The minifier follows the spec and so should other programs. If some other application doesn't work but the spec allows it, this is a bug in that application. HTML5 is a pretty modern spec and it states these tags as being optional. Any modern parser MUST handle the spec properly to be called a HTML5 parser, this minifier relies on that fact.

Your first argument states that these tags might have attributes. That is correct, Minify will not remove tags that have attributes attached, as per the spec. So this should not be an issue.

Your second argument discusses that HTML parsers beside the browser's would not be spec compliant and unable to handle HTML that has no `<html>` or `<head>`. Usually most software use popular parsers from the stdlib or a well-known open-source project. These should be spec compliant and will handle such HTML files properly. Any implementation that does not handle missing `<head>` tags is simply not a valid HTML parser.

Deleting elements has little to do with XSS attacks, how would removing a tag increase XSS risk?

I'm sorry but I will not fix this issue. Do you have a specific use case that causes problems? I would like to know the problem you're having, perhaps there is room for improvement in the minifier.

**Comment by LazyZhu** [comment]
After minify, the website can't verified by Google's with the HTML tag `<meta name="google-site-verification" content="ID" />`, because the missing of `<html>` and `<head>`.
Can you add an option to avoid this?

**Comment by tdewolff** [comment]
Apparently this is indeed a more widespread problem of crawlers and spiders. I am still convinced that they have faulty implementations that do not follow the spec. I will consider including an exception or otherwise always keep the head tag. In the meantime you can give the head tag an attribute, so it will still be kept.

**Comment by mikegleasonjr** [comment]
Just to follow here (because I heavily relies on this amazing library), if you have only the meta tag for example in the head, the head will be removed and so the meta tag?

**Comment by tdewolff** [comment]
No. The minifier does not remove any information from the document, only superfluous text (according to the spec) is removed. Because a `head` tag can be inferred from the content, it is defined as an optional tag in the spec. This means that if you leave out `<head>` and `</head>` (and also for `html`), parsers can still find out what is what (ie. `title` and `meta` are always in `head`).

The problem is that some parsers don't follow this well. They look for a head tag and within there for a meta tag.

**Comment by mikegleasonjr** [comment]
OK so the meta name google verification thing shouldn't be an issue then

**Comment by tdewolff** [comment]
It shouldn't be, but LazyZhu says that apparently the Google verifier explicitly looks for `html` and `head` tags.

**Comment by d4l3k** [comment]
I'm running into this issue with my AMP website. The `<head>` and `<body>` tags are required for AMP to validate. Preferably a `KeepExtraTags` option would be added.

https://www.ampproject.org/docs/reference/spec#required-markup

**Comment by tdewolff** [comment]
Only the start tags are preserved, see if this is sufficient. Otherwise I'll make it keep end tags too.

**Comment by d4l3k** [comment]
Awesome, thanks!

In my experimental tests, it looks like the end tags are required as well. I worked around that though by adding `</head id>`.

**Comment by tdewolff** [comment]
It'll keep end tags now as well!

**Comment by tdewolff** [comment]
It's been renamed to `KeepDocumentTags` now.

**Comment by prakasa1904** [comment]
This is super cool library, not sure what's wrong with my config already use `KeepDocumentTags: true`... But somehow this is still break in my result... Running here https://www.okcarlomboktransport.com/

Response in head from:
```html
<meta
  name="google-site-verification"
  content="CEH3XvvbQeESzhP4pwuvM74vE2Cp5qgHRpmHNnzhD2s"
/>
```

to
```html
<meta name="google-site-verification" content="CEH3XvvbQeESzhP4pwuvM74vE2Cp5qgHRpmHNnzhD2s">
```

So google cannot verify my website,

**Comment by tdewolff** [comment]
Do you really think the ending `/` is required for Google site verification? I'm pretty sure that would break many websites...very surprising that Google uses an XML parser for parsing HTML...
