### ISSUE TITLE
Export minifierFunc

### ISSUE THREAD

**Issue by nishanths** [tdewolff/minify#91]
Export `minifierFunc` as `MinifierFunc`.

This would allows users to do things like:

```
funcs := map[string]minify.MinifierFunc{
		".css": css.Minify,
		".js":  js.Minify,
		".svg": svg.Minify,
}

fn := funcs[filepath.Ext(p)]
fn(m, out, in, nil)
```

**Comment by nishanths** [comment]
Have PR up for this: https://github.com/tdewolff/minify/pull/92. Thanks!

**Comment by tdewolff** [comment]
I'll review it this weekend!
