### ISSUE TITLE
Option to remove IE conditionals

### ISSUE THREAD

**Issue by mikegleasonjr** [tdewolff/minify#96]
It would be great since it is not supported in IE10+ and usage of IE9 is at ~1.6%

refs:
* https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx
* https://www.w3counter.com/trends

**Comment by tdewolff** [comment]
I wanted to remove that for a while now, since it is not spec compliant and is old. It didn't harm anyone to leave it in though, but it might be a good time to get rid of it.

**Comment by tdewolff** [comment]
Fixed by 89c0c97d443ccd730c839abd78db6a42ffd559e2

**Comment by mikegleasonjr** [comment]
Well that was fast! Big thank you :)

**Comment by dipbhi** [comment]
We still have to support IE8 :( and this fix is causing issue. Any way for me to use older code?
