### ISSUE TITLE
Tell which minifier was used

### ISSUE THREAD

**Issue by RReverser** [tdewolff/minify#97]
It would be convenient if all functions such as `m.Bytes`, `m.String` etc. would either return which minifier was used from given content-type or there would be separate helpers for 1) getting minifier from content-type and 2) passing it to any of these functions.

The reasoning is that those functions are pretty convenient to use, but if we want any kind of statistics per file format, we need to either duplicate format detection or rip logic out from those helpers basically reimplementing them in userland.

**Comment by tdewolff** [comment]
I can add a helper function that finds which match was found for the mediatype. It would return a function pointer (ie. variable of type `minify.Minifier`) for a given mediatype. Is that what you're looking for? I guess you'd have to compare it to the functions you supplied to find which one was used...

I'm wondering what to return when no minifier was suitable. `nil`? Or a default no-op minifier so you don't have to check for nil for this function, eg.: `m.Match(mediatype).Minify(m, w, r, nil)`

**Comment by tdewolff** [comment]
Please tell me what you think of the linked commit. It returns the matched pattern (mimetype or regex pattern), mediatype parameters and `MinifierFunc`.

**Comment by RReverser** [comment]
Function pointers and `nil` are fine for me, yes. Thank you!

> I guess you'd have to compare it to the functions you supplied to find which one was used...

Yeah, using map shouldn't be a problem in this case.

One thing still missing is, as described above, ability to pass chosen minifier to any helper. So, for example, for `.Bytes` or `.String`, I would need to perform match myself to get type and then call one one of these methods which would do match again - seems like a duplication of work. (Another option would be to replicate functionality of `Bytes` in own code, but that seems even worse).

**Comment by tdewolff** [comment]
I think you should just call the minify function yourself and convert the string to a bytes buffer. That is fairly trivial and only about 3 lines of code.

Besides, why not just call `Match` to see which function gets called, and then just call `Bytes` or `String` separately?

**Comment by tdewolff** [comment]
Wouldn't it be way easier if you implemented the `Match` function yourself anyways? It is a trivial piece of code. Besides, that saves keeping the minifier funcs in both your code and in the `M` struct in the package.  It seems inefficient this way. Also you can do the statistics too pretty easily.

**Comment by RReverser** [comment]
> I think you should just call the minify function yourself and convert the string to a bytes buffer. That is fairly trivial and only about 3 lines of code.

Slightly more in fact because of creating buffer, readers/writers, and converting back (`Minify` accepts only reader and writer).

> Besides, why not just call Match to see which function gets called, and then just call Bytes or String separately?

That's what I told above about duplication of same work - parsing `Content-Type`, finding a match etc. in runtime. Somewhat suboptimal for perf I guess.

> Wouldn't it be way easier if you implemented the Match function yourself anyways?

Well, this one, again, leads to duplication of parsing of content-types, and then keeping two separate maps (one internal in `M`, another in my code) from mime-types to values.

**Comment by RReverser** [comment]
Anyway, your commit solves the main concern, thanks for that :) I guess we can live with performance-wise concerns at this point.

**Comment by tdewolff** [comment]
> Well, this one, again, leads to duplication of parsing of content-types, and then keeping two separate maps (one internal in M, another in my code) from mime-types to values which can accidentally go out of sync and all other potential issues from code duplication.

No, you would own the map only in your code and you don't use `M`. You write your own match function (which is trivial!) and call the minifiers yourself. The `M` structure is merely a convenience layer on top of the minifiers. It is perfectly normal to call the minifiers yourself when you have a specific use-case.

To be honest, I'm thinking about reversing the commit because `Match` is not that useful. It has duplicate code with `MinifyMimetype` too. If anyone's use-case is different they would probably benefit from writing their own helper function anyways.

**Comment by RReverser** [comment]
> By the way, it is far from being a bottleneck to find the minifier for a given mediatype, you shouldn't have any performance issues.

Indeed, as I said this is rather a side concern. Important one was avoiding duplication of logic and mappings in own code, and that's solved now - thanks, so I'd rather close this issue.

**Comment by RReverser** [comment]
Btw, one more side thought: `Match` and `MinifyMimetype` seem to share pretty much same code right now - might be worth moving to common function or using one in another?
